# Generated by mix bibbidi.gen — do not edit manually
defmodule Bibbidi.Types.BrowsingContext.AccessibilityLocator do
  @moduledoc """
  `browsingContext.AccessibilityLocator`

  ## Fields

  - `type` - `"accessibility"` (required)
  - `value` - `map()` (required)
  """

  @schema Zoi.map(%{
            type: Zoi.string(),
            value:
              Zoi.map(%{
                name: Zoi.string() |> Zoi.optional(),
                role: Zoi.string() |> Zoi.optional()
              })
          })
  @type t :: %{type: String.t(), value: map()}

  @doc "Returns the Zoi schema for this type."
  def schema, do: @schema
end
