# Generated by mix bibbidi.gen — do not edit manually
defmodule Bibbidi.Types.BrowsingContext.BoxClipRectangle do
  @moduledoc """
  `browsingContext.BoxClipRectangle`

  ## Fields

  - `type` - `"box"` (required)
  - `x` - `float()` (required)
  - `y` - `float()` (required)
  - `width` - `float()` (required)
  - `height` - `float()` (required)
  """

  @schema Zoi.map(%{
            type: Zoi.string(),
            x: Zoi.float(),
            y: Zoi.float(),
            width: Zoi.float(),
            height: Zoi.float()
          })
  @type t :: %{type: String.t(), x: float(), y: float(), width: float(), height: float()}

  @doc "Returns the Zoi schema for this type."
  def schema, do: @schema
end
