# Generated by mix bibbidi.gen — do not edit manually
defmodule Bibbidi.Types.BrowsingContext.ClipRectangle do
  @moduledoc """
  `browsingContext.ClipRectangle`

  One of:
  - `t:Bibbidi.Types.BrowsingContext.BoxClipRectangle.t/0`
  - `t:Bibbidi.Types.BrowsingContext.ElementClipRectangle.t/0`
  """

  @schema Zoi.union([
            Zoi.lazy({Bibbidi.Types.BrowsingContext.BoxClipRectangle, :schema, []}),
            Zoi.lazy({Bibbidi.Types.BrowsingContext.ElementClipRectangle, :schema, []})
          ])
  @type t ::
          Bibbidi.Types.BrowsingContext.BoxClipRectangle.t()
          | Bibbidi.Types.BrowsingContext.ElementClipRectangle.t()

  @doc "Returns the Zoi schema for this type."
  def schema, do: @schema
end
