# Generated by mix bibbidi.gen — do not edit manually
defmodule Bibbidi.Types.BrowsingContext.ContextLocator do
  @moduledoc """
  `browsingContext.ContextLocator`

  ## Fields

  - `type` - `"context"` (required)
  - `value` - `map()` (required)
  """

  @schema Zoi.map(%{
            type: Zoi.string(),
            value: Zoi.map(%{context: Zoi.lazy({Bibbidi.Types.BrowsingContext, :schema, []})})
          })
  @type t :: %{type: String.t(), value: map()}

  @doc "Returns the Zoi schema for this type."
  def schema, do: @schema
end
