# Generated by mix bibbidi.gen — do not edit manually
defmodule Bibbidi.Types.BrowsingContext.CreateType do
  @moduledoc """
  `browsingContext.CreateType`

  Values: `tab`, `window`
  """

  @schema Zoi.enum(["tab", "window"])
  @type t :: String.t()
  @values ~w(tab window)

  @doc "Returns the Zoi schema for this type."
  def schema, do: @schema

  @doc "Returns the list of valid values."
  def values, do: @values
end
