# Generated by mix bibbidi.gen — do not edit manually
defmodule Bibbidi.Types.BrowsingContext.ImageFormat do
  @moduledoc """
  `browsingContext.ImageFormat`

  ## Fields

  - `type` - `String.t()` (required)
  - `quality` - `term()` (optional)
  """

  @schema Zoi.map(%{
            type: Zoi.string(),
            quality: Zoi.integer() |> Zoi.min(0.0) |> Zoi.max(1.0) |> Zoi.optional()
          })
  @type t :: %{type: String.t(), quality: integer() | nil}

  @doc "Returns the Zoi schema for this type."
  def schema, do: @schema
end
