# Generated by mix bibbidi.gen — do not edit manually
defmodule Bibbidi.Types.BrowsingContext.InfoList do
  @moduledoc """
  `browsingContext.InfoList`
  """

  @schema Zoi.list(Zoi.lazy({Bibbidi.Types.BrowsingContext.Info, :schema, []}))
  @type t :: [Bibbidi.Types.BrowsingContext.Info.t()]

  @doc "Returns the Zoi schema for this type."
  def schema, do: @schema
end
