# Generated by mix bibbidi.gen — do not edit manually
defmodule Bibbidi.Types.BrowsingContext.Info do
  @moduledoc """
  `browsingContext.Info`

  ## Fields

  - `children` - `t:Bibbidi.Types.BrowsingContext.InfoList.t/0` or `nil` (required)
  - `client_window` - `t:Bibbidi.Types.Browser.ClientWindow.t/0` (required)
  - `context` - `t:Bibbidi.Types.BrowsingContext.t/0` (required)
  - `original_opener` - `t:Bibbidi.Types.BrowsingContext.t/0` or `nil` (required)
  - `url` - `String.t()` (required)
  - `user_context` - `t:Bibbidi.Types.Browser.UserContext.t/0` (required)
  - `parent` - `t:Bibbidi.Types.BrowsingContext.t/0` or `nil` (optional)
  """

  @schema Zoi.map(%{
            children:
              Zoi.union([
                Zoi.lazy({Bibbidi.Types.BrowsingContext.InfoList, :schema, []}),
                Zoi.null()
              ]),
            client_window: Zoi.lazy({Bibbidi.Types.Browser.ClientWindow, :schema, []}),
            context: Zoi.lazy({Bibbidi.Types.BrowsingContext, :schema, []}),
            original_opener:
              Zoi.union([Zoi.lazy({Bibbidi.Types.BrowsingContext, :schema, []}), Zoi.null()]),
            url: Zoi.string(),
            user_context: Zoi.lazy({Bibbidi.Types.Browser.UserContext, :schema, []}),
            parent:
              Zoi.union([Zoi.lazy({Bibbidi.Types.BrowsingContext, :schema, []}), Zoi.null()])
              |> Zoi.optional()
          })
  @type t :: %{
          children: Bibbidi.Types.BrowsingContext.InfoList.t() | nil,
          client_window: Bibbidi.Types.Browser.ClientWindow.t(),
          context: Bibbidi.Types.BrowsingContext.t(),
          original_opener: Bibbidi.Types.BrowsingContext.t() | nil,
          url: String.t(),
          user_context: Bibbidi.Types.Browser.UserContext.t(),
          parent: Bibbidi.Types.BrowsingContext.t() | nil | nil
        }

  @doc "Returns the Zoi schema for this type."
  def schema, do: @schema
end
