# Generated by mix bibbidi.gen — do not edit manually
defmodule Bibbidi.Types.BrowsingContext.InnerTextLocator do
  @moduledoc """
  `browsingContext.InnerTextLocator`

  ## Fields

  - `type` - `"innerText"` (required)
  - `value` - `String.t()` (required)
  - `ignore_case` - `boolean()` (optional)
  - `match_type` - `"full"` or `"partial"` (optional)
  - `max_depth` - `t:Bibbidi.Types.JsUint.t/0` (optional)
  """

  @schema Zoi.map(%{
            type: Zoi.string(),
            value: Zoi.string(),
            ignore_case: Zoi.boolean() |> Zoi.optional(),
            match_type: Zoi.union([Zoi.string(), Zoi.string()]) |> Zoi.optional(),
            max_depth: Zoi.lazy({Bibbidi.Types.JsUint, :schema, []}) |> Zoi.optional()
          })
  @type t :: %{
          type: String.t(),
          value: String.t(),
          ignore_case: boolean() | nil,
          match_type: String.t() | nil,
          max_depth: Bibbidi.Types.JsUint.t() | nil
        }

  @doc "Returns the Zoi schema for this type."
  def schema, do: @schema
end
