# Generated by mix bibbidi.gen — do not edit manually
defmodule Bibbidi.Types.BrowsingContext.Locator do
  @moduledoc """
  `browsingContext.Locator`

  One of:
  - `t:Bibbidi.Types.BrowsingContext.AccessibilityLocator.t/0`
  - `t:Bibbidi.Types.BrowsingContext.CssLocator.t/0`
  - `t:Bibbidi.Types.BrowsingContext.ContextLocator.t/0`
  - `t:Bibbidi.Types.BrowsingContext.InnerTextLocator.t/0`
  - `t:Bibbidi.Types.BrowsingContext.XpathLocator.t/0`
  """

  @schema Zoi.union([
            Zoi.lazy({Bibbidi.Types.BrowsingContext.AccessibilityLocator, :schema, []}),
            Zoi.lazy({Bibbidi.Types.BrowsingContext.CssLocator, :schema, []}),
            Zoi.lazy({Bibbidi.Types.BrowsingContext.ContextLocator, :schema, []}),
            Zoi.lazy({Bibbidi.Types.BrowsingContext.InnerTextLocator, :schema, []}),
            Zoi.lazy({Bibbidi.Types.BrowsingContext.XpathLocator, :schema, []})
          ])
  @type t ::
          Bibbidi.Types.BrowsingContext.AccessibilityLocator.t()
          | Bibbidi.Types.BrowsingContext.CssLocator.t()
          | Bibbidi.Types.BrowsingContext.ContextLocator.t()
          | Bibbidi.Types.BrowsingContext.InnerTextLocator.t()
          | Bibbidi.Types.BrowsingContext.XpathLocator.t()

  @doc "Returns the Zoi schema for this type."
  def schema, do: @schema
end
