# Generated by mix bibbidi.gen — do not edit manually
defmodule Bibbidi.Types.BrowsingContext.PrintPageParameters do
  @moduledoc """
  `browsingContext.PrintPageParameters`

  ## Fields

  - `height` - `term()` (optional)
  - `width` - `term()` (optional)
  """

  @schema Zoi.map(%{height: Zoi.any() |> Zoi.optional(), width: Zoi.any() |> Zoi.optional()})
  @type t :: %{height: term() | nil, width: term() | nil}

  @doc "Returns the Zoi schema for this type."
  def schema, do: @schema
end
