# Generated by mix bibbidi.gen — do not edit manually
defmodule Bibbidi.Types.BrowsingContext.PrintMarginParameters do
  @moduledoc """
  `browsingContext.PrintMarginParameters`

  ## Fields

  - `bottom` - `term()` (optional)
  - `left` - `term()` (optional)
  - `right` - `term()` (optional)
  - `top` - `term()` (optional)
  """

  @schema Zoi.map(%{
            bottom: Zoi.any() |> Zoi.optional(),
            left: Zoi.any() |> Zoi.optional(),
            right: Zoi.any() |> Zoi.optional(),
            top: Zoi.any() |> Zoi.optional()
          })
  @type t :: %{bottom: term() | nil, left: term() | nil, right: term() | nil, top: term() | nil}

  @doc "Returns the Zoi schema for this type."
  def schema, do: @schema
end
