# Generated by mix bibbidi.gen — do not edit manually
defmodule Bibbidi.Types.BrowsingContext.ReadinessState do
  @moduledoc """
  `browsingContext.ReadinessState`

  Values: `none`, `interactive`, `complete`
  """

  @schema Zoi.enum(["none", "interactive", "complete"])
  @type t :: String.t()
  @values ~w(none interactive complete)

  @doc "Returns the Zoi schema for this type."
  def schema, do: @schema

  @doc "Returns the list of valid values."
  def values, do: @values
end
