# Generated by mix bibbidi.gen — do not edit manually
defmodule Bibbidi.Types.BrowsingContext.UserPromptType do
  @moduledoc """
  `browsingContext.UserPromptType`

  Values: `alert`, `beforeunload`, `confirm`, `prompt`
  """

  @schema Zoi.enum(["alert", "beforeunload", "confirm", "prompt"])
  @type t :: String.t()
  @values ~w(alert beforeunload confirm prompt)

  @doc "Returns the Zoi schema for this type."
  def schema, do: @schema

  @doc "Returns the list of valid values."
  def values, do: @values
end
