# Generated by mix bibbidi.gen — do not edit manually
defmodule Bibbidi.Types.Log.Level do
  @moduledoc """
  `log.Level`

  Values: `debug`, `info`, `warn`, `error`
  """

  @schema Zoi.enum(["debug", "info", "warn", "error"])
  @type t :: String.t()
  @values ~w(debug info warn error)

  @doc "Returns the Zoi schema for this type."
  def schema, do: @schema

  @doc "Returns the list of valid values."
  def values, do: @values
end
