# Generated by mix bibbidi.gen — do not edit manually
defmodule Bibbidi.Commands.Storage.DeleteCookies do
  @moduledoc """
  Command struct for `storage.deleteCookies`.

  [WebDriver BiDi Spec](https://w3c.github.io/webdriver-bidi/#command-storage-deleteCookies)
  ## Fields

  - `filter` - `t:Bibbidi.Types.Storage.CookieFilter.t/0` (optional)
  - `partition` - `t:Bibbidi.Types.Storage.PartitionDescriptor.t/0` (optional)

  """

  @derive Bibbidi.Telemetry.Metadata
  @schema Zoi.struct(__MODULE__, %{
            filter: Bibbidi.Types.Storage.CookieFilter.schema() |> Zoi.optional(),
            partition: Bibbidi.Types.Storage.PartitionDescriptor.schema() |> Zoi.optional(),
            meta: Zoi.any() |> Zoi.optional()
          })
  @opts_schema Zoi.keyword(
                 filter: Zoi.any() |> Zoi.optional(),
                 partition: Zoi.any() |> Zoi.optional()
               )
  @result_schema Zoi.map(%{partition_key: Zoi.any()})

  @type t :: unquote(Zoi.type_spec(@schema))
  @type opts :: unquote(Zoi.type_spec(@opts_schema))
  @type result :: unquote(Zoi.type_spec(@result_schema))

  @enforce_keys Zoi.Struct.enforce_keys(@schema)
  defstruct Zoi.Struct.struct_fields(@schema)

  @doc "Returns the Zoi schema for this command struct."
  def schema, do: @schema

  @doc "Returns the Zoi schema for the keyword options."
  def opts_schema, do: @opts_schema

  @doc "Returns the Zoi schema for the result type."
  def result_schema, do: @result_schema

  defimpl Bibbidi.Encodable do
    def method(_), do: "storage.deleteCookies"

    def params(cmd) do
      optional = [
        {:filter, cmd.filter},
        {:partition, cmd.partition}
      ]

      Enum.reduce(optional, %{}, fn
        {_key, nil}, acc -> acc
        {key, value}, acc -> Map.put(acc, key, value)
      end)
    end
  end
end
