# Generated by mix bibbidi.gen — do not edit manually
defmodule Bibbidi.Types.BrowsingContext do
  @moduledoc """
  Type definitions and Zoi schemas for the `browsingContext` module of the WebDriver BiDi protocol.

  Each type has:
  - A `@type` spec derived from the Zoi schema (for Dialyzer)
  - A function returning the Zoi schema (for runtime validation)
  """

  @browsing_context_schema Zoi.string()
  @type browsing_context :: unquote(Zoi.type_spec(@browsing_context_schema))

  @locator_schema Zoi.union([Zoi.any(), Zoi.any(), Zoi.any(), Zoi.any(), Zoi.any()])
  @type locator :: unquote(Zoi.type_spec(@locator_schema))

  @accessibility_locator_schema Zoi.map(%{
                                  type: Zoi.string(),
                                  value:
                                    Zoi.map(%{
                                      name: Zoi.string() |> Zoi.optional(),
                                      role: Zoi.string() |> Zoi.optional()
                                    })
                                })
  @type accessibility_locator :: unquote(Zoi.type_spec(@accessibility_locator_schema))

  @css_locator_schema Zoi.map(%{type: Zoi.string(), value: Zoi.string()})
  @type css_locator :: unquote(Zoi.type_spec(@css_locator_schema))

  @context_locator_schema Zoi.map(%{type: Zoi.string(), value: Zoi.map(%{context: Zoi.any()})})
  @type context_locator :: unquote(Zoi.type_spec(@context_locator_schema))

  @inner_text_locator_schema Zoi.map(%{
                               type: Zoi.string(),
                               value: Zoi.string(),
                               ignore_case: Zoi.boolean() |> Zoi.optional(),
                               match_type:
                                 Zoi.union([Zoi.string(), Zoi.string()]) |> Zoi.optional(),
                               max_depth: Zoi.any() |> Zoi.optional()
                             })
  @type inner_text_locator :: unquote(Zoi.type_spec(@inner_text_locator_schema))

  @x_path_locator_schema Zoi.map(%{type: Zoi.string(), value: Zoi.string()})
  @type x_path_locator :: unquote(Zoi.type_spec(@x_path_locator_schema))

  @navigation_schema Zoi.string()
  @type navigation :: unquote(Zoi.type_spec(@navigation_schema))

  @readiness_state_schema Zoi.union([Zoi.string(), Zoi.string(), Zoi.string()])
  @type readiness_state :: unquote(Zoi.type_spec(@readiness_state_schema))

  @user_prompt_type_schema Zoi.union([Zoi.string(), Zoi.string(), Zoi.string(), Zoi.string()])
  @type user_prompt_type :: unquote(Zoi.type_spec(@user_prompt_type_schema))

  @activate_parameters_schema Zoi.map(%{context: Zoi.any()})
  @type activate_parameters :: unquote(Zoi.type_spec(@activate_parameters_schema))

  @capture_screenshot_parameters_schema Zoi.map(%{
                                          context: Zoi.any(),
                                          origin: Zoi.any() |> Zoi.optional(),
                                          format: Zoi.any() |> Zoi.optional(),
                                          clip: Zoi.any() |> Zoi.optional()
                                        })
  @type capture_screenshot_parameters ::
          unquote(Zoi.type_spec(@capture_screenshot_parameters_schema))

  @image_format_schema Zoi.map(%{
                         type: Zoi.string(),
                         quality: Zoi.integer() |> Zoi.min(0.0) |> Zoi.max(1.0) |> Zoi.optional()
                       })
  @type image_format :: unquote(Zoi.type_spec(@image_format_schema))

  @clip_rectangle_schema Zoi.union([Zoi.any(), Zoi.any()])
  @type clip_rectangle :: unquote(Zoi.type_spec(@clip_rectangle_schema))

  @element_clip_rectangle_schema Zoi.map(%{type: Zoi.string(), element: Zoi.any()})
  @type element_clip_rectangle :: unquote(Zoi.type_spec(@element_clip_rectangle_schema))

  @box_clip_rectangle_schema Zoi.map(%{
                               type: Zoi.string(),
                               x: Zoi.float(),
                               y: Zoi.float(),
                               width: Zoi.float(),
                               height: Zoi.float()
                             })
  @type box_clip_rectangle :: unquote(Zoi.type_spec(@box_clip_rectangle_schema))

  @close_parameters_schema Zoi.map(%{
                             context: Zoi.any(),
                             prompt_unload: Zoi.boolean() |> Zoi.optional()
                           })
  @type close_parameters :: unquote(Zoi.type_spec(@close_parameters_schema))

  @create_type_schema Zoi.union([Zoi.string(), Zoi.string()])
  @type create_type :: unquote(Zoi.type_spec(@create_type_schema))

  @create_parameters_schema Zoi.map(%{
                              type: Zoi.any(),
                              reference_context: Zoi.any() |> Zoi.optional(),
                              background: Zoi.boolean() |> Zoi.optional(),
                              user_context: Zoi.any() |> Zoi.optional()
                            })
  @type create_parameters :: unquote(Zoi.type_spec(@create_parameters_schema))

  @get_tree_parameters_schema Zoi.map(%{
                                max_depth: Zoi.any() |> Zoi.optional(),
                                root: Zoi.any() |> Zoi.optional()
                              })
  @type get_tree_parameters :: unquote(Zoi.type_spec(@get_tree_parameters_schema))

  @handle_user_prompt_parameters_schema Zoi.map(%{
                                          context: Zoi.any(),
                                          accept: Zoi.boolean() |> Zoi.optional(),
                                          user_text: Zoi.string() |> Zoi.optional()
                                        })
  @type handle_user_prompt_parameters ::
          unquote(Zoi.type_spec(@handle_user_prompt_parameters_schema))

  @locate_nodes_parameters_schema Zoi.map(%{
                                    context: Zoi.any(),
                                    locator: Zoi.any(),
                                    max_node_count: Zoi.any() |> Zoi.optional(),
                                    serialization_options: Zoi.any() |> Zoi.optional(),
                                    start_nodes: Zoi.list(Zoi.any()) |> Zoi.optional()
                                  })
  @type locate_nodes_parameters :: unquote(Zoi.type_spec(@locate_nodes_parameters_schema))

  @navigate_parameters_schema Zoi.map(%{
                                context: Zoi.any(),
                                url: Zoi.string(),
                                wait: Zoi.any() |> Zoi.optional()
                              })
  @type navigate_parameters :: unquote(Zoi.type_spec(@navigate_parameters_schema))

  @print_parameters_schema Zoi.map(%{
                             context: Zoi.any(),
                             background: Zoi.boolean() |> Zoi.optional(),
                             margin: Zoi.any() |> Zoi.optional(),
                             orientation: Zoi.any() |> Zoi.optional(),
                             page: Zoi.any() |> Zoi.optional(),
                             page_ranges:
                               Zoi.list(Zoi.union([Zoi.any(), Zoi.string()])) |> Zoi.optional(),
                             scale: Zoi.any() |> Zoi.optional(),
                             shrink_to_fit: Zoi.boolean() |> Zoi.optional()
                           })
  @type print_parameters :: unquote(Zoi.type_spec(@print_parameters_schema))

  @print_margin_parameters_schema Zoi.map(%{
                                    bottom: Zoi.any() |> Zoi.optional(),
                                    left: Zoi.any() |> Zoi.optional(),
                                    right: Zoi.any() |> Zoi.optional(),
                                    top: Zoi.any() |> Zoi.optional()
                                  })
  @type print_margin_parameters :: unquote(Zoi.type_spec(@print_margin_parameters_schema))

  @print_page_parameters_schema Zoi.map(%{
                                  height: Zoi.any() |> Zoi.optional(),
                                  width: Zoi.any() |> Zoi.optional()
                                })
  @type print_page_parameters :: unquote(Zoi.type_spec(@print_page_parameters_schema))

  @reload_parameters_schema Zoi.map(%{
                              context: Zoi.any(),
                              ignore_cache: Zoi.boolean() |> Zoi.optional(),
                              wait: Zoi.any() |> Zoi.optional()
                            })
  @type reload_parameters :: unquote(Zoi.type_spec(@reload_parameters_schema))

  @set_viewport_parameters_schema Zoi.map(%{
                                    context: Zoi.any() |> Zoi.optional(),
                                    viewport:
                                      Zoi.union([Zoi.any(), Zoi.null()]) |> Zoi.optional(),
                                    device_pixel_ratio:
                                      Zoi.union([Zoi.float(), Zoi.null()]) |> Zoi.optional(),
                                    user_contexts: Zoi.list(Zoi.any()) |> Zoi.optional()
                                  })
  @type set_viewport_parameters :: unquote(Zoi.type_spec(@set_viewport_parameters_schema))

  @viewport_schema Zoi.map(%{width: Zoi.any(), height: Zoi.any()})
  @type viewport :: unquote(Zoi.type_spec(@viewport_schema))

  @traverse_history_parameters_schema Zoi.map(%{context: Zoi.any(), delta: Zoi.any()})
  @type traverse_history_parameters :: unquote(Zoi.type_spec(@traverse_history_parameters_schema))

  @info_list_schema Zoi.list(Zoi.any())
  @type info_list :: unquote(Zoi.type_spec(@info_list_schema))

  @info_schema Zoi.map(%{
                 children: Zoi.union([Zoi.any(), Zoi.null()]),
                 client_window: Zoi.any(),
                 context: Zoi.any(),
                 original_opener: Zoi.union([Zoi.any(), Zoi.null()]),
                 url: Zoi.string(),
                 user_context: Zoi.any(),
                 parent: Zoi.union([Zoi.any(), Zoi.null()]) |> Zoi.optional()
               })
  @type info :: unquote(Zoi.type_spec(@info_schema))

  @base_navigation_info_schema Zoi.map(Zoi.string(), Zoi.any())
  @type base_navigation_info :: unquote(Zoi.type_spec(@base_navigation_info_schema))

  @navigation_info_schema Zoi.map(%{})
  @type navigation_info :: unquote(Zoi.type_spec(@navigation_info_schema))

  @activate_result_schema Zoi.any()
  @type activate_result :: unquote(Zoi.type_spec(@activate_result_schema))

  @capture_screenshot_result_schema Zoi.map(%{data: Zoi.string()})
  @type capture_screenshot_result :: unquote(Zoi.type_spec(@capture_screenshot_result_schema))

  @close_result_schema Zoi.any()
  @type close_result :: unquote(Zoi.type_spec(@close_result_schema))

  @create_result_schema Zoi.map(%{context: Zoi.any(), user_context: Zoi.any() |> Zoi.optional()})
  @type create_result :: unquote(Zoi.type_spec(@create_result_schema))

  @get_tree_result_schema Zoi.map(%{contexts: Zoi.any()})
  @type get_tree_result :: unquote(Zoi.type_spec(@get_tree_result_schema))

  @handle_user_prompt_result_schema Zoi.any()
  @type handle_user_prompt_result :: unquote(Zoi.type_spec(@handle_user_prompt_result_schema))

  @locate_nodes_result_schema Zoi.map(%{nodes: Zoi.list(Zoi.any())})
  @type locate_nodes_result :: unquote(Zoi.type_spec(@locate_nodes_result_schema))

  @navigate_result_schema Zoi.map(%{
                            navigation: Zoi.union([Zoi.any(), Zoi.null()]),
                            url: Zoi.string()
                          })
  @type navigate_result :: unquote(Zoi.type_spec(@navigate_result_schema))

  @print_result_schema Zoi.map(%{data: Zoi.string()})
  @type print_result :: unquote(Zoi.type_spec(@print_result_schema))

  @reload_result_schema Zoi.any()
  @type reload_result :: unquote(Zoi.type_spec(@reload_result_schema))

  @set_viewport_result_schema Zoi.any()
  @type set_viewport_result :: unquote(Zoi.type_spec(@set_viewport_result_schema))

  @traverse_history_result_schema Zoi.any()
  @type traverse_history_result :: unquote(Zoi.type_spec(@traverse_history_result_schema))

  @history_updated_parameters_schema Zoi.map(%{
                                       context: Zoi.any(),
                                       timestamp: Zoi.any(),
                                       url: Zoi.string(),
                                       user_context: Zoi.any() |> Zoi.optional()
                                     })
  @type history_updated_parameters :: unquote(Zoi.type_spec(@history_updated_parameters_schema))

  @download_will_begin_params_schema Zoi.map(%{suggested_filename: Zoi.string()})
  @type download_will_begin_params :: unquote(Zoi.type_spec(@download_will_begin_params_schema))

  @download_end_params_schema Zoi.map(%{})
  @type download_end_params :: unquote(Zoi.type_spec(@download_end_params_schema))

  @download_canceled_params_schema Zoi.map(Zoi.string(), Zoi.any())
  @type download_canceled_params :: unquote(Zoi.type_spec(@download_canceled_params_schema))

  @download_complete_params_schema Zoi.map(Zoi.string(), Zoi.any())
  @type download_complete_params :: unquote(Zoi.type_spec(@download_complete_params_schema))

  @user_prompt_closed_parameters_schema Zoi.map(%{
                                          context: Zoi.any(),
                                          accepted: Zoi.boolean(),
                                          type: Zoi.any(),
                                          user_context: Zoi.any() |> Zoi.optional(),
                                          user_text: Zoi.string() |> Zoi.optional()
                                        })
  @type user_prompt_closed_parameters ::
          unquote(Zoi.type_spec(@user_prompt_closed_parameters_schema))

  @user_prompt_opened_parameters_schema Zoi.map(%{
                                          context: Zoi.any(),
                                          handler: Zoi.any(),
                                          message: Zoi.string(),
                                          type: Zoi.any(),
                                          user_context: Zoi.any() |> Zoi.optional(),
                                          default_value: Zoi.string() |> Zoi.optional()
                                        })
  @type user_prompt_opened_parameters ::
          unquote(Zoi.type_spec(@user_prompt_opened_parameters_schema))

  @doc "Returns the Zoi schema for `browsing_context`."
  def browsing_context, do: @browsing_context_schema

  @doc "Returns the Zoi schema for `locator`."
  def locator, do: @locator_schema

  @doc "Returns the Zoi schema for `accessibility_locator`."
  def accessibility_locator, do: @accessibility_locator_schema

  @doc "Returns the Zoi schema for `css_locator`."
  def css_locator, do: @css_locator_schema

  @doc "Returns the Zoi schema for `context_locator`."
  def context_locator, do: @context_locator_schema

  @doc "Returns the Zoi schema for `inner_text_locator`."
  def inner_text_locator, do: @inner_text_locator_schema

  @doc "Returns the Zoi schema for `x_path_locator`."
  def x_path_locator, do: @x_path_locator_schema

  @doc "Returns the Zoi schema for `navigation`."
  def navigation, do: @navigation_schema

  @doc "Returns the Zoi schema for `readiness_state`."
  def readiness_state, do: @readiness_state_schema

  @doc "Returns the Zoi schema for `user_prompt_type`."
  def user_prompt_type, do: @user_prompt_type_schema

  @doc "Returns the Zoi schema for `activate_parameters`."
  def activate_parameters, do: @activate_parameters_schema

  @doc "Returns the Zoi schema for `capture_screenshot_parameters`."
  def capture_screenshot_parameters, do: @capture_screenshot_parameters_schema

  @doc "Returns the Zoi schema for `image_format`."
  def image_format, do: @image_format_schema

  @doc "Returns the Zoi schema for `clip_rectangle`."
  def clip_rectangle, do: @clip_rectangle_schema

  @doc "Returns the Zoi schema for `element_clip_rectangle`."
  def element_clip_rectangle, do: @element_clip_rectangle_schema

  @doc "Returns the Zoi schema for `box_clip_rectangle`."
  def box_clip_rectangle, do: @box_clip_rectangle_schema

  @doc "Returns the Zoi schema for `close_parameters`."
  def close_parameters, do: @close_parameters_schema

  @doc "Returns the Zoi schema for `create_type`."
  def create_type, do: @create_type_schema

  @doc "Returns the Zoi schema for `create_parameters`."
  def create_parameters, do: @create_parameters_schema

  @doc "Returns the Zoi schema for `get_tree_parameters`."
  def get_tree_parameters, do: @get_tree_parameters_schema

  @doc "Returns the Zoi schema for `handle_user_prompt_parameters`."
  def handle_user_prompt_parameters, do: @handle_user_prompt_parameters_schema

  @doc "Returns the Zoi schema for `locate_nodes_parameters`."
  def locate_nodes_parameters, do: @locate_nodes_parameters_schema

  @doc "Returns the Zoi schema for `navigate_parameters`."
  def navigate_parameters, do: @navigate_parameters_schema

  @doc "Returns the Zoi schema for `print_parameters`."
  def print_parameters, do: @print_parameters_schema

  @doc "Returns the Zoi schema for `print_margin_parameters`."
  def print_margin_parameters, do: @print_margin_parameters_schema

  @doc "Returns the Zoi schema for `print_page_parameters`."
  def print_page_parameters, do: @print_page_parameters_schema

  @doc "Returns the Zoi schema for `reload_parameters`."
  def reload_parameters, do: @reload_parameters_schema

  @doc "Returns the Zoi schema for `set_viewport_parameters`."
  def set_viewport_parameters, do: @set_viewport_parameters_schema

  @doc "Returns the Zoi schema for `viewport`."
  def viewport, do: @viewport_schema

  @doc "Returns the Zoi schema for `traverse_history_parameters`."
  def traverse_history_parameters, do: @traverse_history_parameters_schema

  @doc "Returns the Zoi schema for `info_list`."
  def info_list, do: @info_list_schema

  @doc "Returns the Zoi schema for `info`."
  def info, do: @info_schema

  @doc "Returns the Zoi schema for `base_navigation_info`."
  def base_navigation_info, do: @base_navigation_info_schema

  @doc "Returns the Zoi schema for `navigation_info`."
  def navigation_info, do: @navigation_info_schema

  @doc "Returns the Zoi schema for `activate_result`."
  def activate_result, do: @activate_result_schema

  @doc "Returns the Zoi schema for `capture_screenshot_result`."
  def capture_screenshot_result, do: @capture_screenshot_result_schema

  @doc "Returns the Zoi schema for `close_result`."
  def close_result, do: @close_result_schema

  @doc "Returns the Zoi schema for `create_result`."
  def create_result, do: @create_result_schema

  @doc "Returns the Zoi schema for `get_tree_result`."
  def get_tree_result, do: @get_tree_result_schema

  @doc "Returns the Zoi schema for `handle_user_prompt_result`."
  def handle_user_prompt_result, do: @handle_user_prompt_result_schema

  @doc "Returns the Zoi schema for `locate_nodes_result`."
  def locate_nodes_result, do: @locate_nodes_result_schema

  @doc "Returns the Zoi schema for `navigate_result`."
  def navigate_result, do: @navigate_result_schema

  @doc "Returns the Zoi schema for `print_result`."
  def print_result, do: @print_result_schema

  @doc "Returns the Zoi schema for `reload_result`."
  def reload_result, do: @reload_result_schema

  @doc "Returns the Zoi schema for `set_viewport_result`."
  def set_viewport_result, do: @set_viewport_result_schema

  @doc "Returns the Zoi schema for `traverse_history_result`."
  def traverse_history_result, do: @traverse_history_result_schema

  @doc "Returns the Zoi schema for `history_updated_parameters`."
  def history_updated_parameters, do: @history_updated_parameters_schema

  @doc "Returns the Zoi schema for `download_will_begin_params`."
  def download_will_begin_params, do: @download_will_begin_params_schema

  @doc "Returns the Zoi schema for `download_end_params`."
  def download_end_params, do: @download_end_params_schema

  @doc "Returns the Zoi schema for `download_canceled_params`."
  def download_canceled_params, do: @download_canceled_params_schema

  @doc "Returns the Zoi schema for `download_complete_params`."
  def download_complete_params, do: @download_complete_params_schema

  @doc "Returns the Zoi schema for `user_prompt_closed_parameters`."
  def user_prompt_closed_parameters, do: @user_prompt_closed_parameters_schema

  @doc "Returns the Zoi schema for `user_prompt_opened_parameters`."
  def user_prompt_opened_parameters, do: @user_prompt_opened_parameters_schema
end
