# Generated by mix bibbidi.gen — do not edit manually
defmodule Bibbidi.Types.Emulation do
  @moduledoc """
  Type definitions and Zoi schemas for the `emulation` module of the WebDriver BiDi protocol.

  Each type has:
  - A `@type` spec derived from the Zoi schema (for Dialyzer)
  - A function returning the Zoi schema (for runtime validation)
  """

  @set_forced_colors_mode_theme_override_parameters_schema Zoi.map(%{
                                                             theme:
                                                               Zoi.union([Zoi.any(), Zoi.null()]),
                                                             contexts:
                                                               Zoi.list(Zoi.any())
                                                               |> Zoi.optional(),
                                                             user_contexts:
                                                               Zoi.list(Zoi.any())
                                                               |> Zoi.optional()
                                                           })
  @type set_forced_colors_mode_theme_override_parameters ::
          unquote(Zoi.type_spec(@set_forced_colors_mode_theme_override_parameters_schema))

  @forced_colors_mode_theme_schema Zoi.union([Zoi.string(), Zoi.string()])
  @type forced_colors_mode_theme :: unquote(Zoi.type_spec(@forced_colors_mode_theme_schema))

  @set_geolocation_override_parameters_schema Zoi.map(%{
                                                contexts: Zoi.list(Zoi.any()) |> Zoi.optional(),
                                                user_contexts:
                                                  Zoi.list(Zoi.any()) |> Zoi.optional()
                                              })
  @type set_geolocation_override_parameters ::
          unquote(Zoi.type_spec(@set_geolocation_override_parameters_schema))

  @geolocation_coordinates_schema Zoi.map(%{
                                    latitude: Zoi.integer() |> Zoi.min(-90.0) |> Zoi.max(90.0),
                                    longitude: Zoi.integer() |> Zoi.min(-180.0) |> Zoi.max(180.0),
                                    accuracy: Zoi.any() |> Zoi.optional(),
                                    altitude:
                                      Zoi.union([Zoi.float(), Zoi.any()]) |> Zoi.optional(),
                                    altitude_accuracy:
                                      Zoi.union([Zoi.float(), Zoi.any()]) |> Zoi.optional(),
                                    heading:
                                      Zoi.union([Zoi.integer(), Zoi.any()]) |> Zoi.optional(),
                                    speed: Zoi.union([Zoi.float(), Zoi.any()]) |> Zoi.optional()
                                  })
  @type geolocation_coordinates :: unquote(Zoi.type_spec(@geolocation_coordinates_schema))

  @geolocation_position_error_schema Zoi.map(%{type: Zoi.string()})
  @type geolocation_position_error :: unquote(Zoi.type_spec(@geolocation_position_error_schema))

  @set_locale_override_parameters_schema Zoi.map(%{
                                           locale: Zoi.union([Zoi.string(), Zoi.null()]),
                                           contexts: Zoi.list(Zoi.any()) |> Zoi.optional(),
                                           user_contexts: Zoi.list(Zoi.any()) |> Zoi.optional()
                                         })
  @type set_locale_override_parameters ::
          unquote(Zoi.type_spec(@set_locale_override_parameters_schema))

  @set_network_conditions_parameters_schema Zoi.map(%{
                                              network_conditions:
                                                Zoi.union([Zoi.any(), Zoi.null()]),
                                              contexts: Zoi.list(Zoi.any()) |> Zoi.optional(),
                                              user_contexts: Zoi.list(Zoi.any()) |> Zoi.optional()
                                            })
  @type set_network_conditions_parameters ::
          unquote(Zoi.type_spec(@set_network_conditions_parameters_schema))

  @network_conditions_schema Zoi.any()
  @type network_conditions :: unquote(Zoi.type_spec(@network_conditions_schema))

  @network_conditions_offline_schema Zoi.map(%{type: Zoi.string()})
  @type network_conditions_offline :: unquote(Zoi.type_spec(@network_conditions_offline_schema))

  @screen_area_schema Zoi.map(%{width: Zoi.any(), height: Zoi.any()})
  @type screen_area :: unquote(Zoi.type_spec(@screen_area_schema))

  @set_screen_settings_override_parameters_schema Zoi.map(%{
                                                    screen_area:
                                                      Zoi.union([Zoi.any(), Zoi.null()]),
                                                    contexts:
                                                      Zoi.list(Zoi.any()) |> Zoi.optional(),
                                                    user_contexts:
                                                      Zoi.list(Zoi.any()) |> Zoi.optional()
                                                  })
  @type set_screen_settings_override_parameters ::
          unquote(Zoi.type_spec(@set_screen_settings_override_parameters_schema))

  @screen_orientation_natural_schema Zoi.union([Zoi.string(), Zoi.string()])
  @type screen_orientation_natural :: unquote(Zoi.type_spec(@screen_orientation_natural_schema))

  @screen_orientation_type_schema Zoi.union([
                                    Zoi.string(),
                                    Zoi.string(),
                                    Zoi.string(),
                                    Zoi.string()
                                  ])
  @type screen_orientation_type :: unquote(Zoi.type_spec(@screen_orientation_type_schema))

  @screen_orientation_schema Zoi.map(%{natural: Zoi.any(), type: Zoi.any()})
  @type screen_orientation :: unquote(Zoi.type_spec(@screen_orientation_schema))

  @set_screen_orientation_override_parameters_schema Zoi.map(%{
                                                       screen_orientation:
                                                         Zoi.union([Zoi.any(), Zoi.null()]),
                                                       contexts:
                                                         Zoi.list(Zoi.any()) |> Zoi.optional(),
                                                       user_contexts:
                                                         Zoi.list(Zoi.any()) |> Zoi.optional()
                                                     })
  @type set_screen_orientation_override_parameters ::
          unquote(Zoi.type_spec(@set_screen_orientation_override_parameters_schema))

  @set_user_agent_override_parameters_schema Zoi.map(%{
                                               user_agent: Zoi.union([Zoi.string(), Zoi.null()]),
                                               contexts: Zoi.list(Zoi.any()) |> Zoi.optional(),
                                               user_contexts:
                                                 Zoi.list(Zoi.any()) |> Zoi.optional()
                                             })
  @type set_user_agent_override_parameters ::
          unquote(Zoi.type_spec(@set_user_agent_override_parameters_schema))

  @set_scripting_enabled_parameters_schema Zoi.map(%{
                                             enabled: Zoi.union([Zoi.any(), Zoi.null()]),
                                             contexts: Zoi.list(Zoi.any()) |> Zoi.optional(),
                                             user_contexts: Zoi.list(Zoi.any()) |> Zoi.optional()
                                           })
  @type set_scripting_enabled_parameters ::
          unquote(Zoi.type_spec(@set_scripting_enabled_parameters_schema))

  @set_scrollbar_type_override_parameters_schema Zoi.map(%{
                                                   scrollbar_type:
                                                     Zoi.union([
                                                       Zoi.string(),
                                                       Zoi.string(),
                                                       Zoi.null()
                                                     ]),
                                                   contexts:
                                                     Zoi.list(Zoi.any()) |> Zoi.optional(),
                                                   user_contexts:
                                                     Zoi.list(Zoi.any()) |> Zoi.optional()
                                                 })
  @type set_scrollbar_type_override_parameters ::
          unquote(Zoi.type_spec(@set_scrollbar_type_override_parameters_schema))

  @set_timezone_override_parameters_schema Zoi.map(%{
                                             timezone: Zoi.union([Zoi.string(), Zoi.null()]),
                                             contexts: Zoi.list(Zoi.any()) |> Zoi.optional(),
                                             user_contexts: Zoi.list(Zoi.any()) |> Zoi.optional()
                                           })
  @type set_timezone_override_parameters ::
          unquote(Zoi.type_spec(@set_timezone_override_parameters_schema))

  @set_touch_override_parameters_schema Zoi.map(%{
                                          max_touch_points: Zoi.union([Zoi.any(), Zoi.null()]),
                                          contexts: Zoi.list(Zoi.any()) |> Zoi.optional(),
                                          user_contexts: Zoi.list(Zoi.any()) |> Zoi.optional()
                                        })
  @type set_touch_override_parameters ::
          unquote(Zoi.type_spec(@set_touch_override_parameters_schema))

  @set_forced_colors_mode_theme_override_result_schema Zoi.any()
  @type set_forced_colors_mode_theme_override_result ::
          unquote(Zoi.type_spec(@set_forced_colors_mode_theme_override_result_schema))

  @set_geolocation_override_result_schema Zoi.any()
  @type set_geolocation_override_result ::
          unquote(Zoi.type_spec(@set_geolocation_override_result_schema))

  @set_locale_override_result_schema Zoi.any()
  @type set_locale_override_result :: unquote(Zoi.type_spec(@set_locale_override_result_schema))

  @set_network_conditions_result_schema Zoi.any()
  @type set_network_conditions_result ::
          unquote(Zoi.type_spec(@set_network_conditions_result_schema))

  @set_screen_settings_override_result_schema Zoi.any()
  @type set_screen_settings_override_result ::
          unquote(Zoi.type_spec(@set_screen_settings_override_result_schema))

  @set_screen_orientation_override_result_schema Zoi.any()
  @type set_screen_orientation_override_result ::
          unquote(Zoi.type_spec(@set_screen_orientation_override_result_schema))

  @set_user_agent_override_result_schema Zoi.any()
  @type set_user_agent_override_result ::
          unquote(Zoi.type_spec(@set_user_agent_override_result_schema))

  @set_scripting_enabled_result_schema Zoi.any()
  @type set_scripting_enabled_result ::
          unquote(Zoi.type_spec(@set_scripting_enabled_result_schema))

  @set_scrollbar_type_override_result_schema Zoi.any()
  @type set_scrollbar_type_override_result ::
          unquote(Zoi.type_spec(@set_scrollbar_type_override_result_schema))

  @set_timezone_override_result_schema Zoi.any()
  @type set_timezone_override_result ::
          unquote(Zoi.type_spec(@set_timezone_override_result_schema))

  @set_touch_override_result_schema Zoi.any()
  @type set_touch_override_result :: unquote(Zoi.type_spec(@set_touch_override_result_schema))

  @doc "Returns the Zoi schema for `set_forced_colors_mode_theme_override_parameters`."
  def set_forced_colors_mode_theme_override_parameters,
    do: @set_forced_colors_mode_theme_override_parameters_schema

  @doc "Returns the Zoi schema for `forced_colors_mode_theme`."
  def forced_colors_mode_theme, do: @forced_colors_mode_theme_schema

  @doc "Returns the Zoi schema for `set_geolocation_override_parameters`."
  def set_geolocation_override_parameters, do: @set_geolocation_override_parameters_schema

  @doc "Returns the Zoi schema for `geolocation_coordinates`."
  def geolocation_coordinates, do: @geolocation_coordinates_schema

  @doc "Returns the Zoi schema for `geolocation_position_error`."
  def geolocation_position_error, do: @geolocation_position_error_schema

  @doc "Returns the Zoi schema for `set_locale_override_parameters`."
  def set_locale_override_parameters, do: @set_locale_override_parameters_schema

  @doc "Returns the Zoi schema for `set_network_conditions_parameters`."
  def set_network_conditions_parameters, do: @set_network_conditions_parameters_schema

  @doc "Returns the Zoi schema for `network_conditions`."
  def network_conditions, do: @network_conditions_schema

  @doc "Returns the Zoi schema for `network_conditions_offline`."
  def network_conditions_offline, do: @network_conditions_offline_schema

  @doc "Returns the Zoi schema for `screen_area`."
  def screen_area, do: @screen_area_schema

  @doc "Returns the Zoi schema for `set_screen_settings_override_parameters`."
  def set_screen_settings_override_parameters, do: @set_screen_settings_override_parameters_schema

  @doc "Returns the Zoi schema for `screen_orientation_natural`."
  def screen_orientation_natural, do: @screen_orientation_natural_schema

  @doc "Returns the Zoi schema for `screen_orientation_type`."
  def screen_orientation_type, do: @screen_orientation_type_schema

  @doc "Returns the Zoi schema for `screen_orientation`."
  def screen_orientation, do: @screen_orientation_schema

  @doc "Returns the Zoi schema for `set_screen_orientation_override_parameters`."
  def set_screen_orientation_override_parameters,
    do: @set_screen_orientation_override_parameters_schema

  @doc "Returns the Zoi schema for `set_user_agent_override_parameters`."
  def set_user_agent_override_parameters, do: @set_user_agent_override_parameters_schema

  @doc "Returns the Zoi schema for `set_scripting_enabled_parameters`."
  def set_scripting_enabled_parameters, do: @set_scripting_enabled_parameters_schema

  @doc "Returns the Zoi schema for `set_scrollbar_type_override_parameters`."
  def set_scrollbar_type_override_parameters, do: @set_scrollbar_type_override_parameters_schema

  @doc "Returns the Zoi schema for `set_timezone_override_parameters`."
  def set_timezone_override_parameters, do: @set_timezone_override_parameters_schema

  @doc "Returns the Zoi schema for `set_touch_override_parameters`."
  def set_touch_override_parameters, do: @set_touch_override_parameters_schema

  @doc "Returns the Zoi schema for `set_forced_colors_mode_theme_override_result`."
  def set_forced_colors_mode_theme_override_result,
    do: @set_forced_colors_mode_theme_override_result_schema

  @doc "Returns the Zoi schema for `set_geolocation_override_result`."
  def set_geolocation_override_result, do: @set_geolocation_override_result_schema

  @doc "Returns the Zoi schema for `set_locale_override_result`."
  def set_locale_override_result, do: @set_locale_override_result_schema

  @doc "Returns the Zoi schema for `set_network_conditions_result`."
  def set_network_conditions_result, do: @set_network_conditions_result_schema

  @doc "Returns the Zoi schema for `set_screen_settings_override_result`."
  def set_screen_settings_override_result, do: @set_screen_settings_override_result_schema

  @doc "Returns the Zoi schema for `set_screen_orientation_override_result`."
  def set_screen_orientation_override_result, do: @set_screen_orientation_override_result_schema

  @doc "Returns the Zoi schema for `set_user_agent_override_result`."
  def set_user_agent_override_result, do: @set_user_agent_override_result_schema

  @doc "Returns the Zoi schema for `set_scripting_enabled_result`."
  def set_scripting_enabled_result, do: @set_scripting_enabled_result_schema

  @doc "Returns the Zoi schema for `set_scrollbar_type_override_result`."
  def set_scrollbar_type_override_result, do: @set_scrollbar_type_override_result_schema

  @doc "Returns the Zoi schema for `set_timezone_override_result`."
  def set_timezone_override_result, do: @set_timezone_override_result_schema

  @doc "Returns the Zoi schema for `set_touch_override_result`."
  def set_touch_override_result, do: @set_touch_override_result_schema
end
