# Generated by mix bibbidi.gen — do not edit manually
defmodule Bibbidi.Types.Input do
  @moduledoc """
  Type definitions and Zoi schemas for the `input` module of the WebDriver BiDi protocol.

  Each type has:
  - A `@type` spec derived from the Zoi schema (for Dialyzer)
  - A function returning the Zoi schema (for runtime validation)
  """

  @element_origin_schema Zoi.map(%{type: Zoi.string(), element: Zoi.any()})
  @type element_origin :: unquote(Zoi.type_spec(@element_origin_schema))

  @perform_actions_parameters_schema Zoi.map(%{context: Zoi.any(), actions: Zoi.list(Zoi.any())})
  @type perform_actions_parameters :: unquote(Zoi.type_spec(@perform_actions_parameters_schema))

  @source_actions_schema Zoi.union([Zoi.any(), Zoi.any(), Zoi.any(), Zoi.any()])
  @type source_actions :: unquote(Zoi.type_spec(@source_actions_schema))

  @none_source_actions_schema Zoi.map(%{
                                type: Zoi.string(),
                                id: Zoi.string(),
                                actions: Zoi.list(Zoi.any())
                              })
  @type none_source_actions :: unquote(Zoi.type_spec(@none_source_actions_schema))

  @none_source_action_schema Zoi.any()
  @type none_source_action :: unquote(Zoi.type_spec(@none_source_action_schema))

  @key_source_actions_schema Zoi.map(%{
                               type: Zoi.string(),
                               id: Zoi.string(),
                               actions: Zoi.list(Zoi.any())
                             })
  @type key_source_actions :: unquote(Zoi.type_spec(@key_source_actions_schema))

  @key_source_action_schema Zoi.union([Zoi.any(), Zoi.any(), Zoi.any()])
  @type key_source_action :: unquote(Zoi.type_spec(@key_source_action_schema))

  @pointer_source_actions_schema Zoi.map(%{
                                   type: Zoi.string(),
                                   id: Zoi.string(),
                                   parameters: Zoi.any() |> Zoi.optional(),
                                   actions: Zoi.list(Zoi.any())
                                 })
  @type pointer_source_actions :: unquote(Zoi.type_spec(@pointer_source_actions_schema))

  @pointer_type_schema Zoi.union([Zoi.string(), Zoi.string(), Zoi.string()])
  @type pointer_type :: unquote(Zoi.type_spec(@pointer_type_schema))

  @pointer_parameters_schema Zoi.map(%{pointer_type: Zoi.any() |> Zoi.optional()})
  @type pointer_parameters :: unquote(Zoi.type_spec(@pointer_parameters_schema))

  @pointer_source_action_schema Zoi.union([Zoi.any(), Zoi.any(), Zoi.any(), Zoi.any()])
  @type pointer_source_action :: unquote(Zoi.type_spec(@pointer_source_action_schema))

  @wheel_source_actions_schema Zoi.map(%{
                                 type: Zoi.string(),
                                 id: Zoi.string(),
                                 actions: Zoi.list(Zoi.any())
                               })
  @type wheel_source_actions :: unquote(Zoi.type_spec(@wheel_source_actions_schema))

  @wheel_source_action_schema Zoi.union([Zoi.any(), Zoi.any()])
  @type wheel_source_action :: unquote(Zoi.type_spec(@wheel_source_action_schema))

  @pause_action_schema Zoi.map(%{type: Zoi.string(), duration: Zoi.any() |> Zoi.optional()})
  @type pause_action :: unquote(Zoi.type_spec(@pause_action_schema))

  @key_down_action_schema Zoi.map(%{type: Zoi.string(), value: Zoi.string()})
  @type key_down_action :: unquote(Zoi.type_spec(@key_down_action_schema))

  @key_up_action_schema Zoi.map(%{type: Zoi.string(), value: Zoi.string()})
  @type key_up_action :: unquote(Zoi.type_spec(@key_up_action_schema))

  @pointer_up_action_schema Zoi.map(%{type: Zoi.string(), button: Zoi.any()})
  @type pointer_up_action :: unquote(Zoi.type_spec(@pointer_up_action_schema))

  @pointer_down_action_schema Zoi.map(%{type: Zoi.string(), button: Zoi.any()})
  @type pointer_down_action :: unquote(Zoi.type_spec(@pointer_down_action_schema))

  @pointer_move_action_schema Zoi.map(%{
                                type: Zoi.string(),
                                x: Zoi.float(),
                                y: Zoi.float(),
                                duration: Zoi.any() |> Zoi.optional(),
                                origin: Zoi.any() |> Zoi.optional()
                              })
  @type pointer_move_action :: unquote(Zoi.type_spec(@pointer_move_action_schema))

  @wheel_scroll_action_schema Zoi.map(%{
                                type: Zoi.string(),
                                x: Zoi.any(),
                                y: Zoi.any(),
                                delta_x: Zoi.any(),
                                delta_y: Zoi.any(),
                                duration: Zoi.any() |> Zoi.optional(),
                                origin: Zoi.any() |> Zoi.optional()
                              })
  @type wheel_scroll_action :: unquote(Zoi.type_spec(@wheel_scroll_action_schema))

  @pointer_common_properties_schema Zoi.map(Zoi.string(), Zoi.any())
  @type pointer_common_properties :: unquote(Zoi.type_spec(@pointer_common_properties_schema))

  @origin_schema Zoi.union([Zoi.string(), Zoi.string(), Zoi.any()])
  @type origin :: unquote(Zoi.type_spec(@origin_schema))

  @release_actions_parameters_schema Zoi.map(%{context: Zoi.any()})
  @type release_actions_parameters :: unquote(Zoi.type_spec(@release_actions_parameters_schema))

  @set_files_parameters_schema Zoi.map(%{
                                 context: Zoi.any(),
                                 element: Zoi.any(),
                                 files: Zoi.list(Zoi.string())
                               })
  @type set_files_parameters :: unquote(Zoi.type_spec(@set_files_parameters_schema))

  @file_dialog_info_schema Zoi.map(%{
                             context: Zoi.any(),
                             user_context: Zoi.any() |> Zoi.optional(),
                             element: Zoi.any() |> Zoi.optional(),
                             multiple: Zoi.boolean()
                           })
  @type file_dialog_info :: unquote(Zoi.type_spec(@file_dialog_info_schema))

  @perform_actions_result_schema Zoi.any()
  @type perform_actions_result :: unquote(Zoi.type_spec(@perform_actions_result_schema))

  @release_actions_result_schema Zoi.any()
  @type release_actions_result :: unquote(Zoi.type_spec(@release_actions_result_schema))

  @set_files_result_schema Zoi.any()
  @type set_files_result :: unquote(Zoi.type_spec(@set_files_result_schema))

  @doc "Returns the Zoi schema for `element_origin`."
  def element_origin, do: @element_origin_schema

  @doc "Returns the Zoi schema for `perform_actions_parameters`."
  def perform_actions_parameters, do: @perform_actions_parameters_schema

  @doc "Returns the Zoi schema for `source_actions`."
  def source_actions, do: @source_actions_schema

  @doc "Returns the Zoi schema for `none_source_actions`."
  def none_source_actions, do: @none_source_actions_schema

  @doc "Returns the Zoi schema for `none_source_action`."
  def none_source_action, do: @none_source_action_schema

  @doc "Returns the Zoi schema for `key_source_actions`."
  def key_source_actions, do: @key_source_actions_schema

  @doc "Returns the Zoi schema for `key_source_action`."
  def key_source_action, do: @key_source_action_schema

  @doc "Returns the Zoi schema for `pointer_source_actions`."
  def pointer_source_actions, do: @pointer_source_actions_schema

  @doc "Returns the Zoi schema for `pointer_type`."
  def pointer_type, do: @pointer_type_schema

  @doc "Returns the Zoi schema for `pointer_parameters`."
  def pointer_parameters, do: @pointer_parameters_schema

  @doc "Returns the Zoi schema for `pointer_source_action`."
  def pointer_source_action, do: @pointer_source_action_schema

  @doc "Returns the Zoi schema for `wheel_source_actions`."
  def wheel_source_actions, do: @wheel_source_actions_schema

  @doc "Returns the Zoi schema for `wheel_source_action`."
  def wheel_source_action, do: @wheel_source_action_schema

  @doc "Returns the Zoi schema for `pause_action`."
  def pause_action, do: @pause_action_schema

  @doc "Returns the Zoi schema for `key_down_action`."
  def key_down_action, do: @key_down_action_schema

  @doc "Returns the Zoi schema for `key_up_action`."
  def key_up_action, do: @key_up_action_schema

  @doc "Returns the Zoi schema for `pointer_up_action`."
  def pointer_up_action, do: @pointer_up_action_schema

  @doc "Returns the Zoi schema for `pointer_down_action`."
  def pointer_down_action, do: @pointer_down_action_schema

  @doc "Returns the Zoi schema for `pointer_move_action`."
  def pointer_move_action, do: @pointer_move_action_schema

  @doc "Returns the Zoi schema for `wheel_scroll_action`."
  def wheel_scroll_action, do: @wheel_scroll_action_schema

  @doc "Returns the Zoi schema for `pointer_common_properties`."
  def pointer_common_properties, do: @pointer_common_properties_schema

  @doc "Returns the Zoi schema for `origin`."
  def origin, do: @origin_schema

  @doc "Returns the Zoi schema for `release_actions_parameters`."
  def release_actions_parameters, do: @release_actions_parameters_schema

  @doc "Returns the Zoi schema for `set_files_parameters`."
  def set_files_parameters, do: @set_files_parameters_schema

  @doc "Returns the Zoi schema for `file_dialog_info`."
  def file_dialog_info, do: @file_dialog_info_schema

  @doc "Returns the Zoi schema for `perform_actions_result`."
  def perform_actions_result, do: @perform_actions_result_schema

  @doc "Returns the Zoi schema for `release_actions_result`."
  def release_actions_result, do: @release_actions_result_schema

  @doc "Returns the Zoi schema for `set_files_result`."
  def set_files_result, do: @set_files_result_schema
end
