# Generated by mix bibbidi.gen — do not edit manually
defmodule Bibbidi.Types.Log do
  @moduledoc """
  Type definitions and Zoi schemas for the `log` module of the WebDriver BiDi protocol.

  Each type has:
  - A `@type` spec derived from the Zoi schema (for Dialyzer)
  - A function returning the Zoi schema (for runtime validation)
  """

  @level_schema Zoi.union([Zoi.string(), Zoi.string(), Zoi.string(), Zoi.string()])
  @type level :: unquote(Zoi.type_spec(@level_schema))

  @entry_schema Zoi.union([Zoi.any(), Zoi.any(), Zoi.any()])
  @type entry :: unquote(Zoi.type_spec(@entry_schema))

  @base_log_entry_schema Zoi.map(Zoi.string(), Zoi.any())
  @type base_log_entry :: unquote(Zoi.type_spec(@base_log_entry_schema))

  @generic_log_entry_schema Zoi.map(%{type: Zoi.string()})
  @type generic_log_entry :: unquote(Zoi.type_spec(@generic_log_entry_schema))

  @console_log_entry_schema Zoi.map(%{
                              type: Zoi.string(),
                              method: Zoi.string(),
                              args: Zoi.list(Zoi.any())
                            })
  @type console_log_entry :: unquote(Zoi.type_spec(@console_log_entry_schema))

  @javascript_log_entry_schema Zoi.map(%{type: Zoi.string()})
  @type javascript_log_entry :: unquote(Zoi.type_spec(@javascript_log_entry_schema))

  @doc "Returns the Zoi schema for `level`."
  def level, do: @level_schema

  @doc "Returns the Zoi schema for `entry`."
  def entry, do: @entry_schema

  @doc "Returns the Zoi schema for `base_log_entry`."
  def base_log_entry, do: @base_log_entry_schema

  @doc "Returns the Zoi schema for `generic_log_entry`."
  def generic_log_entry, do: @generic_log_entry_schema

  @doc "Returns the Zoi schema for `console_log_entry`."
  def console_log_entry, do: @console_log_entry_schema

  @doc "Returns the Zoi schema for `javascript_log_entry`."
  def javascript_log_entry, do: @javascript_log_entry_schema
end
