# Generated by mix bibbidi.gen — do not edit manually
defmodule Bibbidi.Types.Network do
  @moduledoc """
  Type definitions and Zoi schemas for the `network` module of the WebDriver BiDi protocol.

  Each type has:
  - A `@type` spec derived from the Zoi schema (for Dialyzer)
  - A function returning the Zoi schema (for runtime validation)
  """

  @auth_credentials_schema Zoi.map(%{
                             type: Zoi.string(),
                             username: Zoi.string(),
                             password: Zoi.string()
                           })
  @type auth_credentials :: unquote(Zoi.type_spec(@auth_credentials_schema))

  @bytes_value_schema Zoi.union([Zoi.any(), Zoi.any()])
  @type bytes_value :: unquote(Zoi.type_spec(@bytes_value_schema))

  @string_value_schema Zoi.map(%{type: Zoi.string(), value: Zoi.string()})
  @type string_value :: unquote(Zoi.type_spec(@string_value_schema))

  @base64value_schema Zoi.map(%{type: Zoi.string(), value: Zoi.string()})
  @type base64value :: unquote(Zoi.type_spec(@base64value_schema))

  @collector_schema Zoi.string()
  @type collector :: unquote(Zoi.type_spec(@collector_schema))

  @collector_type_schema Zoi.string()
  @type collector_type :: unquote(Zoi.type_spec(@collector_type_schema))

  @same_site_schema Zoi.union([Zoi.string(), Zoi.string(), Zoi.string(), Zoi.string()])
  @type same_site :: unquote(Zoi.type_spec(@same_site_schema))

  @cookie_schema Zoi.map(%{
                   name: Zoi.string(),
                   value: Zoi.any(),
                   domain: Zoi.string(),
                   path: Zoi.string(),
                   size: Zoi.any(),
                   http_only: Zoi.boolean(),
                   secure: Zoi.boolean(),
                   same_site: Zoi.any(),
                   expiry: Zoi.any() |> Zoi.optional()
                 })
  @type cookie :: unquote(Zoi.type_spec(@cookie_schema))

  @cookie_header_schema Zoi.map(%{name: Zoi.string(), value: Zoi.any()})
  @type cookie_header :: unquote(Zoi.type_spec(@cookie_header_schema))

  @data_type_schema Zoi.union([Zoi.string(), Zoi.string()])
  @type data_type :: unquote(Zoi.type_spec(@data_type_schema))

  @header_schema Zoi.map(%{name: Zoi.string(), value: Zoi.any()})
  @type header :: unquote(Zoi.type_spec(@header_schema))

  @intercept_schema Zoi.string()
  @type intercept :: unquote(Zoi.type_spec(@intercept_schema))

  @request_schema Zoi.string()
  @type request :: unquote(Zoi.type_spec(@request_schema))

  @set_cookie_header_schema Zoi.map(%{
                              name: Zoi.string(),
                              value: Zoi.any(),
                              domain: Zoi.string() |> Zoi.optional(),
                              http_only: Zoi.boolean() |> Zoi.optional(),
                              expiry: Zoi.string() |> Zoi.optional(),
                              max_age: Zoi.any() |> Zoi.optional(),
                              path: Zoi.string() |> Zoi.optional(),
                              same_site: Zoi.any() |> Zoi.optional(),
                              secure: Zoi.boolean() |> Zoi.optional()
                            })
  @type set_cookie_header :: unquote(Zoi.type_spec(@set_cookie_header_schema))

  @url_pattern_schema Zoi.union([Zoi.any(), Zoi.any()])
  @type url_pattern :: unquote(Zoi.type_spec(@url_pattern_schema))

  @url_pattern_pattern_schema Zoi.map(%{
                                type: Zoi.string(),
                                protocol: Zoi.string() |> Zoi.optional(),
                                hostname: Zoi.string() |> Zoi.optional(),
                                port: Zoi.string() |> Zoi.optional(),
                                pathname: Zoi.string() |> Zoi.optional(),
                                search: Zoi.string() |> Zoi.optional()
                              })
  @type url_pattern_pattern :: unquote(Zoi.type_spec(@url_pattern_pattern_schema))

  @url_pattern_string_schema Zoi.map(%{type: Zoi.string(), pattern: Zoi.string()})
  @type url_pattern_string :: unquote(Zoi.type_spec(@url_pattern_string_schema))

  @add_data_collector_parameters_schema Zoi.map(%{
                                          data_types: Zoi.list(Zoi.any()),
                                          max_encoded_data_size: Zoi.any(),
                                          collector_type: Zoi.any() |> Zoi.optional(),
                                          contexts: Zoi.list(Zoi.any()) |> Zoi.optional(),
                                          user_contexts: Zoi.list(Zoi.any()) |> Zoi.optional()
                                        })
  @type add_data_collector_parameters ::
          unquote(Zoi.type_spec(@add_data_collector_parameters_schema))

  @add_intercept_parameters_schema Zoi.map(%{
                                     phases: Zoi.list(Zoi.any()),
                                     contexts: Zoi.list(Zoi.any()) |> Zoi.optional(),
                                     url_patterns: Zoi.list(Zoi.any()) |> Zoi.optional()
                                   })
  @type add_intercept_parameters :: unquote(Zoi.type_spec(@add_intercept_parameters_schema))

  @intercept_phase_schema Zoi.union([Zoi.string(), Zoi.string(), Zoi.string()])
  @type intercept_phase :: unquote(Zoi.type_spec(@intercept_phase_schema))

  @continue_request_parameters_schema Zoi.map(%{
                                        request: Zoi.any(),
                                        body: Zoi.any() |> Zoi.optional(),
                                        cookies: Zoi.list(Zoi.any()) |> Zoi.optional(),
                                        headers: Zoi.list(Zoi.any()) |> Zoi.optional(),
                                        method: Zoi.string() |> Zoi.optional(),
                                        url: Zoi.string() |> Zoi.optional()
                                      })
  @type continue_request_parameters :: unquote(Zoi.type_spec(@continue_request_parameters_schema))

  @continue_response_parameters_schema Zoi.map(%{
                                         request: Zoi.any(),
                                         cookies: Zoi.list(Zoi.any()) |> Zoi.optional(),
                                         credentials: Zoi.any() |> Zoi.optional(),
                                         headers: Zoi.list(Zoi.any()) |> Zoi.optional(),
                                         reason_phrase: Zoi.string() |> Zoi.optional(),
                                         status_code: Zoi.any() |> Zoi.optional()
                                       })
  @type continue_response_parameters ::
          unquote(Zoi.type_spec(@continue_response_parameters_schema))

  @continue_with_auth_parameters_schema Zoi.map(%{request: Zoi.any()})
  @type continue_with_auth_parameters ::
          unquote(Zoi.type_spec(@continue_with_auth_parameters_schema))

  @continue_with_auth_credentials_schema Zoi.map(Zoi.string(), Zoi.any())
  @type continue_with_auth_credentials ::
          unquote(Zoi.type_spec(@continue_with_auth_credentials_schema))

  @continue_with_auth_no_credentials_schema Zoi.map(Zoi.string(), Zoi.any())
  @type continue_with_auth_no_credentials ::
          unquote(Zoi.type_spec(@continue_with_auth_no_credentials_schema))

  @disown_data_parameters_schema Zoi.map(%{
                                   data_type: Zoi.any(),
                                   collector: Zoi.any(),
                                   request: Zoi.any()
                                 })
  @type disown_data_parameters :: unquote(Zoi.type_spec(@disown_data_parameters_schema))

  @fail_request_parameters_schema Zoi.map(%{request: Zoi.any()})
  @type fail_request_parameters :: unquote(Zoi.type_spec(@fail_request_parameters_schema))

  @get_data_parameters_schema Zoi.map(%{
                                data_type: Zoi.any(),
                                collector: Zoi.any() |> Zoi.optional(),
                                disown: Zoi.boolean() |> Zoi.optional(),
                                request: Zoi.any()
                              })
  @type get_data_parameters :: unquote(Zoi.type_spec(@get_data_parameters_schema))

  @provide_response_parameters_schema Zoi.map(%{
                                        request: Zoi.any(),
                                        body: Zoi.any() |> Zoi.optional(),
                                        cookies: Zoi.list(Zoi.any()) |> Zoi.optional(),
                                        headers: Zoi.list(Zoi.any()) |> Zoi.optional(),
                                        reason_phrase: Zoi.string() |> Zoi.optional(),
                                        status_code: Zoi.any() |> Zoi.optional()
                                      })
  @type provide_response_parameters :: unquote(Zoi.type_spec(@provide_response_parameters_schema))

  @remove_data_collector_parameters_schema Zoi.map(%{collector: Zoi.any()})
  @type remove_data_collector_parameters ::
          unquote(Zoi.type_spec(@remove_data_collector_parameters_schema))

  @remove_intercept_parameters_schema Zoi.map(%{intercept: Zoi.any()})
  @type remove_intercept_parameters :: unquote(Zoi.type_spec(@remove_intercept_parameters_schema))

  @set_cache_behavior_parameters_schema Zoi.map(%{
                                          cache_behavior: Zoi.union([Zoi.string(), Zoi.string()]),
                                          contexts: Zoi.list(Zoi.any()) |> Zoi.optional()
                                        })
  @type set_cache_behavior_parameters ::
          unquote(Zoi.type_spec(@set_cache_behavior_parameters_schema))

  @set_extra_headers_parameters_schema Zoi.map(%{
                                         headers: Zoi.list(Zoi.any()),
                                         contexts: Zoi.list(Zoi.any()) |> Zoi.optional(),
                                         user_contexts: Zoi.list(Zoi.any()) |> Zoi.optional()
                                       })
  @type set_extra_headers_parameters ::
          unquote(Zoi.type_spec(@set_extra_headers_parameters_schema))

  @auth_challenge_schema Zoi.map(%{scheme: Zoi.string(), realm: Zoi.string()})
  @type auth_challenge :: unquote(Zoi.type_spec(@auth_challenge_schema))

  @base_parameters_schema Zoi.map(Zoi.string(), Zoi.any())
  @type base_parameters :: unquote(Zoi.type_spec(@base_parameters_schema))

  @fetch_timing_info_schema Zoi.map(%{
                              time_origin: Zoi.float(),
                              request_time: Zoi.float(),
                              redirect_start: Zoi.float(),
                              redirect_end: Zoi.float(),
                              fetch_start: Zoi.float(),
                              dns_start: Zoi.float(),
                              dns_end: Zoi.float(),
                              connect_start: Zoi.float(),
                              connect_end: Zoi.float(),
                              tls_start: Zoi.float(),
                              request_start: Zoi.float(),
                              response_start: Zoi.float(),
                              response_end: Zoi.float()
                            })
  @type fetch_timing_info :: unquote(Zoi.type_spec(@fetch_timing_info_schema))

  @initiator_schema Zoi.map(%{
                      column_number: Zoi.any() |> Zoi.optional(),
                      line_number: Zoi.any() |> Zoi.optional(),
                      request: Zoi.any() |> Zoi.optional(),
                      stack_trace: Zoi.any() |> Zoi.optional(),
                      type:
                        Zoi.union([Zoi.string(), Zoi.string(), Zoi.string(), Zoi.string()])
                        |> Zoi.optional()
                    })
  @type initiator :: unquote(Zoi.type_spec(@initiator_schema))

  @request_data_schema Zoi.map(%{
                         request: Zoi.any(),
                         url: Zoi.string(),
                         method: Zoi.string(),
                         headers: Zoi.list(Zoi.any()),
                         cookies: Zoi.list(Zoi.any()),
                         headers_size: Zoi.any(),
                         body_size: Zoi.union([Zoi.any(), Zoi.null()]),
                         destination: Zoi.string(),
                         initiator_type: Zoi.union([Zoi.string(), Zoi.null()]),
                         timings: Zoi.any()
                       })
  @type request_data :: unquote(Zoi.type_spec(@request_data_schema))

  @response_content_schema Zoi.map(%{size: Zoi.any()})
  @type response_content :: unquote(Zoi.type_spec(@response_content_schema))

  @response_data_schema Zoi.map(%{
                          url: Zoi.string(),
                          protocol: Zoi.string(),
                          status: Zoi.any(),
                          status_text: Zoi.string(),
                          from_cache: Zoi.boolean(),
                          headers: Zoi.list(Zoi.any()),
                          mime_type: Zoi.string(),
                          bytes_received: Zoi.any(),
                          headers_size: Zoi.union([Zoi.any(), Zoi.null()]),
                          body_size: Zoi.union([Zoi.any(), Zoi.null()]),
                          content: Zoi.any(),
                          auth_challenges: Zoi.list(Zoi.any()) |> Zoi.optional()
                        })
  @type response_data :: unquote(Zoi.type_spec(@response_data_schema))

  @add_data_collector_result_schema Zoi.map(%{collector: Zoi.any()})
  @type add_data_collector_result :: unquote(Zoi.type_spec(@add_data_collector_result_schema))

  @add_intercept_result_schema Zoi.map(%{intercept: Zoi.any()})
  @type add_intercept_result :: unquote(Zoi.type_spec(@add_intercept_result_schema))

  @continue_request_result_schema Zoi.any()
  @type continue_request_result :: unquote(Zoi.type_spec(@continue_request_result_schema))

  @continue_response_result_schema Zoi.any()
  @type continue_response_result :: unquote(Zoi.type_spec(@continue_response_result_schema))

  @continue_with_auth_result_schema Zoi.any()
  @type continue_with_auth_result :: unquote(Zoi.type_spec(@continue_with_auth_result_schema))

  @disown_data_result_schema Zoi.any()
  @type disown_data_result :: unquote(Zoi.type_spec(@disown_data_result_schema))

  @fail_request_result_schema Zoi.any()
  @type fail_request_result :: unquote(Zoi.type_spec(@fail_request_result_schema))

  @get_data_result_schema Zoi.map(%{bytes: Zoi.any()})
  @type get_data_result :: unquote(Zoi.type_spec(@get_data_result_schema))

  @provide_response_result_schema Zoi.any()
  @type provide_response_result :: unquote(Zoi.type_spec(@provide_response_result_schema))

  @remove_data_collector_result_schema Zoi.any()
  @type remove_data_collector_result ::
          unquote(Zoi.type_spec(@remove_data_collector_result_schema))

  @remove_intercept_result_schema Zoi.any()
  @type remove_intercept_result :: unquote(Zoi.type_spec(@remove_intercept_result_schema))

  @set_cache_behavior_result_schema Zoi.any()
  @type set_cache_behavior_result :: unquote(Zoi.type_spec(@set_cache_behavior_result_schema))

  @set_extra_headers_result_schema Zoi.any()
  @type set_extra_headers_result :: unquote(Zoi.type_spec(@set_extra_headers_result_schema))

  @auth_required_parameters_schema Zoi.map(%{response: Zoi.any()})
  @type auth_required_parameters :: unquote(Zoi.type_spec(@auth_required_parameters_schema))

  @before_request_sent_parameters_schema Zoi.map(%{initiator: Zoi.any() |> Zoi.optional()})
  @type before_request_sent_parameters ::
          unquote(Zoi.type_spec(@before_request_sent_parameters_schema))

  @fetch_error_parameters_schema Zoi.map(%{error_text: Zoi.string()})
  @type fetch_error_parameters :: unquote(Zoi.type_spec(@fetch_error_parameters_schema))

  @response_completed_parameters_schema Zoi.map(%{response: Zoi.any()})
  @type response_completed_parameters ::
          unquote(Zoi.type_spec(@response_completed_parameters_schema))

  @response_started_parameters_schema Zoi.map(%{response: Zoi.any()})
  @type response_started_parameters :: unquote(Zoi.type_spec(@response_started_parameters_schema))

  @doc "Returns the Zoi schema for `auth_credentials`."
  def auth_credentials, do: @auth_credentials_schema

  @doc "Returns the Zoi schema for `bytes_value`."
  def bytes_value, do: @bytes_value_schema

  @doc "Returns the Zoi schema for `string_value`."
  def string_value, do: @string_value_schema

  @doc "Returns the Zoi schema for `base64value`."
  def base64value, do: @base64value_schema

  @doc "Returns the Zoi schema for `collector`."
  def collector, do: @collector_schema

  @doc "Returns the Zoi schema for `collector_type`."
  def collector_type, do: @collector_type_schema

  @doc "Returns the Zoi schema for `same_site`."
  def same_site, do: @same_site_schema

  @doc "Returns the Zoi schema for `cookie`."
  def cookie, do: @cookie_schema

  @doc "Returns the Zoi schema for `cookie_header`."
  def cookie_header, do: @cookie_header_schema

  @doc "Returns the Zoi schema for `data_type`."
  def data_type, do: @data_type_schema

  @doc "Returns the Zoi schema for `header`."
  def header, do: @header_schema

  @doc "Returns the Zoi schema for `intercept`."
  def intercept, do: @intercept_schema

  @doc "Returns the Zoi schema for `request`."
  def request, do: @request_schema

  @doc "Returns the Zoi schema for `set_cookie_header`."
  def set_cookie_header, do: @set_cookie_header_schema

  @doc "Returns the Zoi schema for `url_pattern`."
  def url_pattern, do: @url_pattern_schema

  @doc "Returns the Zoi schema for `url_pattern_pattern`."
  def url_pattern_pattern, do: @url_pattern_pattern_schema

  @doc "Returns the Zoi schema for `url_pattern_string`."
  def url_pattern_string, do: @url_pattern_string_schema

  @doc "Returns the Zoi schema for `add_data_collector_parameters`."
  def add_data_collector_parameters, do: @add_data_collector_parameters_schema

  @doc "Returns the Zoi schema for `add_intercept_parameters`."
  def add_intercept_parameters, do: @add_intercept_parameters_schema

  @doc "Returns the Zoi schema for `intercept_phase`."
  def intercept_phase, do: @intercept_phase_schema

  @doc "Returns the Zoi schema for `continue_request_parameters`."
  def continue_request_parameters, do: @continue_request_parameters_schema

  @doc "Returns the Zoi schema for `continue_response_parameters`."
  def continue_response_parameters, do: @continue_response_parameters_schema

  @doc "Returns the Zoi schema for `continue_with_auth_parameters`."
  def continue_with_auth_parameters, do: @continue_with_auth_parameters_schema

  @doc "Returns the Zoi schema for `continue_with_auth_credentials`."
  def continue_with_auth_credentials, do: @continue_with_auth_credentials_schema

  @doc "Returns the Zoi schema for `continue_with_auth_no_credentials`."
  def continue_with_auth_no_credentials, do: @continue_with_auth_no_credentials_schema

  @doc "Returns the Zoi schema for `disown_data_parameters`."
  def disown_data_parameters, do: @disown_data_parameters_schema

  @doc "Returns the Zoi schema for `fail_request_parameters`."
  def fail_request_parameters, do: @fail_request_parameters_schema

  @doc "Returns the Zoi schema for `get_data_parameters`."
  def get_data_parameters, do: @get_data_parameters_schema

  @doc "Returns the Zoi schema for `provide_response_parameters`."
  def provide_response_parameters, do: @provide_response_parameters_schema

  @doc "Returns the Zoi schema for `remove_data_collector_parameters`."
  def remove_data_collector_parameters, do: @remove_data_collector_parameters_schema

  @doc "Returns the Zoi schema for `remove_intercept_parameters`."
  def remove_intercept_parameters, do: @remove_intercept_parameters_schema

  @doc "Returns the Zoi schema for `set_cache_behavior_parameters`."
  def set_cache_behavior_parameters, do: @set_cache_behavior_parameters_schema

  @doc "Returns the Zoi schema for `set_extra_headers_parameters`."
  def set_extra_headers_parameters, do: @set_extra_headers_parameters_schema

  @doc "Returns the Zoi schema for `auth_challenge`."
  def auth_challenge, do: @auth_challenge_schema

  @doc "Returns the Zoi schema for `base_parameters`."
  def base_parameters, do: @base_parameters_schema

  @doc "Returns the Zoi schema for `fetch_timing_info`."
  def fetch_timing_info, do: @fetch_timing_info_schema

  @doc "Returns the Zoi schema for `initiator`."
  def initiator, do: @initiator_schema

  @doc "Returns the Zoi schema for `request_data`."
  def request_data, do: @request_data_schema

  @doc "Returns the Zoi schema for `response_content`."
  def response_content, do: @response_content_schema

  @doc "Returns the Zoi schema for `response_data`."
  def response_data, do: @response_data_schema

  @doc "Returns the Zoi schema for `add_data_collector_result`."
  def add_data_collector_result, do: @add_data_collector_result_schema

  @doc "Returns the Zoi schema for `add_intercept_result`."
  def add_intercept_result, do: @add_intercept_result_schema

  @doc "Returns the Zoi schema for `continue_request_result`."
  def continue_request_result, do: @continue_request_result_schema

  @doc "Returns the Zoi schema for `continue_response_result`."
  def continue_response_result, do: @continue_response_result_schema

  @doc "Returns the Zoi schema for `continue_with_auth_result`."
  def continue_with_auth_result, do: @continue_with_auth_result_schema

  @doc "Returns the Zoi schema for `disown_data_result`."
  def disown_data_result, do: @disown_data_result_schema

  @doc "Returns the Zoi schema for `fail_request_result`."
  def fail_request_result, do: @fail_request_result_schema

  @doc "Returns the Zoi schema for `get_data_result`."
  def get_data_result, do: @get_data_result_schema

  @doc "Returns the Zoi schema for `provide_response_result`."
  def provide_response_result, do: @provide_response_result_schema

  @doc "Returns the Zoi schema for `remove_data_collector_result`."
  def remove_data_collector_result, do: @remove_data_collector_result_schema

  @doc "Returns the Zoi schema for `remove_intercept_result`."
  def remove_intercept_result, do: @remove_intercept_result_schema

  @doc "Returns the Zoi schema for `set_cache_behavior_result`."
  def set_cache_behavior_result, do: @set_cache_behavior_result_schema

  @doc "Returns the Zoi schema for `set_extra_headers_result`."
  def set_extra_headers_result, do: @set_extra_headers_result_schema

  @doc "Returns the Zoi schema for `auth_required_parameters`."
  def auth_required_parameters, do: @auth_required_parameters_schema

  @doc "Returns the Zoi schema for `before_request_sent_parameters`."
  def before_request_sent_parameters, do: @before_request_sent_parameters_schema

  @doc "Returns the Zoi schema for `fetch_error_parameters`."
  def fetch_error_parameters, do: @fetch_error_parameters_schema

  @doc "Returns the Zoi schema for `response_completed_parameters`."
  def response_completed_parameters, do: @response_completed_parameters_schema

  @doc "Returns the Zoi schema for `response_started_parameters`."
  def response_started_parameters, do: @response_started_parameters_schema
end
