# Generated by mix bibbidi.gen — do not edit manually
defmodule Bibbidi.Types.Script do
  @moduledoc """
  Type definitions and Zoi schemas for the `script` module of the WebDriver BiDi protocol.

  Each type has:
  - A `@type` spec derived from the Zoi schema (for Dialyzer)
  - A function returning the Zoi schema (for runtime validation)
  """

  @channel_schema Zoi.string()
  @type channel :: unquote(Zoi.type_spec(@channel_schema))

  @channel_value_schema Zoi.map(%{type: Zoi.string(), value: Zoi.any()})
  @type channel_value :: unquote(Zoi.type_spec(@channel_value_schema))

  @channel_properties_schema Zoi.map(%{
                               channel: Zoi.any(),
                               serialization_options: Zoi.any() |> Zoi.optional(),
                               ownership: Zoi.any() |> Zoi.optional()
                             })
  @type channel_properties :: unquote(Zoi.type_spec(@channel_properties_schema))

  @evaluate_result_schema Zoi.union([Zoi.any(), Zoi.any()])
  @type evaluate_result :: unquote(Zoi.type_spec(@evaluate_result_schema))

  @evaluate_result_success_schema Zoi.map(%{
                                    type: Zoi.string(),
                                    result: Zoi.any(),
                                    realm: Zoi.any()
                                  })
  @type evaluate_result_success :: unquote(Zoi.type_spec(@evaluate_result_success_schema))

  @evaluate_result_exception_schema Zoi.map(%{
                                      type: Zoi.string(),
                                      exception_details: Zoi.any(),
                                      realm: Zoi.any()
                                    })
  @type evaluate_result_exception :: unquote(Zoi.type_spec(@evaluate_result_exception_schema))

  @exception_details_schema Zoi.map(%{
                              column_number: Zoi.any(),
                              exception: Zoi.any(),
                              line_number: Zoi.any(),
                              stack_trace: Zoi.any(),
                              text: Zoi.string()
                            })
  @type exception_details :: unquote(Zoi.type_spec(@exception_details_schema))

  @handle_schema Zoi.string()
  @type handle :: unquote(Zoi.type_spec(@handle_schema))

  @internal_id_schema Zoi.string()
  @type internal_id :: unquote(Zoi.type_spec(@internal_id_schema))

  @local_value_schema Zoi.union([
                        Zoi.any(),
                        Zoi.any(),
                        Zoi.any(),
                        Zoi.any(),
                        Zoi.map(%{}),
                        Zoi.any(),
                        Zoi.any(),
                        Zoi.map(%{}),
                        Zoi.any()
                      ])
  @type local_value :: unquote(Zoi.type_spec(@local_value_schema))

  @list_local_value_schema Zoi.list(Zoi.any())
  @type list_local_value :: unquote(Zoi.type_spec(@list_local_value_schema))

  @array_local_value_schema Zoi.map(%{type: Zoi.string(), value: Zoi.any()})
  @type array_local_value :: unquote(Zoi.type_spec(@array_local_value_schema))

  @date_local_value_schema Zoi.map(Zoi.string(), Zoi.any())
  @type date_local_value :: unquote(Zoi.type_spec(@date_local_value_schema))

  @mapping_local_value_schema Zoi.list(
                                Zoi.tuple({Zoi.union([Zoi.any(), Zoi.string()]), Zoi.any()})
                              )
  @type mapping_local_value :: unquote(Zoi.type_spec(@mapping_local_value_schema))

  @map_local_value_schema Zoi.map(%{type: Zoi.string(), value: Zoi.any()})
  @type map_local_value :: unquote(Zoi.type_spec(@map_local_value_schema))

  @object_local_value_schema Zoi.map(%{type: Zoi.string(), value: Zoi.any()})
  @type object_local_value :: unquote(Zoi.type_spec(@object_local_value_schema))

  @reg_exp_value_schema Zoi.map(%{pattern: Zoi.string(), flags: Zoi.string() |> Zoi.optional()})
  @type reg_exp_value :: unquote(Zoi.type_spec(@reg_exp_value_schema))

  @reg_exp_local_value_schema Zoi.map(Zoi.string(), Zoi.any())
  @type reg_exp_local_value :: unquote(Zoi.type_spec(@reg_exp_local_value_schema))

  @set_local_value_schema Zoi.map(%{type: Zoi.string(), value: Zoi.any()})
  @type set_local_value :: unquote(Zoi.type_spec(@set_local_value_schema))

  @preload_script_schema Zoi.string()
  @type preload_script :: unquote(Zoi.type_spec(@preload_script_schema))

  @realm_schema Zoi.string()
  @type realm :: unquote(Zoi.type_spec(@realm_schema))

  @primitive_protocol_value_schema Zoi.union([
                                     Zoi.any(),
                                     Zoi.any(),
                                     Zoi.any(),
                                     Zoi.any(),
                                     Zoi.any(),
                                     Zoi.any()
                                   ])
  @type primitive_protocol_value :: unquote(Zoi.type_spec(@primitive_protocol_value_schema))

  @undefined_value_schema Zoi.map(%{type: Zoi.string()})
  @type undefined_value :: unquote(Zoi.type_spec(@undefined_value_schema))

  @null_value_schema Zoi.map(%{type: Zoi.string()})
  @type null_value :: unquote(Zoi.type_spec(@null_value_schema))

  @string_value_schema Zoi.map(%{type: Zoi.string(), value: Zoi.string()})
  @type string_value :: unquote(Zoi.type_spec(@string_value_schema))

  @special_number_schema Zoi.union([Zoi.string(), Zoi.string(), Zoi.string(), Zoi.string()])
  @type special_number :: unquote(Zoi.type_spec(@special_number_schema))

  @number_value_schema Zoi.map(%{type: Zoi.string(), value: Zoi.union([Zoi.any(), Zoi.any()])})
  @type number_value :: unquote(Zoi.type_spec(@number_value_schema))

  @boolean_value_schema Zoi.map(%{type: Zoi.string(), value: Zoi.boolean()})
  @type boolean_value :: unquote(Zoi.type_spec(@boolean_value_schema))

  @big_int_value_schema Zoi.map(%{type: Zoi.string(), value: Zoi.string()})
  @type big_int_value :: unquote(Zoi.type_spec(@big_int_value_schema))

  @realm_type_schema Zoi.union([
                       Zoi.string(),
                       Zoi.string(),
                       Zoi.string(),
                       Zoi.string(),
                       Zoi.string(),
                       Zoi.string(),
                       Zoi.string(),
                       Zoi.string()
                     ])
  @type realm_type :: unquote(Zoi.type_spec(@realm_type_schema))

  @remote_reference_schema Zoi.union([Zoi.any(), Zoi.any()])
  @type remote_reference :: unquote(Zoi.type_spec(@remote_reference_schema))

  @shared_reference_schema Zoi.map(%{shared_id: Zoi.any(), handle: Zoi.any() |> Zoi.optional()})
  @type shared_reference :: unquote(Zoi.type_spec(@shared_reference_schema))

  @remote_object_reference_schema Zoi.map(%{
                                    handle: Zoi.any(),
                                    shared_id: Zoi.any() |> Zoi.optional()
                                  })
  @type remote_object_reference :: unquote(Zoi.type_spec(@remote_object_reference_schema))

  @remote_value_schema Zoi.union([
                         Zoi.any(),
                         Zoi.any(),
                         Zoi.any(),
                         Zoi.any(),
                         Zoi.any(),
                         Zoi.any(),
                         Zoi.any(),
                         Zoi.any(),
                         Zoi.any(),
                         Zoi.any(),
                         Zoi.any(),
                         Zoi.any(),
                         Zoi.any(),
                         Zoi.any(),
                         Zoi.any(),
                         Zoi.any(),
                         Zoi.any(),
                         Zoi.any(),
                         Zoi.any(),
                         Zoi.any(),
                         Zoi.any()
                       ])
  @type remote_value :: unquote(Zoi.type_spec(@remote_value_schema))

  @list_remote_value_schema Zoi.list(Zoi.any())
  @type list_remote_value :: unquote(Zoi.type_spec(@list_remote_value_schema))

  @mapping_remote_value_schema Zoi.list(
                                 Zoi.tuple({Zoi.union([Zoi.any(), Zoi.string()]), Zoi.any()})
                               )
  @type mapping_remote_value :: unquote(Zoi.type_spec(@mapping_remote_value_schema))

  @symbol_remote_value_schema Zoi.map(%{
                                type: Zoi.string(),
                                handle: Zoi.any() |> Zoi.optional(),
                                internal_id: Zoi.any() |> Zoi.optional()
                              })
  @type symbol_remote_value :: unquote(Zoi.type_spec(@symbol_remote_value_schema))

  @array_remote_value_schema Zoi.map(%{
                               type: Zoi.string(),
                               handle: Zoi.any() |> Zoi.optional(),
                               internal_id: Zoi.any() |> Zoi.optional(),
                               value: Zoi.any() |> Zoi.optional()
                             })
  @type array_remote_value :: unquote(Zoi.type_spec(@array_remote_value_schema))

  @object_remote_value_schema Zoi.map(%{
                                type: Zoi.string(),
                                handle: Zoi.any() |> Zoi.optional(),
                                internal_id: Zoi.any() |> Zoi.optional(),
                                value: Zoi.any() |> Zoi.optional()
                              })
  @type object_remote_value :: unquote(Zoi.type_spec(@object_remote_value_schema))

  @function_remote_value_schema Zoi.map(%{
                                  type: Zoi.string(),
                                  handle: Zoi.any() |> Zoi.optional(),
                                  internal_id: Zoi.any() |> Zoi.optional()
                                })
  @type function_remote_value :: unquote(Zoi.type_spec(@function_remote_value_schema))

  @reg_exp_remote_value_schema Zoi.map(%{
                                 handle: Zoi.any() |> Zoi.optional(),
                                 internal_id: Zoi.any() |> Zoi.optional()
                               })
  @type reg_exp_remote_value :: unquote(Zoi.type_spec(@reg_exp_remote_value_schema))

  @date_remote_value_schema Zoi.map(%{
                              handle: Zoi.any() |> Zoi.optional(),
                              internal_id: Zoi.any() |> Zoi.optional()
                            })
  @type date_remote_value :: unquote(Zoi.type_spec(@date_remote_value_schema))

  @map_remote_value_schema Zoi.map(%{
                             type: Zoi.string(),
                             handle: Zoi.any() |> Zoi.optional(),
                             internal_id: Zoi.any() |> Zoi.optional(),
                             value: Zoi.any() |> Zoi.optional()
                           })
  @type map_remote_value :: unquote(Zoi.type_spec(@map_remote_value_schema))

  @set_remote_value_schema Zoi.map(%{
                             type: Zoi.string(),
                             handle: Zoi.any() |> Zoi.optional(),
                             internal_id: Zoi.any() |> Zoi.optional(),
                             value: Zoi.any() |> Zoi.optional()
                           })
  @type set_remote_value :: unquote(Zoi.type_spec(@set_remote_value_schema))

  @weak_map_remote_value_schema Zoi.map(%{
                                  type: Zoi.string(),
                                  handle: Zoi.any() |> Zoi.optional(),
                                  internal_id: Zoi.any() |> Zoi.optional()
                                })
  @type weak_map_remote_value :: unquote(Zoi.type_spec(@weak_map_remote_value_schema))

  @weak_set_remote_value_schema Zoi.map(%{
                                  type: Zoi.string(),
                                  handle: Zoi.any() |> Zoi.optional(),
                                  internal_id: Zoi.any() |> Zoi.optional()
                                })
  @type weak_set_remote_value :: unquote(Zoi.type_spec(@weak_set_remote_value_schema))

  @generator_remote_value_schema Zoi.map(%{
                                   type: Zoi.string(),
                                   handle: Zoi.any() |> Zoi.optional(),
                                   internal_id: Zoi.any() |> Zoi.optional()
                                 })
  @type generator_remote_value :: unquote(Zoi.type_spec(@generator_remote_value_schema))

  @error_remote_value_schema Zoi.map(%{
                               type: Zoi.string(),
                               handle: Zoi.any() |> Zoi.optional(),
                               internal_id: Zoi.any() |> Zoi.optional()
                             })
  @type error_remote_value :: unquote(Zoi.type_spec(@error_remote_value_schema))

  @proxy_remote_value_schema Zoi.map(%{
                               type: Zoi.string(),
                               handle: Zoi.any() |> Zoi.optional(),
                               internal_id: Zoi.any() |> Zoi.optional()
                             })
  @type proxy_remote_value :: unquote(Zoi.type_spec(@proxy_remote_value_schema))

  @promise_remote_value_schema Zoi.map(%{
                                 type: Zoi.string(),
                                 handle: Zoi.any() |> Zoi.optional(),
                                 internal_id: Zoi.any() |> Zoi.optional()
                               })
  @type promise_remote_value :: unquote(Zoi.type_spec(@promise_remote_value_schema))

  @typed_array_remote_value_schema Zoi.map(%{
                                     type: Zoi.string(),
                                     handle: Zoi.any() |> Zoi.optional(),
                                     internal_id: Zoi.any() |> Zoi.optional()
                                   })
  @type typed_array_remote_value :: unquote(Zoi.type_spec(@typed_array_remote_value_schema))

  @array_buffer_remote_value_schema Zoi.map(%{
                                      type: Zoi.string(),
                                      handle: Zoi.any() |> Zoi.optional(),
                                      internal_id: Zoi.any() |> Zoi.optional()
                                    })
  @type array_buffer_remote_value :: unquote(Zoi.type_spec(@array_buffer_remote_value_schema))

  @node_list_remote_value_schema Zoi.map(%{
                                   type: Zoi.string(),
                                   handle: Zoi.any() |> Zoi.optional(),
                                   internal_id: Zoi.any() |> Zoi.optional(),
                                   value: Zoi.any() |> Zoi.optional()
                                 })
  @type node_list_remote_value :: unquote(Zoi.type_spec(@node_list_remote_value_schema))

  @html_collection_remote_value_schema Zoi.map(%{
                                         type: Zoi.string(),
                                         handle: Zoi.any() |> Zoi.optional(),
                                         internal_id: Zoi.any() |> Zoi.optional(),
                                         value: Zoi.any() |> Zoi.optional()
                                       })
  @type html_collection_remote_value ::
          unquote(Zoi.type_spec(@html_collection_remote_value_schema))

  @node_remote_value_schema Zoi.map(%{
                              type: Zoi.string(),
                              shared_id: Zoi.any() |> Zoi.optional(),
                              handle: Zoi.any() |> Zoi.optional(),
                              internal_id: Zoi.any() |> Zoi.optional(),
                              value: Zoi.any() |> Zoi.optional()
                            })
  @type node_remote_value :: unquote(Zoi.type_spec(@node_remote_value_schema))

  @node_properties_schema Zoi.map(%{
                            node_type: Zoi.any(),
                            child_node_count: Zoi.any(),
                            attributes: Zoi.map(%{}) |> Zoi.optional(),
                            children: Zoi.list(Zoi.any()) |> Zoi.optional(),
                            local_name: Zoi.string() |> Zoi.optional(),
                            mode: Zoi.union([Zoi.string(), Zoi.string()]) |> Zoi.optional(),
                            namespace_uri: Zoi.string() |> Zoi.optional(),
                            node_value: Zoi.string() |> Zoi.optional(),
                            shadow_root: Zoi.union([Zoi.any(), Zoi.null()]) |> Zoi.optional()
                          })
  @type node_properties :: unquote(Zoi.type_spec(@node_properties_schema))

  @window_proxy_remote_value_schema Zoi.map(%{
                                      type: Zoi.string(),
                                      value: Zoi.any(),
                                      handle: Zoi.any() |> Zoi.optional(),
                                      internal_id: Zoi.any() |> Zoi.optional()
                                    })
  @type window_proxy_remote_value :: unquote(Zoi.type_spec(@window_proxy_remote_value_schema))

  @window_proxy_properties_schema Zoi.map(%{context: Zoi.any()})
  @type window_proxy_properties :: unquote(Zoi.type_spec(@window_proxy_properties_schema))

  @result_ownership_schema Zoi.union([Zoi.string(), Zoi.string()])
  @type result_ownership :: unquote(Zoi.type_spec(@result_ownership_schema))

  @serialization_options_schema Zoi.map(%{
                                  max_dom_depth: Zoi.any() |> Zoi.optional(),
                                  max_object_depth: Zoi.any() |> Zoi.optional(),
                                  include_shadow_tree: Zoi.any() |> Zoi.optional()
                                })
  @type serialization_options :: unquote(Zoi.type_spec(@serialization_options_schema))

  @shared_id_schema Zoi.string()
  @type shared_id :: unquote(Zoi.type_spec(@shared_id_schema))

  @stack_frame_schema Zoi.map(%{
                        column_number: Zoi.any(),
                        function_name: Zoi.string(),
                        line_number: Zoi.any(),
                        url: Zoi.string()
                      })
  @type stack_frame :: unquote(Zoi.type_spec(@stack_frame_schema))

  @stack_trace_schema Zoi.map(%{call_frames: Zoi.list(Zoi.any())})
  @type stack_trace :: unquote(Zoi.type_spec(@stack_trace_schema))

  @realm_target_schema Zoi.map(%{realm: Zoi.any()})
  @type realm_target :: unquote(Zoi.type_spec(@realm_target_schema))

  @context_target_schema Zoi.map(%{context: Zoi.any(), sandbox: Zoi.string() |> Zoi.optional()})
  @type context_target :: unquote(Zoi.type_spec(@context_target_schema))

  @target_schema Zoi.union([Zoi.any(), Zoi.any()])
  @type target :: unquote(Zoi.type_spec(@target_schema))

  @add_preload_script_parameters_schema Zoi.map(%{
                                          function_declaration: Zoi.string(),
                                          arguments: Zoi.list(Zoi.any()) |> Zoi.optional(),
                                          contexts: Zoi.list(Zoi.any()) |> Zoi.optional(),
                                          user_contexts: Zoi.list(Zoi.any()) |> Zoi.optional(),
                                          sandbox: Zoi.string() |> Zoi.optional()
                                        })
  @type add_preload_script_parameters ::
          unquote(Zoi.type_spec(@add_preload_script_parameters_schema))

  @disown_parameters_schema Zoi.map(%{handles: Zoi.list(Zoi.any()), target: Zoi.any()})
  @type disown_parameters :: unquote(Zoi.type_spec(@disown_parameters_schema))

  @call_function_parameters_schema Zoi.map(%{
                                     function_declaration: Zoi.string(),
                                     await_promise: Zoi.boolean(),
                                     target: Zoi.any(),
                                     arguments: Zoi.list(Zoi.any()) |> Zoi.optional(),
                                     result_ownership: Zoi.any() |> Zoi.optional(),
                                     serialization_options: Zoi.any() |> Zoi.optional(),
                                     this: Zoi.any() |> Zoi.optional(),
                                     user_activation: Zoi.boolean() |> Zoi.optional()
                                   })
  @type call_function_parameters :: unquote(Zoi.type_spec(@call_function_parameters_schema))

  @evaluate_parameters_schema Zoi.map(%{
                                expression: Zoi.string(),
                                target: Zoi.any(),
                                await_promise: Zoi.boolean(),
                                result_ownership: Zoi.any() |> Zoi.optional(),
                                serialization_options: Zoi.any() |> Zoi.optional(),
                                user_activation: Zoi.boolean() |> Zoi.optional()
                              })
  @type evaluate_parameters :: unquote(Zoi.type_spec(@evaluate_parameters_schema))

  @get_realms_parameters_schema Zoi.map(%{
                                  context: Zoi.any() |> Zoi.optional(),
                                  type: Zoi.any() |> Zoi.optional()
                                })
  @type get_realms_parameters :: unquote(Zoi.type_spec(@get_realms_parameters_schema))

  @remove_preload_script_parameters_schema Zoi.map(%{script: Zoi.any()})
  @type remove_preload_script_parameters ::
          unquote(Zoi.type_spec(@remove_preload_script_parameters_schema))

  @realm_info_schema Zoi.union([
                       Zoi.any(),
                       Zoi.any(),
                       Zoi.any(),
                       Zoi.any(),
                       Zoi.any(),
                       Zoi.any(),
                       Zoi.any(),
                       Zoi.any()
                     ])
  @type realm_info :: unquote(Zoi.type_spec(@realm_info_schema))

  @base_realm_info_schema Zoi.map(Zoi.string(), Zoi.any())
  @type base_realm_info :: unquote(Zoi.type_spec(@base_realm_info_schema))

  @window_realm_info_schema Zoi.map(%{
                              type: Zoi.string(),
                              context: Zoi.any(),
                              user_context: Zoi.any() |> Zoi.optional(),
                              sandbox: Zoi.string() |> Zoi.optional()
                            })
  @type window_realm_info :: unquote(Zoi.type_spec(@window_realm_info_schema))

  @dedicated_worker_realm_info_schema Zoi.map(%{type: Zoi.string(), owners: Zoi.list(Zoi.any())})
  @type dedicated_worker_realm_info :: unquote(Zoi.type_spec(@dedicated_worker_realm_info_schema))

  @shared_worker_realm_info_schema Zoi.map(%{type: Zoi.string()})
  @type shared_worker_realm_info :: unquote(Zoi.type_spec(@shared_worker_realm_info_schema))

  @service_worker_realm_info_schema Zoi.map(%{type: Zoi.string()})
  @type service_worker_realm_info :: unquote(Zoi.type_spec(@service_worker_realm_info_schema))

  @worker_realm_info_schema Zoi.map(%{type: Zoi.string()})
  @type worker_realm_info :: unquote(Zoi.type_spec(@worker_realm_info_schema))

  @paint_worklet_realm_info_schema Zoi.map(%{type: Zoi.string()})
  @type paint_worklet_realm_info :: unquote(Zoi.type_spec(@paint_worklet_realm_info_schema))

  @audio_worklet_realm_info_schema Zoi.map(%{type: Zoi.string()})
  @type audio_worklet_realm_info :: unquote(Zoi.type_spec(@audio_worklet_realm_info_schema))

  @worklet_realm_info_schema Zoi.map(%{type: Zoi.string()})
  @type worklet_realm_info :: unquote(Zoi.type_spec(@worklet_realm_info_schema))

  @source_schema Zoi.map(%{
                   realm: Zoi.any(),
                   context: Zoi.any() |> Zoi.optional(),
                   user_context: Zoi.any() |> Zoi.optional()
                 })
  @type source :: unquote(Zoi.type_spec(@source_schema))

  @add_preload_script_result_schema Zoi.map(%{script: Zoi.any()})
  @type add_preload_script_result :: unquote(Zoi.type_spec(@add_preload_script_result_schema))

  @disown_result_schema Zoi.any()
  @type disown_result :: unquote(Zoi.type_spec(@disown_result_schema))

  @call_function_result_schema Zoi.any()
  @type call_function_result :: unquote(Zoi.type_spec(@call_function_result_schema))

  @get_realms_result_schema Zoi.map(%{realms: Zoi.list(Zoi.any())})
  @type get_realms_result :: unquote(Zoi.type_spec(@get_realms_result_schema))

  @remove_preload_script_result_schema Zoi.any()
  @type remove_preload_script_result ::
          unquote(Zoi.type_spec(@remove_preload_script_result_schema))

  @message_parameters_schema Zoi.map(%{channel: Zoi.any(), data: Zoi.any(), source: Zoi.any()})
  @type message_parameters :: unquote(Zoi.type_spec(@message_parameters_schema))

  @realm_destroyed_parameters_schema Zoi.map(%{realm: Zoi.any()})
  @type realm_destroyed_parameters :: unquote(Zoi.type_spec(@realm_destroyed_parameters_schema))

  @doc "Returns the Zoi schema for `channel`."
  def channel, do: @channel_schema

  @doc "Returns the Zoi schema for `channel_value`."
  def channel_value, do: @channel_value_schema

  @doc "Returns the Zoi schema for `channel_properties`."
  def channel_properties, do: @channel_properties_schema

  @doc "Returns the Zoi schema for `evaluate_result`."
  def evaluate_result, do: @evaluate_result_schema

  @doc "Returns the Zoi schema for `evaluate_result_success`."
  def evaluate_result_success, do: @evaluate_result_success_schema

  @doc "Returns the Zoi schema for `evaluate_result_exception`."
  def evaluate_result_exception, do: @evaluate_result_exception_schema

  @doc "Returns the Zoi schema for `exception_details`."
  def exception_details, do: @exception_details_schema

  @doc "Returns the Zoi schema for `handle`."
  def handle, do: @handle_schema

  @doc "Returns the Zoi schema for `internal_id`."
  def internal_id, do: @internal_id_schema

  @doc "Returns the Zoi schema for `local_value`."
  def local_value, do: @local_value_schema

  @doc "Returns the Zoi schema for `list_local_value`."
  def list_local_value, do: @list_local_value_schema

  @doc "Returns the Zoi schema for `array_local_value`."
  def array_local_value, do: @array_local_value_schema

  @doc "Returns the Zoi schema for `date_local_value`."
  def date_local_value, do: @date_local_value_schema

  @doc "Returns the Zoi schema for `mapping_local_value`."
  def mapping_local_value, do: @mapping_local_value_schema

  @doc "Returns the Zoi schema for `map_local_value`."
  def map_local_value, do: @map_local_value_schema

  @doc "Returns the Zoi schema for `object_local_value`."
  def object_local_value, do: @object_local_value_schema

  @doc "Returns the Zoi schema for `reg_exp_value`."
  def reg_exp_value, do: @reg_exp_value_schema

  @doc "Returns the Zoi schema for `reg_exp_local_value`."
  def reg_exp_local_value, do: @reg_exp_local_value_schema

  @doc "Returns the Zoi schema for `set_local_value`."
  def set_local_value, do: @set_local_value_schema

  @doc "Returns the Zoi schema for `preload_script`."
  def preload_script, do: @preload_script_schema

  @doc "Returns the Zoi schema for `realm`."
  def realm, do: @realm_schema

  @doc "Returns the Zoi schema for `primitive_protocol_value`."
  def primitive_protocol_value, do: @primitive_protocol_value_schema

  @doc "Returns the Zoi schema for `undefined_value`."
  def undefined_value, do: @undefined_value_schema

  @doc "Returns the Zoi schema for `null_value`."
  def null_value, do: @null_value_schema

  @doc "Returns the Zoi schema for `string_value`."
  def string_value, do: @string_value_schema

  @doc "Returns the Zoi schema for `special_number`."
  def special_number, do: @special_number_schema

  @doc "Returns the Zoi schema for `number_value`."
  def number_value, do: @number_value_schema

  @doc "Returns the Zoi schema for `boolean_value`."
  def boolean_value, do: @boolean_value_schema

  @doc "Returns the Zoi schema for `big_int_value`."
  def big_int_value, do: @big_int_value_schema

  @doc "Returns the Zoi schema for `realm_type`."
  def realm_type, do: @realm_type_schema

  @doc "Returns the Zoi schema for `remote_reference`."
  def remote_reference, do: @remote_reference_schema

  @doc "Returns the Zoi schema for `shared_reference`."
  def shared_reference, do: @shared_reference_schema

  @doc "Returns the Zoi schema for `remote_object_reference`."
  def remote_object_reference, do: @remote_object_reference_schema

  @doc "Returns the Zoi schema for `remote_value`."
  def remote_value, do: @remote_value_schema

  @doc "Returns the Zoi schema for `list_remote_value`."
  def list_remote_value, do: @list_remote_value_schema

  @doc "Returns the Zoi schema for `mapping_remote_value`."
  def mapping_remote_value, do: @mapping_remote_value_schema

  @doc "Returns the Zoi schema for `symbol_remote_value`."
  def symbol_remote_value, do: @symbol_remote_value_schema

  @doc "Returns the Zoi schema for `array_remote_value`."
  def array_remote_value, do: @array_remote_value_schema

  @doc "Returns the Zoi schema for `object_remote_value`."
  def object_remote_value, do: @object_remote_value_schema

  @doc "Returns the Zoi schema for `function_remote_value`."
  def function_remote_value, do: @function_remote_value_schema

  @doc "Returns the Zoi schema for `reg_exp_remote_value`."
  def reg_exp_remote_value, do: @reg_exp_remote_value_schema

  @doc "Returns the Zoi schema for `date_remote_value`."
  def date_remote_value, do: @date_remote_value_schema

  @doc "Returns the Zoi schema for `map_remote_value`."
  def map_remote_value, do: @map_remote_value_schema

  @doc "Returns the Zoi schema for `set_remote_value`."
  def set_remote_value, do: @set_remote_value_schema

  @doc "Returns the Zoi schema for `weak_map_remote_value`."
  def weak_map_remote_value, do: @weak_map_remote_value_schema

  @doc "Returns the Zoi schema for `weak_set_remote_value`."
  def weak_set_remote_value, do: @weak_set_remote_value_schema

  @doc "Returns the Zoi schema for `generator_remote_value`."
  def generator_remote_value, do: @generator_remote_value_schema

  @doc "Returns the Zoi schema for `error_remote_value`."
  def error_remote_value, do: @error_remote_value_schema

  @doc "Returns the Zoi schema for `proxy_remote_value`."
  def proxy_remote_value, do: @proxy_remote_value_schema

  @doc "Returns the Zoi schema for `promise_remote_value`."
  def promise_remote_value, do: @promise_remote_value_schema

  @doc "Returns the Zoi schema for `typed_array_remote_value`."
  def typed_array_remote_value, do: @typed_array_remote_value_schema

  @doc "Returns the Zoi schema for `array_buffer_remote_value`."
  def array_buffer_remote_value, do: @array_buffer_remote_value_schema

  @doc "Returns the Zoi schema for `node_list_remote_value`."
  def node_list_remote_value, do: @node_list_remote_value_schema

  @doc "Returns the Zoi schema for `html_collection_remote_value`."
  def html_collection_remote_value, do: @html_collection_remote_value_schema

  @doc "Returns the Zoi schema for `node_remote_value`."
  def node_remote_value, do: @node_remote_value_schema

  @doc "Returns the Zoi schema for `node_properties`."
  def node_properties, do: @node_properties_schema

  @doc "Returns the Zoi schema for `window_proxy_remote_value`."
  def window_proxy_remote_value, do: @window_proxy_remote_value_schema

  @doc "Returns the Zoi schema for `window_proxy_properties`."
  def window_proxy_properties, do: @window_proxy_properties_schema

  @doc "Returns the Zoi schema for `result_ownership`."
  def result_ownership, do: @result_ownership_schema

  @doc "Returns the Zoi schema for `serialization_options`."
  def serialization_options, do: @serialization_options_schema

  @doc "Returns the Zoi schema for `shared_id`."
  def shared_id, do: @shared_id_schema

  @doc "Returns the Zoi schema for `stack_frame`."
  def stack_frame, do: @stack_frame_schema

  @doc "Returns the Zoi schema for `stack_trace`."
  def stack_trace, do: @stack_trace_schema

  @doc "Returns the Zoi schema for `realm_target`."
  def realm_target, do: @realm_target_schema

  @doc "Returns the Zoi schema for `context_target`."
  def context_target, do: @context_target_schema

  @doc "Returns the Zoi schema for `target`."
  def target, do: @target_schema

  @doc "Returns the Zoi schema for `add_preload_script_parameters`."
  def add_preload_script_parameters, do: @add_preload_script_parameters_schema

  @doc "Returns the Zoi schema for `disown_parameters`."
  def disown_parameters, do: @disown_parameters_schema

  @doc "Returns the Zoi schema for `call_function_parameters`."
  def call_function_parameters, do: @call_function_parameters_schema

  @doc "Returns the Zoi schema for `evaluate_parameters`."
  def evaluate_parameters, do: @evaluate_parameters_schema

  @doc "Returns the Zoi schema for `get_realms_parameters`."
  def get_realms_parameters, do: @get_realms_parameters_schema

  @doc "Returns the Zoi schema for `remove_preload_script_parameters`."
  def remove_preload_script_parameters, do: @remove_preload_script_parameters_schema

  @doc "Returns the Zoi schema for `realm_info`."
  def realm_info, do: @realm_info_schema

  @doc "Returns the Zoi schema for `base_realm_info`."
  def base_realm_info, do: @base_realm_info_schema

  @doc "Returns the Zoi schema for `window_realm_info`."
  def window_realm_info, do: @window_realm_info_schema

  @doc "Returns the Zoi schema for `dedicated_worker_realm_info`."
  def dedicated_worker_realm_info, do: @dedicated_worker_realm_info_schema

  @doc "Returns the Zoi schema for `shared_worker_realm_info`."
  def shared_worker_realm_info, do: @shared_worker_realm_info_schema

  @doc "Returns the Zoi schema for `service_worker_realm_info`."
  def service_worker_realm_info, do: @service_worker_realm_info_schema

  @doc "Returns the Zoi schema for `worker_realm_info`."
  def worker_realm_info, do: @worker_realm_info_schema

  @doc "Returns the Zoi schema for `paint_worklet_realm_info`."
  def paint_worklet_realm_info, do: @paint_worklet_realm_info_schema

  @doc "Returns the Zoi schema for `audio_worklet_realm_info`."
  def audio_worklet_realm_info, do: @audio_worklet_realm_info_schema

  @doc "Returns the Zoi schema for `worklet_realm_info`."
  def worklet_realm_info, do: @worklet_realm_info_schema

  @doc "Returns the Zoi schema for `source`."
  def source, do: @source_schema

  @doc "Returns the Zoi schema for `add_preload_script_result`."
  def add_preload_script_result, do: @add_preload_script_result_schema

  @doc "Returns the Zoi schema for `disown_result`."
  def disown_result, do: @disown_result_schema

  @doc "Returns the Zoi schema for `call_function_result`."
  def call_function_result, do: @call_function_result_schema

  @doc "Returns the Zoi schema for `get_realms_result`."
  def get_realms_result, do: @get_realms_result_schema

  @doc "Returns the Zoi schema for `remove_preload_script_result`."
  def remove_preload_script_result, do: @remove_preload_script_result_schema

  @doc "Returns the Zoi schema for `message_parameters`."
  def message_parameters, do: @message_parameters_schema

  @doc "Returns the Zoi schema for `realm_destroyed_parameters`."
  def realm_destroyed_parameters, do: @realm_destroyed_parameters_schema
end
