# Generated by mix bibbidi.gen — do not edit manually
defmodule Bibbidi.Types.Session do
  @moduledoc """
  Type definitions and Zoi schemas for the `session` module of the WebDriver BiDi protocol.

  Each type has:
  - A `@type` spec derived from the Zoi schema (for Dialyzer)
  - A function returning the Zoi schema (for runtime validation)
  """

  @capabilities_request_schema Zoi.map(%{
                                 always_match: Zoi.any() |> Zoi.optional(),
                                 first_match: Zoi.list(Zoi.any()) |> Zoi.optional()
                               })
  @type capabilities_request :: unquote(Zoi.type_spec(@capabilities_request_schema))

  @capability_request_schema Zoi.map(%{
                               accept_insecure_certs: Zoi.boolean() |> Zoi.optional(),
                               browser_name: Zoi.string() |> Zoi.optional(),
                               browser_version: Zoi.string() |> Zoi.optional(),
                               platform_name: Zoi.string() |> Zoi.optional(),
                               proxy: Zoi.any() |> Zoi.optional(),
                               unhandled_prompt_behavior: Zoi.any() |> Zoi.optional()
                             })
  @type capability_request :: unquote(Zoi.type_spec(@capability_request_schema))

  @proxy_configuration_schema Zoi.map(Zoi.string(), Zoi.any())
  @type proxy_configuration :: unquote(Zoi.type_spec(@proxy_configuration_schema))

  @autodetect_proxy_configuration_schema Zoi.map(Zoi.string(), Zoi.any())
  @type autodetect_proxy_configuration ::
          unquote(Zoi.type_spec(@autodetect_proxy_configuration_schema))

  @direct_proxy_configuration_schema Zoi.map(Zoi.string(), Zoi.any())
  @type direct_proxy_configuration :: unquote(Zoi.type_spec(@direct_proxy_configuration_schema))

  @manual_proxy_configuration_schema Zoi.map(Zoi.string(), Zoi.any())
  @type manual_proxy_configuration :: unquote(Zoi.type_spec(@manual_proxy_configuration_schema))

  @socks_proxy_configuration_schema Zoi.map(Zoi.string(), Zoi.any())
  @type socks_proxy_configuration :: unquote(Zoi.type_spec(@socks_proxy_configuration_schema))

  @pac_proxy_configuration_schema Zoi.map(Zoi.string(), Zoi.any())
  @type pac_proxy_configuration :: unquote(Zoi.type_spec(@pac_proxy_configuration_schema))

  @system_proxy_configuration_schema Zoi.map(Zoi.string(), Zoi.any())
  @type system_proxy_configuration :: unquote(Zoi.type_spec(@system_proxy_configuration_schema))

  @user_prompt_handler_schema Zoi.map(%{
                                alert: Zoi.any() |> Zoi.optional(),
                                before_unload: Zoi.any() |> Zoi.optional(),
                                confirm: Zoi.any() |> Zoi.optional(),
                                default: Zoi.any() |> Zoi.optional(),
                                file: Zoi.any() |> Zoi.optional(),
                                prompt: Zoi.any() |> Zoi.optional()
                              })
  @type user_prompt_handler :: unquote(Zoi.type_spec(@user_prompt_handler_schema))

  @user_prompt_handler_type_schema Zoi.union([Zoi.string(), Zoi.string(), Zoi.string()])
  @type user_prompt_handler_type :: unquote(Zoi.type_spec(@user_prompt_handler_type_schema))

  @subscription_schema Zoi.string()
  @type subscription :: unquote(Zoi.type_spec(@subscription_schema))

  @subscribe_parameters_schema Zoi.map(%{
                                 events: Zoi.list(Zoi.string()),
                                 contexts: Zoi.list(Zoi.any()) |> Zoi.optional(),
                                 user_contexts: Zoi.list(Zoi.any()) |> Zoi.optional()
                               })
  @type subscribe_parameters :: unquote(Zoi.type_spec(@subscribe_parameters_schema))

  @unsubscribe_by_id_request_schema Zoi.map(%{subscriptions: Zoi.list(Zoi.any())})
  @type unsubscribe_by_id_request :: unquote(Zoi.type_spec(@unsubscribe_by_id_request_schema))

  @unsubscribe_by_attributes_request_schema Zoi.map(%{events: Zoi.list(Zoi.string())})
  @type unsubscribe_by_attributes_request ::
          unquote(Zoi.type_spec(@unsubscribe_by_attributes_request_schema))

  @new_parameters_schema Zoi.map(%{capabilities: Zoi.any()})
  @type new_parameters :: unquote(Zoi.type_spec(@new_parameters_schema))

  @unsubscribe_parameters_schema Zoi.union([Zoi.any(), Zoi.any()])
  @type unsubscribe_parameters :: unquote(Zoi.type_spec(@unsubscribe_parameters_schema))

  @status_result_schema Zoi.map(%{ready: Zoi.boolean(), message: Zoi.string()})
  @type status_result :: unquote(Zoi.type_spec(@status_result_schema))

  @new_result_schema Zoi.map(%{
                       session_id: Zoi.string(),
                       capabilities:
                         Zoi.map(%{
                           accept_insecure_certs: Zoi.boolean(),
                           browser_name: Zoi.string(),
                           browser_version: Zoi.string(),
                           platform_name: Zoi.string(),
                           set_window_rect: Zoi.boolean(),
                           user_agent: Zoi.string(),
                           proxy: Zoi.any() |> Zoi.optional(),
                           unhandled_prompt_behavior: Zoi.any() |> Zoi.optional(),
                           web_socket_url: Zoi.string() |> Zoi.optional()
                         })
                     })
  @type new_result :: unquote(Zoi.type_spec(@new_result_schema))

  @end_result_schema Zoi.any()
  @type end_result :: unquote(Zoi.type_spec(@end_result_schema))

  @subscribe_result_schema Zoi.map(%{subscription: Zoi.any()})
  @type subscribe_result :: unquote(Zoi.type_spec(@subscribe_result_schema))

  @unsubscribe_result_schema Zoi.any()
  @type unsubscribe_result :: unquote(Zoi.type_spec(@unsubscribe_result_schema))

  @doc "Returns the Zoi schema for `capabilities_request`."
  def capabilities_request, do: @capabilities_request_schema

  @doc "Returns the Zoi schema for `capability_request`."
  def capability_request, do: @capability_request_schema

  @doc "Returns the Zoi schema for `proxy_configuration`."
  def proxy_configuration, do: @proxy_configuration_schema

  @doc "Returns the Zoi schema for `autodetect_proxy_configuration`."
  def autodetect_proxy_configuration, do: @autodetect_proxy_configuration_schema

  @doc "Returns the Zoi schema for `direct_proxy_configuration`."
  def direct_proxy_configuration, do: @direct_proxy_configuration_schema

  @doc "Returns the Zoi schema for `manual_proxy_configuration`."
  def manual_proxy_configuration, do: @manual_proxy_configuration_schema

  @doc "Returns the Zoi schema for `socks_proxy_configuration`."
  def socks_proxy_configuration, do: @socks_proxy_configuration_schema

  @doc "Returns the Zoi schema for `pac_proxy_configuration`."
  def pac_proxy_configuration, do: @pac_proxy_configuration_schema

  @doc "Returns the Zoi schema for `system_proxy_configuration`."
  def system_proxy_configuration, do: @system_proxy_configuration_schema

  @doc "Returns the Zoi schema for `user_prompt_handler`."
  def user_prompt_handler, do: @user_prompt_handler_schema

  @doc "Returns the Zoi schema for `user_prompt_handler_type`."
  def user_prompt_handler_type, do: @user_prompt_handler_type_schema

  @doc "Returns the Zoi schema for `subscription`."
  def subscription, do: @subscription_schema

  @doc "Returns the Zoi schema for `subscribe_parameters`."
  def subscribe_parameters, do: @subscribe_parameters_schema

  @doc "Returns the Zoi schema for `unsubscribe_by_id_request`."
  def unsubscribe_by_id_request, do: @unsubscribe_by_id_request_schema

  @doc "Returns the Zoi schema for `unsubscribe_by_attributes_request`."
  def unsubscribe_by_attributes_request, do: @unsubscribe_by_attributes_request_schema

  @doc "Returns the Zoi schema for `new_parameters`."
  def new_parameters, do: @new_parameters_schema

  @doc "Returns the Zoi schema for `unsubscribe_parameters`."
  def unsubscribe_parameters, do: @unsubscribe_parameters_schema

  @doc "Returns the Zoi schema for `status_result`."
  def status_result, do: @status_result_schema

  @doc "Returns the Zoi schema for `new_result`."
  def new_result, do: @new_result_schema

  @doc "Returns the Zoi schema for `end_result`."
  def end_result, do: @end_result_schema

  @doc "Returns the Zoi schema for `subscribe_result`."
  def subscribe_result, do: @subscribe_result_schema

  @doc "Returns the Zoi schema for `unsubscribe_result`."
  def unsubscribe_result, do: @unsubscribe_result_schema
end
