# Generated by mix bibbidi.gen — do not edit manually
defmodule Bibbidi.Types.Storage do
  @moduledoc """
  Type definitions and Zoi schemas for the `storage` module of the WebDriver BiDi protocol.

  Each type has:
  - A `@type` spec derived from the Zoi schema (for Dialyzer)
  - A function returning the Zoi schema (for runtime validation)
  """

  @partition_key_schema Zoi.map(%{
                          user_context: Zoi.string() |> Zoi.optional(),
                          source_origin: Zoi.string() |> Zoi.optional()
                        })
  @type partition_key :: unquote(Zoi.type_spec(@partition_key_schema))

  @cookie_filter_schema Zoi.map(%{
                          name: Zoi.string() |> Zoi.optional(),
                          value: Zoi.any() |> Zoi.optional(),
                          domain: Zoi.string() |> Zoi.optional(),
                          path: Zoi.string() |> Zoi.optional(),
                          size: Zoi.any() |> Zoi.optional(),
                          http_only: Zoi.boolean() |> Zoi.optional(),
                          secure: Zoi.boolean() |> Zoi.optional(),
                          same_site: Zoi.any() |> Zoi.optional(),
                          expiry: Zoi.any() |> Zoi.optional()
                        })
  @type cookie_filter :: unquote(Zoi.type_spec(@cookie_filter_schema))

  @browsing_context_partition_descriptor_schema Zoi.map(%{type: Zoi.string(), context: Zoi.any()})
  @type browsing_context_partition_descriptor ::
          unquote(Zoi.type_spec(@browsing_context_partition_descriptor_schema))

  @storage_key_partition_descriptor_schema Zoi.map(%{
                                             type: Zoi.string(),
                                             user_context: Zoi.string() |> Zoi.optional(),
                                             source_origin: Zoi.string() |> Zoi.optional()
                                           })
  @type storage_key_partition_descriptor ::
          unquote(Zoi.type_spec(@storage_key_partition_descriptor_schema))

  @partition_descriptor_schema Zoi.union([Zoi.any(), Zoi.any()])
  @type partition_descriptor :: unquote(Zoi.type_spec(@partition_descriptor_schema))

  @get_cookies_parameters_schema Zoi.map(%{
                                   filter: Zoi.any() |> Zoi.optional(),
                                   partition: Zoi.any() |> Zoi.optional()
                                 })
  @type get_cookies_parameters :: unquote(Zoi.type_spec(@get_cookies_parameters_schema))

  @partial_cookie_schema Zoi.map(%{
                           name: Zoi.string(),
                           value: Zoi.any(),
                           domain: Zoi.string(),
                           path: Zoi.string() |> Zoi.optional(),
                           http_only: Zoi.boolean() |> Zoi.optional(),
                           secure: Zoi.boolean() |> Zoi.optional(),
                           same_site: Zoi.any() |> Zoi.optional(),
                           expiry: Zoi.any() |> Zoi.optional()
                         })
  @type partial_cookie :: unquote(Zoi.type_spec(@partial_cookie_schema))

  @set_cookie_parameters_schema Zoi.map(%{
                                  cookie: Zoi.any(),
                                  partition: Zoi.any() |> Zoi.optional()
                                })
  @type set_cookie_parameters :: unquote(Zoi.type_spec(@set_cookie_parameters_schema))

  @delete_cookies_parameters_schema Zoi.map(%{
                                      filter: Zoi.any() |> Zoi.optional(),
                                      partition: Zoi.any() |> Zoi.optional()
                                    })
  @type delete_cookies_parameters :: unquote(Zoi.type_spec(@delete_cookies_parameters_schema))

  @get_cookies_result_schema Zoi.map(%{cookies: Zoi.list(Zoi.any()), partition_key: Zoi.any()})
  @type get_cookies_result :: unquote(Zoi.type_spec(@get_cookies_result_schema))

  @set_cookie_result_schema Zoi.map(%{partition_key: Zoi.any()})
  @type set_cookie_result :: unquote(Zoi.type_spec(@set_cookie_result_schema))

  @delete_cookies_result_schema Zoi.map(%{partition_key: Zoi.any()})
  @type delete_cookies_result :: unquote(Zoi.type_spec(@delete_cookies_result_schema))

  @doc "Returns the Zoi schema for `partition_key`."
  def partition_key, do: @partition_key_schema

  @doc "Returns the Zoi schema for `cookie_filter`."
  def cookie_filter, do: @cookie_filter_schema

  @doc "Returns the Zoi schema for `browsing_context_partition_descriptor`."
  def browsing_context_partition_descriptor, do: @browsing_context_partition_descriptor_schema

  @doc "Returns the Zoi schema for `storage_key_partition_descriptor`."
  def storage_key_partition_descriptor, do: @storage_key_partition_descriptor_schema

  @doc "Returns the Zoi schema for `partition_descriptor`."
  def partition_descriptor, do: @partition_descriptor_schema

  @doc "Returns the Zoi schema for `get_cookies_parameters`."
  def get_cookies_parameters, do: @get_cookies_parameters_schema

  @doc "Returns the Zoi schema for `partial_cookie`."
  def partial_cookie, do: @partial_cookie_schema

  @doc "Returns the Zoi schema for `set_cookie_parameters`."
  def set_cookie_parameters, do: @set_cookie_parameters_schema

  @doc "Returns the Zoi schema for `delete_cookies_parameters`."
  def delete_cookies_parameters, do: @delete_cookies_parameters_schema

  @doc "Returns the Zoi schema for `get_cookies_result`."
  def get_cookies_result, do: @get_cookies_result_schema

  @doc "Returns the Zoi schema for `set_cookie_result`."
  def set_cookie_result, do: @set_cookie_result_schema

  @doc "Returns the Zoi schema for `delete_cookies_result`."
  def delete_cookies_result, do: @delete_cookies_result_schema
end
