# Generated by mix bibbidi.gen — do not edit manually
defmodule Bibbidi.Types.WebExtension do
  @moduledoc """
  Type definitions and Zoi schemas for the `webExtension` module of the WebDriver BiDi protocol.

  Each type has:
  - A `@type` spec derived from the Zoi schema (for Dialyzer)
  - A function returning the Zoi schema (for runtime validation)
  """

  @extension_schema Zoi.string()
  @type extension :: unquote(Zoi.type_spec(@extension_schema))

  @install_parameters_schema Zoi.map(%{extension_data: Zoi.any()})
  @type install_parameters :: unquote(Zoi.type_spec(@install_parameters_schema))

  @extension_data_schema Zoi.union([Zoi.any(), Zoi.any(), Zoi.any()])
  @type extension_data :: unquote(Zoi.type_spec(@extension_data_schema))

  @extension_path_schema Zoi.map(%{type: Zoi.string(), path: Zoi.string()})
  @type extension_path :: unquote(Zoi.type_spec(@extension_path_schema))

  @extension_archive_path_schema Zoi.map(%{type: Zoi.string(), path: Zoi.string()})
  @type extension_archive_path :: unquote(Zoi.type_spec(@extension_archive_path_schema))

  @extension_base64encoded_schema Zoi.map(%{type: Zoi.string(), value: Zoi.string()})
  @type extension_base64encoded :: unquote(Zoi.type_spec(@extension_base64encoded_schema))

  @uninstall_parameters_schema Zoi.map(%{extension: Zoi.any()})
  @type uninstall_parameters :: unquote(Zoi.type_spec(@uninstall_parameters_schema))

  @install_result_schema Zoi.map(%{extension: Zoi.any()})
  @type install_result :: unquote(Zoi.type_spec(@install_result_schema))

  @uninstall_result_schema Zoi.any()
  @type uninstall_result :: unquote(Zoi.type_spec(@uninstall_result_schema))

  @doc "Returns the Zoi schema for `extension`."
  def extension, do: @extension_schema

  @doc "Returns the Zoi schema for `install_parameters`."
  def install_parameters, do: @install_parameters_schema

  @doc "Returns the Zoi schema for `extension_data`."
  def extension_data, do: @extension_data_schema

  @doc "Returns the Zoi schema for `extension_path`."
  def extension_path, do: @extension_path_schema

  @doc "Returns the Zoi schema for `extension_archive_path`."
  def extension_archive_path, do: @extension_archive_path_schema

  @doc "Returns the Zoi schema for `extension_base64encoded`."
  def extension_base64encoded, do: @extension_base64encoded_schema

  @doc "Returns the Zoi schema for `uninstall_parameters`."
  def uninstall_parameters, do: @uninstall_parameters_schema

  @doc "Returns the Zoi schema for `install_result`."
  def install_result, do: @install_result_schema

  @doc "Returns the Zoi schema for `uninstall_result`."
  def uninstall_result, do: @uninstall_result_schema
end
