#!/usr/bin/env bash
#
# PreToolUse hook: refuse to hand-edit generated files.
#
# Bibbidi's command/type modules are generated by `mix bibbidi.gen` and carry the marker
# "Generated by mix bibbidi.gen" as their FIRST line. Editing them is pointless — the next
# regen clobbers the change — so block Edit/Write to such files and redirect to the real
# source (the CDDL spec or dev/cddl generator) + the regen-codegen skill.
#
# The marker is checked on line 1 only, so documentation that merely quotes the marker
# (this script, AGENTS.md, the skill files) is not affected.
#
set -uo pipefail

input="$(cat)"

fp="$(printf '%s' "$input" | jq -r '.tool_input.file_path // empty' 2>/dev/null)"
[ -z "$fp" ] && exit 0
# New file (nothing on disk yet) — nothing generated to protect.
[ -f "$fp" ] || exit 0

if head -n1 "$fp" 2>/dev/null | grep -q "Generated by mix bibbidi.gen"; then
  rel="${fp#"${CLAUDE_PROJECT_DIR:-}"/}"
  {
    echo "Refusing to edit $rel — it is generated by 'mix bibbidi.gen' and will be overwritten on the next regen."
    echo "Change the source instead, then regenerate (regen-codegen skill):"
    echo "  - CDDL spec:      packages/bibbidi/priv/cddl/{remote,local}.cddl"
    echo "  - code generator: packages/bibbidi/dev/cddl/{generator,parser,utils}.ex"
    echo "See the edit-codegen skill for the full workflow."
  } >&2
  exit 2
fi
exit 0
