# Generated by mix bibbidi.gen — do not edit manually
defmodule Bibbidi.Commands.Browser do
  @moduledoc """
  Command builders for the `browser` module of the WebDriver BiDi protocol.
  """

  alias Bibbidi.Connection

  @doc "Executes the `browser.close` command."
  @spec close(GenServer.server()) :: {:ok, map()} | {:error, term()}
  def close(conn) do
    Connection.execute(conn, %__MODULE__.Close{})
  end

  @doc "Executes the `browser.createUserContext` command."
  @spec create_user_context(GenServer.server(), keyword()) :: {:ok, map()} | {:error, term()}
  def create_user_context(conn, opts \\ []) do
    Connection.execute(conn, %__MODULE__.CreateUserContext{
      accept_insecure_certs: opts[:accept_insecure_certs],
      proxy: opts[:proxy],
      unhandled_prompt_behavior: opts[:unhandled_prompt_behavior]
    })
  end

  @doc "Executes the `browser.getClientWindows` command."
  @spec get_client_windows(GenServer.server()) :: {:ok, map()} | {:error, term()}
  def get_client_windows(conn) do
    Connection.execute(conn, %__MODULE__.GetClientWindows{})
  end

  @doc "Executes the `browser.getUserContexts` command."
  @spec get_user_contexts(GenServer.server()) :: {:ok, map()} | {:error, term()}
  def get_user_contexts(conn) do
    Connection.execute(conn, %__MODULE__.GetUserContexts{})
  end

  @doc "Executes the `browser.removeUserContext` command."
  @spec remove_user_context(GenServer.server(), term()) :: {:ok, map()} | {:error, term()}
  def remove_user_context(conn, user_context) do
    Connection.execute(conn, %__MODULE__.RemoveUserContext{
      user_context: user_context
    })
  end

  @doc "Executes the `browser.setClientWindowState` command."
  @spec set_client_window_state(GenServer.server(), term()) :: {:ok, map()} | {:error, term()}
  def set_client_window_state(conn, client_window) do
    Connection.execute(conn, %__MODULE__.SetClientWindowState{
      client_window: client_window
    })
  end

  @doc "Executes the `browser.setDownloadBehavior` command."
  @spec set_download_behavior(GenServer.server(), term(), keyword()) ::
          {:ok, map()} | {:error, term()}
  def set_download_behavior(conn, download_behavior, opts \\ []) do
    Connection.execute(conn, %__MODULE__.SetDownloadBehavior{
      download_behavior: download_behavior,
      user_contexts: opts[:user_contexts]
    })
  end
end
