# Generated by mix bibbidi.gen — do not edit manually
defmodule Bibbidi.Commands.Input do
  @moduledoc """
  Command builders for the `input` module of the WebDriver BiDi protocol.
  """

  alias Bibbidi.Connection

  @doc "Executes the `input.performActions` command."
  @spec perform_actions(GenServer.server(), term(), term()) :: {:ok, map()} | {:error, term()}
  def perform_actions(conn, context, actions) do
    Connection.execute(conn, %__MODULE__.PerformActions{
      context: context,
      actions: actions
    })
  end

  @doc "Executes the `input.releaseActions` command."
  @spec release_actions(GenServer.server(), term()) :: {:ok, map()} | {:error, term()}
  def release_actions(conn, context) do
    Connection.execute(conn, %__MODULE__.ReleaseActions{
      context: context
    })
  end

  @doc "Executes the `input.setFiles` command."
  @spec set_files(GenServer.server(), term(), term(), term()) :: {:ok, map()} | {:error, term()}
  def set_files(conn, context, element, files) do
    Connection.execute(conn, %__MODULE__.SetFiles{
      context: context,
      element: element,
      files: files
    })
  end

  @doc "Executes the `input.fileDialogOpened` command."
  @spec file_dialog_opened(GenServer.server(), term(), term(), keyword()) ::
          {:ok, map()} | {:error, term()}
  def file_dialog_opened(conn, context, multiple, opts \\ []) do
    Connection.execute(conn, %__MODULE__.FileDialogOpened{
      context: context,
      multiple: multiple,
      user_context: opts[:user_context],
      element: opts[:element]
    })
  end
end
