# Generated by mix bibbidi.gen — do not edit manually
defmodule Bibbidi.Commands.Network do
  @moduledoc """
  Command builders for the `network` module of the WebDriver BiDi protocol.
  """

  alias Bibbidi.Connection

  @doc "Executes the `network.addDataCollector` command."
  @spec add_data_collector(GenServer.server(), term(), term(), keyword()) ::
          {:ok, map()} | {:error, term()}
  def add_data_collector(conn, data_types, max_encoded_data_size, opts \\ []) do
    Connection.execute(conn, %__MODULE__.AddDataCollector{
      data_types: data_types,
      max_encoded_data_size: max_encoded_data_size,
      collector_type: opts[:collector_type],
      contexts: opts[:contexts],
      user_contexts: opts[:user_contexts]
    })
  end

  @doc "Executes the `network.addIntercept` command."
  @spec add_intercept(GenServer.server(), term(), keyword()) :: {:ok, map()} | {:error, term()}
  def add_intercept(conn, phases, opts \\ []) do
    Connection.execute(conn, %__MODULE__.AddIntercept{
      phases: phases,
      contexts: opts[:contexts],
      url_patterns: opts[:url_patterns]
    })
  end

  @doc "Executes the `network.continueRequest` command."
  @spec continue_request(GenServer.server(), term(), keyword()) :: {:ok, map()} | {:error, term()}
  def continue_request(conn, request, opts \\ []) do
    Connection.execute(conn, %__MODULE__.ContinueRequest{
      request: request,
      body: opts[:body],
      cookies: opts[:cookies],
      headers: opts[:headers],
      method: opts[:method],
      url: opts[:url]
    })
  end

  @doc "Executes the `network.continueResponse` command."
  @spec continue_response(GenServer.server(), term(), keyword()) ::
          {:ok, map()} | {:error, term()}
  def continue_response(conn, request, opts \\ []) do
    Connection.execute(conn, %__MODULE__.ContinueResponse{
      request: request,
      cookies: opts[:cookies],
      credentials: opts[:credentials],
      headers: opts[:headers],
      reason_phrase: opts[:reason_phrase],
      status_code: opts[:status_code]
    })
  end

  @doc "Executes the `network.continueWithAuth` command."
  @spec continue_with_auth(GenServer.server(), term()) :: {:ok, map()} | {:error, term()}
  def continue_with_auth(conn, request) do
    Connection.execute(conn, %__MODULE__.ContinueWithAuth{
      request: request
    })
  end

  @doc "Executes the `network.disownData` command."
  @spec disown_data(GenServer.server(), term(), term(), term()) :: {:ok, map()} | {:error, term()}
  def disown_data(conn, data_type, collector, request) do
    Connection.execute(conn, %__MODULE__.DisownData{
      data_type: data_type,
      collector: collector,
      request: request
    })
  end

  @doc "Executes the `network.failRequest` command."
  @spec fail_request(GenServer.server(), term()) :: {:ok, map()} | {:error, term()}
  def fail_request(conn, request) do
    Connection.execute(conn, %__MODULE__.FailRequest{
      request: request
    })
  end

  @doc "Executes the `network.getData` command."
  @spec get_data(GenServer.server(), term(), term(), keyword()) :: {:ok, map()} | {:error, term()}
  def get_data(conn, data_type, request, opts \\ []) do
    Connection.execute(conn, %__MODULE__.GetData{
      data_type: data_type,
      request: request,
      collector: opts[:collector],
      disown: opts[:disown]
    })
  end

  @doc "Executes the `network.provideResponse` command."
  @spec provide_response(GenServer.server(), term(), keyword()) :: {:ok, map()} | {:error, term()}
  def provide_response(conn, request, opts \\ []) do
    Connection.execute(conn, %__MODULE__.ProvideResponse{
      request: request,
      body: opts[:body],
      cookies: opts[:cookies],
      headers: opts[:headers],
      reason_phrase: opts[:reason_phrase],
      status_code: opts[:status_code]
    })
  end

  @doc "Executes the `network.removeDataCollector` command."
  @spec remove_data_collector(GenServer.server(), term()) :: {:ok, map()} | {:error, term()}
  def remove_data_collector(conn, collector) do
    Connection.execute(conn, %__MODULE__.RemoveDataCollector{
      collector: collector
    })
  end

  @doc "Executes the `network.removeIntercept` command."
  @spec remove_intercept(GenServer.server(), term()) :: {:ok, map()} | {:error, term()}
  def remove_intercept(conn, intercept) do
    Connection.execute(conn, %__MODULE__.RemoveIntercept{
      intercept: intercept
    })
  end

  @doc "Executes the `network.setCacheBehavior` command."
  @spec set_cache_behavior(GenServer.server(), term(), keyword()) ::
          {:ok, map()} | {:error, term()}
  def set_cache_behavior(conn, cache_behavior, opts \\ []) do
    Connection.execute(conn, %__MODULE__.SetCacheBehavior{
      cache_behavior: cache_behavior,
      contexts: opts[:contexts]
    })
  end

  @doc "Executes the `network.setExtraHeaders` command."
  @spec set_extra_headers(GenServer.server(), term(), keyword()) ::
          {:ok, map()} | {:error, term()}
  def set_extra_headers(conn, headers, opts \\ []) do
    Connection.execute(conn, %__MODULE__.SetExtraHeaders{
      headers: headers,
      contexts: opts[:contexts],
      user_contexts: opts[:user_contexts]
    })
  end
end
