# Generated by mix bibbidi.gen — do not edit manually
defmodule Bibbidi.Commands.Script do
  @moduledoc """
  Command builders for the `script` module of the WebDriver BiDi protocol.
  """

  alias Bibbidi.Connection

  @doc "Executes the `script.addPreloadScript` command."
  @spec add_preload_script(GenServer.server(), term(), keyword()) ::
          {:ok, map()} | {:error, term()}
  def add_preload_script(conn, function_declaration, opts \\ []) do
    Connection.execute(conn, %__MODULE__.AddPreloadScript{
      function_declaration: function_declaration,
      arguments: opts[:arguments],
      contexts: opts[:contexts],
      user_contexts: opts[:user_contexts],
      sandbox: opts[:sandbox]
    })
  end

  @doc "Executes the `script.disown` command."
  @spec disown(GenServer.server(), term(), term()) :: {:ok, map()} | {:error, term()}
  def disown(conn, handles, target) do
    Connection.execute(conn, %__MODULE__.Disown{
      handles: handles,
      target: target
    })
  end

  @doc "Executes the `script.callFunction` command."
  @spec call_function(GenServer.server(), term(), term(), term(), keyword()) ::
          {:ok, map()} | {:error, term()}
  def call_function(conn, function_declaration, await_promise, target, opts \\ []) do
    Connection.execute(conn, %__MODULE__.CallFunction{
      function_declaration: function_declaration,
      await_promise: await_promise,
      target: target,
      arguments: opts[:arguments],
      result_ownership: opts[:result_ownership],
      serialization_options: opts[:serialization_options],
      this: opts[:this],
      user_activation: opts[:user_activation]
    })
  end

  @doc "Executes the `script.evaluate` command."
  @spec evaluate(GenServer.server(), term(), term(), term(), keyword()) ::
          {:ok, map()} | {:error, term()}
  def evaluate(conn, expression, target, await_promise, opts \\ []) do
    Connection.execute(conn, %__MODULE__.Evaluate{
      expression: expression,
      target: target,
      await_promise: await_promise,
      result_ownership: opts[:result_ownership],
      serialization_options: opts[:serialization_options],
      user_activation: opts[:user_activation]
    })
  end

  @doc "Executes the `script.getRealms` command."
  @spec get_realms(GenServer.server(), keyword()) :: {:ok, map()} | {:error, term()}
  def get_realms(conn, opts \\ []) do
    Connection.execute(conn, %__MODULE__.GetRealms{
      context: opts[:context],
      type: opts[:type]
    })
  end

  @doc "Executes the `script.removePreloadScript` command."
  @spec remove_preload_script(GenServer.server(), term()) :: {:ok, map()} | {:error, term()}
  def remove_preload_script(conn, script) do
    Connection.execute(conn, %__MODULE__.RemovePreloadScript{
      script: script
    })
  end
end
