# Generated by mix bibbidi.gen — do not edit manually
defmodule Bibbidi.Commands.Session do
  @moduledoc """
  Command builders for the `session` module of the WebDriver BiDi protocol.

  See also `Bibbidi.Session` for a higher-level convenience API.
  """

  alias Bibbidi.Connection

  @doc "Executes the `session.status` command."
  @spec status(GenServer.server()) :: {:ok, map()} | {:error, term()}
  def status(conn) do
    Connection.execute(conn, %__MODULE__.Status{})
  end

  @doc "Executes the `session.new` command."
  @spec new(GenServer.server(), term()) :: {:ok, map()} | {:error, term()}
  def new(conn, capabilities) do
    Connection.execute(conn, %__MODULE__.New{
      capabilities: capabilities
    })
  end

  @doc "Executes the `session.end` command."
  @spec session_end(GenServer.server()) :: {:ok, map()} | {:error, term()}
  def session_end(conn) do
    Connection.execute(conn, %__MODULE__.End{})
  end

  @doc "Executes the `session.subscribe` command."
  @spec subscribe(GenServer.server(), term(), keyword()) :: {:ok, map()} | {:error, term()}
  def subscribe(conn, events, opts \\ []) do
    Connection.execute(conn, %__MODULE__.Subscribe{
      events: events,
      contexts: opts[:contexts],
      user_contexts: opts[:user_contexts]
    })
  end

  @doc "Executes the `session.unsubscribe` command."
  @spec unsubscribe(GenServer.server(), keyword()) :: {:ok, map()} | {:error, term()}
  def unsubscribe(conn, opts \\ []) do
    Connection.execute(conn, %__MODULE__.Unsubscribe{
      events: opts[:events],
      subscriptions: opts[:subscriptions]
    })
  end
end
