# Generated by mix bibbidi.gen — do not edit manually
defmodule Bibbidi.Commands.Storage do
  @moduledoc """
  Command builders for the `storage` module of the WebDriver BiDi protocol.
  """

  alias Bibbidi.Connection

  @doc "Executes the `storage.getCookies` command."
  @spec get_cookies(GenServer.server(), keyword()) :: {:ok, map()} | {:error, term()}
  def get_cookies(conn, opts \\ []) do
    Connection.execute(conn, %__MODULE__.GetCookies{
      filter: opts[:filter],
      partition: opts[:partition]
    })
  end

  @doc "Executes the `storage.setCookie` command."
  @spec set_cookie(GenServer.server(), term(), keyword()) :: {:ok, map()} | {:error, term()}
  def set_cookie(conn, cookie, opts \\ []) do
    Connection.execute(conn, %__MODULE__.SetCookie{
      cookie: cookie,
      partition: opts[:partition]
    })
  end

  @doc "Executes the `storage.deleteCookies` command."
  @spec delete_cookies(GenServer.server(), keyword()) :: {:ok, map()} | {:error, term()}
  def delete_cookies(conn, opts \\ []) do
    Connection.execute(conn, %__MODULE__.DeleteCookies{
      filter: opts[:filter],
      partition: opts[:partition]
    })
  end
end
