# Generated by mix bibbidi.gen — do not edit manually
defmodule Bibbidi.Commands.WebExtension do
  @moduledoc """
  Command builders for the `webExtension` module of the WebDriver BiDi protocol.
  """

  alias Bibbidi.Connection
  alias __MODULE__.Install
  alias __MODULE__.Uninstall

  @doc "Executes the `webExtension.install` command."
  @spec install(GenServer.server(), term()) :: {:ok, Install.result()} | {:error, term()}
  def install(conn, extension_data) do
    Connection.execute(conn, struct!(Install, [{:extension_data, extension_data}]))
  end

  @doc "Executes the `webExtension.uninstall` command."
  @spec uninstall(GenServer.server(), term()) :: {:ok, Uninstall.result()} | {:error, term()}
  def uninstall(conn, extension) do
    Connection.execute(conn, struct!(Uninstall, [{:extension, extension}]))
  end
end
