# Generated by mix bibbidi.gen — do not edit manually
defmodule Bibbidi.Commands.Session.Unsubscribe do
  @moduledoc """
  Command struct for `session.unsubscribe`.

  [WebDriver BiDi Spec](https://w3c.github.io/webdriver-bidi/#command-session-unsubscribe)
  ## Fields

  - `events` - list of `String.t()` (optional)
  - `subscriptions` - list of `t:Bibbidi.Types.Session.Subscription.t/0` (optional)

  """

  @derive Bibbidi.Telemetry.Metadata
  @schema Zoi.struct(__MODULE__, %{
            events: Zoi.list(Zoi.string()) |> Zoi.optional(),
            subscriptions:
              Zoi.list(Bibbidi.Types.Session.Subscription.schema()) |> Zoi.optional(),
            meta: Zoi.any() |> Zoi.optional()
          })
  @opts_schema Zoi.keyword(
                 events: Zoi.list(Zoi.string()) |> Zoi.optional(),
                 subscriptions: Zoi.list(Zoi.any()) |> Zoi.optional()
               )
  @result_schema Zoi.map(Zoi.string(), Zoi.any())

  @type t :: unquote(Zoi.type_spec(@schema))
  @type opts :: unquote(Zoi.type_spec(@opts_schema))
  @type result :: unquote(Zoi.type_spec(@result_schema))

  @enforce_keys Zoi.Struct.enforce_keys(@schema)
  defstruct Zoi.Struct.struct_fields(@schema)

  @doc "Returns the Zoi schema for this command struct."
  def schema, do: @schema

  @doc "Returns the Zoi schema for the keyword options."
  def opts_schema, do: @opts_schema

  @doc "Returns the Zoi schema for the result type."
  def result_schema, do: @result_schema

  defimpl Bibbidi.Encodable do
    def method(_), do: "session.unsubscribe"

    def params(cmd) do
      optional = [
        {:events, cmd.events},
        {:subscriptions, cmd.subscriptions}
      ]

      Enum.reduce(optional, %{}, fn
        {_key, nil}, acc -> acc
        {key, value}, acc -> Map.put(acc, key, value)
      end)
    end
  end
end
