# Generated by mix bibbidi.gen — do not edit manually
defmodule Bibbidi.Commands.Input.FileDialogOpened do
  @moduledoc """
  Command struct for `input.fileDialogOpened`.

  [WebDriver BiDi Spec](https://w3c.github.io/webdriver-bidi/#command-input-fileDialogOpened)
  ## Fields

  - `context` - `t:Bibbidi.Types.BrowsingContext.t/0` (required)
  - `multiple` - `boolean()` (required)
  - `user_context` - `t:Bibbidi.Types.Browser.UserContext.t/0` (optional)
  - `element` - `t:Bibbidi.Types.Script.SharedReference.t/0` (optional)

  """

  @derive Bibbidi.Telemetry.Metadata
  @schema Zoi.struct(__MODULE__, %{
            context: Bibbidi.Types.BrowsingContext.schema(),
            multiple: Zoi.boolean(),
            user_context: Bibbidi.Types.Browser.UserContext.schema() |> Zoi.optional(),
            element: Bibbidi.Types.Script.SharedReference.schema() |> Zoi.optional(),
            meta: Zoi.any() |> Zoi.optional()
          })
  @opts_schema Zoi.keyword(
                 user_context: Zoi.any() |> Zoi.optional(),
                 element: Zoi.any() |> Zoi.optional()
               )
  @result_schema Zoi.map(Zoi.string(), Zoi.any())

  @type t :: unquote(Zoi.type_spec(@schema))
  @type opts :: unquote(Zoi.type_spec(@opts_schema))
  @type result :: unquote(Zoi.type_spec(@result_schema))

  @enforce_keys Zoi.Struct.enforce_keys(@schema)
  defstruct Zoi.Struct.struct_fields(@schema)

  @doc "Returns the Zoi schema for this command struct."
  def schema, do: @schema

  @doc "Returns the Zoi schema for the keyword options."
  def opts_schema, do: @opts_schema

  @doc "Returns the Zoi schema for the result type."
  def result_schema, do: @result_schema

  defimpl Bibbidi.Encodable do
    def method(_), do: "input.fileDialogOpened"

    def params(cmd) do
      optional = [
        {:userContext, cmd.user_context},
        {:element, cmd.element}
      ]

      Enum.reduce(optional, %{context: cmd.context, multiple: cmd.multiple}, fn
        {_key, nil}, acc -> acc
        {key, value}, acc -> Map.put(acc, key, value)
      end)
    end
  end
end
