# Generated by mix bibbidi.gen — do not edit manually
defmodule Bibbidi.Commands.Input.PerformActions do
  @moduledoc """
  Command struct for `input.performActions`.

  [WebDriver BiDi Spec](https://w3c.github.io/webdriver-bidi/#command-input-performActions)
  ## Fields

  - `context` - `t:Bibbidi.Types.BrowsingContext.t/0` (required)
  - `actions` - list of `t:Bibbidi.Types.Input.SourceActions.t/0` (required)

  """

  @derive Bibbidi.Telemetry.Metadata
  @schema Zoi.struct(__MODULE__, %{
            context: Bibbidi.Types.BrowsingContext.schema(),
            actions: Zoi.list(Bibbidi.Types.Input.SourceActions.schema()),
            meta: Zoi.any() |> Zoi.optional()
          })
  @opts_schema Zoi.keyword([])
  @result_schema Zoi.map(Zoi.string(), Zoi.any())

  @type t :: unquote(Zoi.type_spec(@schema))
  @type opts :: unquote(Zoi.type_spec(@opts_schema))
  @type result :: unquote(Zoi.type_spec(@result_schema))

  @enforce_keys Zoi.Struct.enforce_keys(@schema)
  defstruct Zoi.Struct.struct_fields(@schema)

  @doc "Returns the Zoi schema for this command struct."
  def schema, do: @schema

  @doc "Returns the Zoi schema for the keyword options."
  def opts_schema, do: @opts_schema

  @doc "Returns the Zoi schema for the result type."
  def result_schema, do: @result_schema

  defimpl Bibbidi.Encodable do
    def method(_), do: "input.performActions"

    def params(cmd), do: %{context: cmd.context, actions: cmd.actions}
  end
end
