# Generated by mix bibbidi.gen — do not edit manually
defmodule Bibbidi.Types.Session.CapabilitiesRequest do
  @moduledoc """
  `session.CapabilitiesRequest`

  ## Fields

  - `always_match` - `t:Bibbidi.Types.Session.CapabilityRequest.t/0` (optional)
  - `first_match` - list of `t:Bibbidi.Types.Session.CapabilityRequest.t/0` (optional)
  """

  @schema Zoi.map(%{
            always_match:
              Zoi.lazy({Bibbidi.Types.Session.CapabilityRequest, :schema, []}) |> Zoi.optional(),
            first_match:
              Zoi.list(Zoi.lazy({Bibbidi.Types.Session.CapabilityRequest, :schema, []}))
              |> Zoi.optional()
          })
  @type t :: %{
          always_match: Bibbidi.Types.Session.CapabilityRequest.t() | nil,
          first_match: [Bibbidi.Types.Session.CapabilityRequest.t()] | nil
        }

  @doc "Returns the Zoi schema for this type."
  def schema, do: @schema
end
