# Generated by mix bibbidi.gen — do not edit manually
defmodule Bibbidi.Types.Session.CapabilityRequest do
  @moduledoc """
  `session.CapabilityRequest`

  ## Fields

  - `accept_insecure_certs` - `boolean()` (optional)
  - `browser_name` - `String.t()` (optional)
  - `browser_version` - `String.t()` (optional)
  - `platform_name` - `String.t()` (optional)
  - `proxy` - `t:Bibbidi.Types.Session.ProxyConfiguration.t/0` (optional)
  - `unhandled_prompt_behavior` - `t:Bibbidi.Types.Session.UserPromptHandler.t/0` (optional)
  """

  @schema Zoi.map(%{
            accept_insecure_certs: Zoi.boolean() |> Zoi.optional(),
            browser_name: Zoi.string() |> Zoi.optional(),
            browser_version: Zoi.string() |> Zoi.optional(),
            platform_name: Zoi.string() |> Zoi.optional(),
            proxy:
              Zoi.lazy({Bibbidi.Types.Session.ProxyConfiguration, :schema, []}) |> Zoi.optional(),
            unhandled_prompt_behavior:
              Zoi.lazy({Bibbidi.Types.Session.UserPromptHandler, :schema, []}) |> Zoi.optional()
          })
  @type t :: %{
          accept_insecure_certs: boolean() | nil,
          browser_name: String.t() | nil,
          browser_version: String.t() | nil,
          platform_name: String.t() | nil,
          proxy: Bibbidi.Types.Session.ProxyConfiguration.t() | nil,
          unhandled_prompt_behavior: Bibbidi.Types.Session.UserPromptHandler.t() | nil
        }

  @doc "Returns the Zoi schema for this type."
  def schema, do: @schema
end
