# Generated by mix bibbidi.gen — do not edit manually
defmodule Bibbidi.Types.Session.Subscription do
  @moduledoc """
  `session.Subscription`
  """

  @schema Zoi.string()
  @type t :: String.t()

  @doc "Returns the Zoi schema for this type."
  def schema, do: @schema
end
