# Generated by mix bibbidi.gen — do not edit manually
defmodule Bibbidi.Types.Session.UserPromptHandler do
  @moduledoc """
  `session.UserPromptHandler`

  ## Fields

  - `alert` - `t:Bibbidi.Types.Session.UserPromptHandlerType.t/0` (optional)
  - `before_unload` - `t:Bibbidi.Types.Session.UserPromptHandlerType.t/0` (optional)
  - `confirm` - `t:Bibbidi.Types.Session.UserPromptHandlerType.t/0` (optional)
  - `default` - `t:Bibbidi.Types.Session.UserPromptHandlerType.t/0` (optional)
  - `file` - `t:Bibbidi.Types.Session.UserPromptHandlerType.t/0` (optional)
  - `prompt` - `t:Bibbidi.Types.Session.UserPromptHandlerType.t/0` (optional)
  """

  @schema Zoi.map(%{
            alert:
              Zoi.lazy({Bibbidi.Types.Session.UserPromptHandlerType, :schema, []})
              |> Zoi.optional(),
            before_unload:
              Zoi.lazy({Bibbidi.Types.Session.UserPromptHandlerType, :schema, []})
              |> Zoi.optional(),
            confirm:
              Zoi.lazy({Bibbidi.Types.Session.UserPromptHandlerType, :schema, []})
              |> Zoi.optional(),
            default:
              Zoi.lazy({Bibbidi.Types.Session.UserPromptHandlerType, :schema, []})
              |> Zoi.optional(),
            file:
              Zoi.lazy({Bibbidi.Types.Session.UserPromptHandlerType, :schema, []})
              |> Zoi.optional(),
            prompt:
              Zoi.lazy({Bibbidi.Types.Session.UserPromptHandlerType, :schema, []})
              |> Zoi.optional()
          })
  @type t :: %{
          alert: Bibbidi.Types.Session.UserPromptHandlerType.t() | nil,
          before_unload: Bibbidi.Types.Session.UserPromptHandlerType.t() | nil,
          confirm: Bibbidi.Types.Session.UserPromptHandlerType.t() | nil,
          default: Bibbidi.Types.Session.UserPromptHandlerType.t() | nil,
          file: Bibbidi.Types.Session.UserPromptHandlerType.t() | nil,
          prompt: Bibbidi.Types.Session.UserPromptHandlerType.t() | nil
        }

  @doc "Returns the Zoi schema for this type."
  def schema, do: @schema
end
