# Generated by mix bibbidi.gen — do not edit manually
defmodule Bibbidi.Events.Guards do
  @moduledoc """
  Guards for matching BiDi event structs in `handle_info` and `with` clauses.

  `import Bibbidi.Events.Guards` to use these:

      def handle_info(msg, state) when is_bibbidi_event(msg), do: ...
      def handle_info(msg, state) when is_bibbidi_log_event(msg), do: ...
      def handle_info(%Bibbidi.Events.Log.EntryAdded{} = ev, state), do: ...

  `is_bibbidi_event/1` matches any generated event struct AND
  `Bibbidi.Events.Unknown` (the catch-all for events outside the codegen).
  Namespace-specific guards (`is_bibbidi_log_event/1`, etc.) do NOT match
  `Unknown` — use them when you want only events confidently known to belong
  to that BiDi module.
  """

  @doc "True when `msg` is a generated event struct under the `browsingContext` namespace."
  defguard is_bibbidi_browsing_context_event(msg)
           when is_struct(msg, Bibbidi.Events.BrowsingContext.ContextCreated) or
                  is_struct(msg, Bibbidi.Events.BrowsingContext.ContextDestroyed) or
                  is_struct(msg, Bibbidi.Events.BrowsingContext.DomContentLoaded) or
                  is_struct(msg, Bibbidi.Events.BrowsingContext.DownloadEnd) or
                  is_struct(msg, Bibbidi.Events.BrowsingContext.DownloadWillBegin) or
                  is_struct(msg, Bibbidi.Events.BrowsingContext.FragmentNavigated) or
                  is_struct(msg, Bibbidi.Events.BrowsingContext.HistoryUpdated) or
                  is_struct(msg, Bibbidi.Events.BrowsingContext.Load) or
                  is_struct(msg, Bibbidi.Events.BrowsingContext.NavigationAborted) or
                  is_struct(msg, Bibbidi.Events.BrowsingContext.NavigationCommitted) or
                  is_struct(msg, Bibbidi.Events.BrowsingContext.NavigationFailed) or
                  is_struct(msg, Bibbidi.Events.BrowsingContext.NavigationStarted) or
                  is_struct(msg, Bibbidi.Events.BrowsingContext.UserPromptClosed) or
                  is_struct(msg, Bibbidi.Events.BrowsingContext.UserPromptOpened)

  @doc "True when `msg` is a generated event struct under the `input` namespace."
  defguard is_bibbidi_input_event(msg)
           when is_struct(msg, Bibbidi.Events.Input.FileDialogOpened)

  @doc "True when `msg` is a generated event struct under the `log` namespace."
  defguard is_bibbidi_log_event(msg)
           when is_struct(msg, Bibbidi.Events.Log.EntryAdded)

  @doc "True when `msg` is a generated event struct under the `network` namespace."
  defguard is_bibbidi_network_event(msg)
           when is_struct(msg, Bibbidi.Events.Network.AuthRequired) or
                  is_struct(msg, Bibbidi.Events.Network.BeforeRequestSent) or
                  is_struct(msg, Bibbidi.Events.Network.FetchError) or
                  is_struct(msg, Bibbidi.Events.Network.ResponseCompleted) or
                  is_struct(msg, Bibbidi.Events.Network.ResponseStarted)

  @doc "True when `msg` is a generated event struct under the `script` namespace."
  defguard is_bibbidi_script_event(msg)
           when is_struct(msg, Bibbidi.Events.Script.Message) or
                  is_struct(msg, Bibbidi.Events.Script.RealmCreated) or
                  is_struct(msg, Bibbidi.Events.Script.RealmDestroyed)

  @doc """
  True when `msg` is any generated event struct or `%Bibbidi.Events.Unknown{}`.

  Use this as the broad screening guard in handlers that might receive
  non-event messages (timers, monitor refs, custom IPC, etc.).
  """
  defguard is_bibbidi_event(msg)
           when is_bibbidi_browsing_context_event(msg) or
                  is_bibbidi_input_event(msg) or
                  is_bibbidi_log_event(msg) or
                  is_bibbidi_network_event(msg) or
                  is_bibbidi_script_event(msg) or
                  is_struct(msg, Bibbidi.Events.Unknown)
end
