# Generated by mix bibbidi.gen — do not edit manually
defmodule Bibbidi.Types.Input.ElementOrigin do
  @moduledoc """
  `input.ElementOrigin`

  ## Fields

  - `type` - `"element"` (required)
  - `element` - `t:Bibbidi.Types.Script.SharedReference.t/0` (required)
  """

  @schema Zoi.map(%{
            type: Zoi.string(),
            element: Zoi.lazy({Bibbidi.Types.Script.SharedReference, :schema, []})
          })
  @type t :: %{type: String.t(), element: Bibbidi.Types.Script.SharedReference.t()}

  @doc "Returns the Zoi schema for this type."
  def schema, do: @schema
end
