# Generated by mix bibbidi.gen — do not edit manually
defmodule Bibbidi.Types.Input.KeySourceAction do
  @moduledoc """
  `input.KeySourceAction`

  One of:
  - `t:Bibbidi.Types.Input.PauseAction.t/0`
  - `t:Bibbidi.Types.Input.KeyDownAction.t/0`
  - `t:Bibbidi.Types.Input.KeyUpAction.t/0`
  """

  @schema Zoi.union([
            Zoi.lazy({Bibbidi.Types.Input.PauseAction, :schema, []}),
            Zoi.lazy({Bibbidi.Types.Input.KeyDownAction, :schema, []}),
            Zoi.lazy({Bibbidi.Types.Input.KeyUpAction, :schema, []})
          ])
  @type t ::
          Bibbidi.Types.Input.PauseAction.t()
          | Bibbidi.Types.Input.KeyDownAction.t()
          | Bibbidi.Types.Input.KeyUpAction.t()

  @doc "Returns the Zoi schema for this type."
  def schema, do: @schema
end
