# Generated by mix bibbidi.gen — do not edit manually
defmodule Bibbidi.Types.Input.KeyUpAction do
  @moduledoc """
  `input.KeyUpAction`

  ## Fields

  - `type` - `"keyUp"` (required)
  - `value` - `String.t()` (required)
  """

  @schema Zoi.map(%{type: Zoi.string(), value: Zoi.string()})
  @type t :: %{type: String.t(), value: String.t()}

  @doc "Returns the Zoi schema for this type."
  def schema, do: @schema
end
