# Generated by mix bibbidi.gen — do not edit manually
defmodule Bibbidi.Types.Input.NoneSourceAction do
  @moduledoc """
  `input.NoneSourceAction`

  ## Fields

  - `type` - `"pause"` (required)
  - `duration` - `t:Bibbidi.Types.JsUint.t/0` (optional)
  """

  @schema Zoi.map(%{
            type: Zoi.string(),
            duration: Zoi.lazy({Bibbidi.Types.JsUint, :schema, []}) |> Zoi.optional()
          })
  @type t :: %{type: String.t(), duration: Bibbidi.Types.JsUint.t() | nil}

  @doc "Returns the Zoi schema for this type."
  def schema, do: @schema
end
