# Generated by mix bibbidi.gen — do not edit manually
defmodule Bibbidi.Types.Input.Origin do
  @moduledoc """
  `input.Origin`
  """

  @schema Zoi.union([
            Zoi.string(),
            Zoi.string(),
            Zoi.lazy({Bibbidi.Types.Input.ElementOrigin, :schema, []})
          ])
  @type t :: String.t() | Bibbidi.Types.Input.ElementOrigin.t()

  @doc "Returns the Zoi schema for this type."
  def schema, do: @schema
end
