# Generated by mix bibbidi.gen — do not edit manually
defmodule Bibbidi.Types.Input.PointerMoveAction do
  @moduledoc """
  `input.PointerMoveAction`

  ## Fields

  - `type` - `"pointerMove"` (required)
  - `x` - `float()` (required)
  - `y` - `float()` (required)
  - `duration` - `t:Bibbidi.Types.JsUint.t/0` (optional)
  - `origin` - `t:Bibbidi.Types.Input.Origin.t/0` (optional)
  - `width` - `term()` (optional)
  - `height` - `term()` (optional)
  - `pressure` - `float()` (optional)
  - `tangential_pressure` - `float()` (optional)
  - `twist` - `term()` (optional)
  - `altitude_angle` - `term()` (optional)
  - `azimuth_angle` - `term()` (optional)
  """

  @schema Zoi.map(%{
            type: Zoi.literal("pointerMove"),
            x: Zoi.float(),
            y: Zoi.float(),
            duration: Zoi.lazy({Bibbidi.Types.JsUint, :schema, []}) |> Zoi.optional(),
            origin: Zoi.lazy({Bibbidi.Types.Input.Origin, :schema, []}) |> Zoi.optional(),
            width: Zoi.any() |> Zoi.optional(),
            height: Zoi.any() |> Zoi.optional(),
            pressure: Zoi.float() |> Zoi.optional(),
            tangential_pressure: Zoi.float() |> Zoi.optional(),
            twist: Zoi.any() |> Zoi.optional(),
            altitude_angle: Zoi.any() |> Zoi.optional(),
            azimuth_angle: Zoi.any() |> Zoi.optional()
          })
  @type t :: %{
          type: String.t(),
          x: float(),
          y: float(),
          duration: Bibbidi.Types.JsUint.t() | nil,
          origin: Bibbidi.Types.Input.Origin.t() | nil,
          width: term() | nil,
          height: term() | nil,
          pressure: float() | nil,
          tangential_pressure: float() | nil,
          twist: term() | nil,
          altitude_angle: term() | nil,
          azimuth_angle: term() | nil
        }

  @doc "Returns the Zoi schema for this type."
  def schema, do: @schema
end
