# Generated by mix bibbidi.gen — do not edit manually
defmodule Bibbidi.Types.Input.PointerMoveAction do
  @moduledoc """
  `input.PointerMoveAction`

  ## Fields

  - `type` - `"pointerMove"` (required)
  - `x` - `float()` (required)
  - `y` - `float()` (required)
  - `duration` - `t:Bibbidi.Types.JsUint.t/0` (optional)
  - `origin` - `t:Bibbidi.Types.Input.Origin.t/0` (optional)
  """

  @schema Zoi.map(%{
            type: Zoi.string(),
            x: Zoi.float(),
            y: Zoi.float(),
            duration: Zoi.lazy({Bibbidi.Types.JsUint, :schema, []}) |> Zoi.optional(),
            origin: Zoi.lazy({Bibbidi.Types.Input.Origin, :schema, []}) |> Zoi.optional()
          })
  @type t :: %{
          type: String.t(),
          x: float(),
          y: float(),
          duration: Bibbidi.Types.JsUint.t() | nil,
          origin: Bibbidi.Types.Input.Origin.t() | nil
        }

  @doc "Returns the Zoi schema for this type."
  def schema, do: @schema
end
