# Generated by mix bibbidi.gen — do not edit manually
defmodule Bibbidi.Types.Input.PointerParameters do
  @moduledoc """
  `input.PointerParameters`

  ## Fields

  - `pointer_type` - `term()` (optional)
  """

  @schema Zoi.map(%{pointer_type: Zoi.any() |> Zoi.optional()})
  @type t :: %{pointer_type: term() | nil}

  @doc "Returns the Zoi schema for this type."
  def schema, do: @schema
end
