# Generated by mix bibbidi.gen — do not edit manually
defmodule Bibbidi.Types.Input.PointerDownAction do
  @moduledoc """
  `input.PointerDownAction`

  ## Fields

  - `type` - `"pointerDown"` (required)
  - `button` - `t:Bibbidi.Types.JsUint.t/0` (required)
  """

  @schema Zoi.map(%{type: Zoi.string(), button: Zoi.lazy({Bibbidi.Types.JsUint, :schema, []})})
  @type t :: %{type: String.t(), button: Bibbidi.Types.JsUint.t()}

  @doc "Returns the Zoi schema for this type."
  def schema, do: @schema
end
