# Generated by mix bibbidi.gen — do not edit manually
defmodule Bibbidi.Types.Input.PointerSourceAction do
  @moduledoc """
  `input.PointerSourceAction`

  One of:
  - `t:Bibbidi.Types.Input.PauseAction.t/0`
  - `t:Bibbidi.Types.Input.PointerDownAction.t/0`
  - `t:Bibbidi.Types.Input.PointerUpAction.t/0`
  - `t:Bibbidi.Types.Input.PointerMoveAction.t/0`
  """

  @schema Zoi.union([
            Zoi.lazy({Bibbidi.Types.Input.PauseAction, :schema, []}),
            Zoi.lazy({Bibbidi.Types.Input.PointerDownAction, :schema, []}),
            Zoi.lazy({Bibbidi.Types.Input.PointerUpAction, :schema, []}),
            Zoi.lazy({Bibbidi.Types.Input.PointerMoveAction, :schema, []})
          ])
  @type t ::
          Bibbidi.Types.Input.PauseAction.t()
          | Bibbidi.Types.Input.PointerDownAction.t()
          | Bibbidi.Types.Input.PointerUpAction.t()
          | Bibbidi.Types.Input.PointerMoveAction.t()

  @doc "Returns the Zoi schema for this type."
  def schema, do: @schema
end
