# Generated by mix bibbidi.gen — do not edit manually
defmodule Bibbidi.Types.Input.SourceActions do
  @moduledoc """
  `input.SourceActions`

  One of:
  - `t:Bibbidi.Types.Input.NoneSourceActions.t/0`
  - `t:Bibbidi.Types.Input.KeySourceActions.t/0`
  - `t:Bibbidi.Types.Input.PointerSourceActions.t/0`
  - `t:Bibbidi.Types.Input.WheelSourceActions.t/0`
  """

  @schema Zoi.union([
            Zoi.lazy({Bibbidi.Types.Input.NoneSourceActions, :schema, []}),
            Zoi.lazy({Bibbidi.Types.Input.KeySourceActions, :schema, []}),
            Zoi.lazy({Bibbidi.Types.Input.PointerSourceActions, :schema, []}),
            Zoi.lazy({Bibbidi.Types.Input.WheelSourceActions, :schema, []})
          ])
  @type t ::
          Bibbidi.Types.Input.NoneSourceActions.t()
          | Bibbidi.Types.Input.KeySourceActions.t()
          | Bibbidi.Types.Input.PointerSourceActions.t()
          | Bibbidi.Types.Input.WheelSourceActions.t()

  @doc "Returns the Zoi schema for this type."
  def schema, do: @schema
end
