# Generated by mix bibbidi.gen — do not edit manually
defmodule Bibbidi.Types.Input.WheelSourceActions do
  @moduledoc """
  `input.WheelSourceActions`

  ## Fields

  - `type` - `"wheel"` (required)
  - `id` - `String.t()` (required)
  - `actions` - list of `t:Bibbidi.Types.Input.WheelSourceAction.t/0` (required)
  """

  @schema Zoi.map(%{
            type: Zoi.string(),
            id: Zoi.string(),
            actions: Zoi.list(Zoi.lazy({Bibbidi.Types.Input.WheelSourceAction, :schema, []}))
          })
  @type t :: %{
          type: String.t(),
          id: String.t(),
          actions: [Bibbidi.Types.Input.WheelSourceAction.t()]
        }

  @doc "Returns the Zoi schema for this type."
  def schema, do: @schema
end
