# Generated by mix bibbidi.gen — do not edit manually
defmodule Bibbidi.Commands.WebExtension.Install do
  @moduledoc """
  Command struct for `webExtension.install`.

  [WebDriver BiDi Spec](https://w3c.github.io/webdriver-bidi/#command-webExtension-install)
  ## Fields

  - `extension_data` - `t:Bibbidi.Types.WebExtension.ExtensionData.t/0` (required)

  """

  @derive Bibbidi.Telemetry.Metadata
  @schema Zoi.struct(__MODULE__, %{
            extension_data: Bibbidi.Types.WebExtension.ExtensionData.schema(),
            meta: Zoi.any() |> Zoi.optional()
          })
  @opts_schema Zoi.keyword([])
  @result_schema Zoi.map(%{extension: Bibbidi.Types.WebExtension.Extension.schema()})

  @type t :: unquote(Zoi.type_spec(@schema))
  @type opts :: unquote(Zoi.type_spec(@opts_schema))
  @type result :: unquote(Zoi.type_spec(@result_schema))

  @enforce_keys Zoi.Struct.enforce_keys(@schema)
  defstruct Zoi.Struct.struct_fields(@schema)

  @doc "Returns the Zoi schema for this command struct."
  def schema, do: @schema

  @doc "Returns the Zoi schema for the keyword options."
  def opts_schema, do: @opts_schema

  @doc "Returns the Zoi schema for the result type."
  def result_schema, do: @result_schema

  defimpl Bibbidi.Encodable do
    def method(_), do: "webExtension.install"

    def params(cmd), do: %{extensionData: cmd.extension_data}
  end
end
