# Generated by mix bibbidi.gen — do not edit manually
defmodule Bibbidi.Commands.Network do
  @moduledoc """
  Command builders for the `network` module of the WebDriver BiDi protocol.
  """

  alias Bibbidi.Connection
  alias __MODULE__.AddDataCollector
  alias __MODULE__.AddIntercept
  alias __MODULE__.ContinueRequest
  alias __MODULE__.ContinueResponse
  alias __MODULE__.ContinueWithAuth
  alias __MODULE__.DisownData
  alias __MODULE__.FailRequest
  alias __MODULE__.GetData
  alias __MODULE__.ProvideResponse
  alias __MODULE__.RemoveDataCollector
  alias __MODULE__.RemoveIntercept
  alias __MODULE__.SetCacheBehavior
  alias __MODULE__.SetExtraHeaders

  @doc """
  Executes the `network.addDataCollector` command.

  ## Options

  #{Zoi.describe(AddDataCollector.opts_schema())}
  """
  @spec add_data_collector(
          GenServer.server(),
          [Bibbidi.Types.Network.DataType.t()],
          Bibbidi.Types.JsUint.t(),
          AddDataCollector.opts()
        ) :: {:ok, AddDataCollector.result()} | {:error, term()}
  def add_data_collector(conn, data_types, max_encoded_data_size, opts \\ []) do
    {connection_mod, opts} = Keyword.pop(opts, :connection_mod, Connection)
    opts = Zoi.parse!(AddDataCollector.opts_schema(), opts)

    connection_mod.execute(
      conn,
      struct!(AddDataCollector, [
        {:data_types, data_types},
        {:max_encoded_data_size, max_encoded_data_size} | opts
      ]),
      []
    )
  end

  @doc """
  Executes the `network.addIntercept` command.

  ## Options

  #{Zoi.describe(AddIntercept.opts_schema())}
  """
  @spec add_intercept(
          GenServer.server(),
          [Bibbidi.Types.Network.InterceptPhase.t()],
          AddIntercept.opts()
        ) :: {:ok, AddIntercept.result()} | {:error, term()}
  def add_intercept(conn, phases, opts \\ []) do
    {connection_mod, opts} = Keyword.pop(opts, :connection_mod, Connection)
    opts = Zoi.parse!(AddIntercept.opts_schema(), opts)
    connection_mod.execute(conn, struct!(AddIntercept, [{:phases, phases} | opts]), [])
  end

  @doc """
  Executes the `network.continueRequest` command.

  ## Options

  #{Zoi.describe(ContinueRequest.opts_schema())}
  """
  @spec continue_request(
          GenServer.server(),
          Bibbidi.Types.Network.Request.t(),
          ContinueRequest.opts()
        ) :: {:ok, ContinueRequest.result()} | {:error, term()}
  def continue_request(conn, request, opts \\ []) do
    {connection_mod, opts} = Keyword.pop(opts, :connection_mod, Connection)
    opts = Zoi.parse!(ContinueRequest.opts_schema(), opts)
    connection_mod.execute(conn, struct!(ContinueRequest, [{:request, request} | opts]), [])
  end

  @doc """
  Executes the `network.continueResponse` command.

  ## Options

  #{Zoi.describe(ContinueResponse.opts_schema())}
  """
  @spec continue_response(
          GenServer.server(),
          Bibbidi.Types.Network.Request.t(),
          ContinueResponse.opts()
        ) :: {:ok, ContinueResponse.result()} | {:error, term()}
  def continue_response(conn, request, opts \\ []) do
    {connection_mod, opts} = Keyword.pop(opts, :connection_mod, Connection)
    opts = Zoi.parse!(ContinueResponse.opts_schema(), opts)
    connection_mod.execute(conn, struct!(ContinueResponse, [{:request, request} | opts]), [])
  end

  @doc """
  Executes the `network.continueWithAuth` command.

  ## Options

  #{Zoi.describe(ContinueWithAuth.opts_schema())}
  """
  @spec continue_with_auth(
          GenServer.server(),
          Bibbidi.Types.Network.Request.t(),
          ContinueWithAuth.opts()
        ) :: {:ok, ContinueWithAuth.result()} | {:error, term()}
  def continue_with_auth(conn, request, opts \\ []) do
    {connection_mod, opts} = Keyword.pop(opts, :connection_mod, Connection)
    opts = Zoi.parse!(ContinueWithAuth.opts_schema(), opts)
    connection_mod.execute(conn, struct!(ContinueWithAuth, [{:request, request} | opts]), [])
  end

  @doc "Executes the `network.disownData` command."
  @spec disown_data(
          GenServer.server(),
          Bibbidi.Types.Network.DataType.t(),
          Bibbidi.Types.Network.Collector.t(),
          Bibbidi.Types.Network.Request.t(),
          DisownData.opts()
        ) :: {:ok, DisownData.result()} | {:error, term()}
  def disown_data(conn, data_type, collector, request, opts \\ []) do
    {connection_mod, _opts} = Keyword.pop(opts, :connection_mod, Connection)

    connection_mod.execute(
      conn,
      struct!(DisownData, [{:data_type, data_type}, {:collector, collector}, {:request, request}]),
      []
    )
  end

  @doc "Executes the `network.failRequest` command."
  @spec fail_request(GenServer.server(), Bibbidi.Types.Network.Request.t(), FailRequest.opts()) ::
          {:ok, FailRequest.result()} | {:error, term()}
  def fail_request(conn, request, opts \\ []) do
    {connection_mod, _opts} = Keyword.pop(opts, :connection_mod, Connection)
    connection_mod.execute(conn, struct!(FailRequest, [{:request, request}]), [])
  end

  @doc """
  Executes the `network.getData` command.

  ## Options

  #{Zoi.describe(GetData.opts_schema())}
  """
  @spec get_data(
          GenServer.server(),
          Bibbidi.Types.Network.DataType.t(),
          Bibbidi.Types.Network.Request.t(),
          GetData.opts()
        ) :: {:ok, GetData.result()} | {:error, term()}
  def get_data(conn, data_type, request, opts \\ []) do
    {connection_mod, opts} = Keyword.pop(opts, :connection_mod, Connection)
    opts = Zoi.parse!(GetData.opts_schema(), opts)

    connection_mod.execute(
      conn,
      struct!(GetData, [{:data_type, data_type}, {:request, request} | opts]),
      []
    )
  end

  @doc """
  Executes the `network.provideResponse` command.

  ## Options

  #{Zoi.describe(ProvideResponse.opts_schema())}
  """
  @spec provide_response(
          GenServer.server(),
          Bibbidi.Types.Network.Request.t(),
          ProvideResponse.opts()
        ) :: {:ok, ProvideResponse.result()} | {:error, term()}
  def provide_response(conn, request, opts \\ []) do
    {connection_mod, opts} = Keyword.pop(opts, :connection_mod, Connection)
    opts = Zoi.parse!(ProvideResponse.opts_schema(), opts)
    connection_mod.execute(conn, struct!(ProvideResponse, [{:request, request} | opts]), [])
  end

  @doc "Executes the `network.removeDataCollector` command."
  @spec remove_data_collector(
          GenServer.server(),
          Bibbidi.Types.Network.Collector.t(),
          RemoveDataCollector.opts()
        ) :: {:ok, RemoveDataCollector.result()} | {:error, term()}
  def remove_data_collector(conn, collector, opts \\ []) do
    {connection_mod, _opts} = Keyword.pop(opts, :connection_mod, Connection)
    connection_mod.execute(conn, struct!(RemoveDataCollector, [{:collector, collector}]), [])
  end

  @doc "Executes the `network.removeIntercept` command."
  @spec remove_intercept(
          GenServer.server(),
          Bibbidi.Types.Network.Intercept.t(),
          RemoveIntercept.opts()
        ) :: {:ok, RemoveIntercept.result()} | {:error, term()}
  def remove_intercept(conn, intercept, opts \\ []) do
    {connection_mod, _opts} = Keyword.pop(opts, :connection_mod, Connection)
    connection_mod.execute(conn, struct!(RemoveIntercept, [{:intercept, intercept}]), [])
  end

  @doc """
  Executes the `network.setCacheBehavior` command.

  ## Options

  #{Zoi.describe(SetCacheBehavior.opts_schema())}
  """
  @spec set_cache_behavior(GenServer.server(), String.t(), SetCacheBehavior.opts()) ::
          {:ok, SetCacheBehavior.result()} | {:error, term()}
  def set_cache_behavior(conn, cache_behavior, opts \\ []) do
    {connection_mod, opts} = Keyword.pop(opts, :connection_mod, Connection)
    opts = Zoi.parse!(SetCacheBehavior.opts_schema(), opts)

    connection_mod.execute(
      conn,
      struct!(SetCacheBehavior, [{:cache_behavior, cache_behavior} | opts]),
      []
    )
  end

  @doc """
  Executes the `network.setExtraHeaders` command.

  ## Options

  #{Zoi.describe(SetExtraHeaders.opts_schema())}
  """
  @spec set_extra_headers(
          GenServer.server(),
          [Bibbidi.Types.Network.Header.t()],
          SetExtraHeaders.opts()
        ) :: {:ok, SetExtraHeaders.result()} | {:error, term()}
  def set_extra_headers(conn, headers, opts \\ []) do
    {connection_mod, opts} = Keyword.pop(opts, :connection_mod, Connection)
    opts = Zoi.parse!(SetExtraHeaders.opts_schema(), opts)
    connection_mod.execute(conn, struct!(SetExtraHeaders, [{:headers, headers} | opts]), [])
  end
end
