# Generated by mix bibbidi.gen — do not edit manually
defmodule Bibbidi.Commands.Session do
  @moduledoc """
  Command builders for the `session` module of the WebDriver BiDi protocol.

  See also `Bibbidi.Session` for a higher-level convenience API.
  """

  alias Bibbidi.Connection
  alias __MODULE__.Status
  alias __MODULE__.New
  alias __MODULE__.End
  alias __MODULE__.Subscribe
  alias __MODULE__.Unsubscribe

  @doc "Executes the `session.status` command."
  @spec status(GenServer.server()) :: {:ok, Status.result()} | {:error, term()}
  def status(conn) do
    Connection.execute(conn, %Status{})
  end

  @doc "Executes the `session.new` command."
  @spec new(GenServer.server(), term()) :: {:ok, New.result()} | {:error, term()}
  def new(conn, capabilities) do
    Connection.execute(conn, struct!(New, [{:capabilities, capabilities}]))
  end

  @doc "Executes the `session.end` command."
  @spec session_end(GenServer.server()) :: {:ok, End.result()} | {:error, term()}
  def session_end(conn) do
    Connection.execute(conn, %End{})
  end

  @doc """
  Executes the `session.subscribe` command.

  ## Options

  #{Zoi.describe(Subscribe.opts_schema())}
  """
  @spec subscribe(GenServer.server(), [String.t()], Subscribe.opts()) ::
          {:ok, Subscribe.result()} | {:error, term()}
  def subscribe(conn, events, opts \\ []) do
    opts = Zoi.parse!(Subscribe.opts_schema(), opts)
    Connection.execute(conn, struct!(Subscribe, [{:events, events} | opts]))
  end

  @doc """
  Executes the `session.unsubscribe` command.

  ## Options

  #{Zoi.describe(Unsubscribe.opts_schema())}
  """
  @spec unsubscribe(GenServer.server(), Unsubscribe.opts()) ::
          {:ok, Unsubscribe.result()} | {:error, term()}
  def unsubscribe(conn, opts \\ []) do
    opts = Zoi.parse!(Unsubscribe.opts_schema(), opts)
    Connection.execute(conn, struct!(Unsubscribe, opts))
  end
end
