# Generated by mix bibbidi.gen — do not edit manually
defmodule Bibbidi.Types.Browser.DownloadBehavior do
  @moduledoc """
  `browser.DownloadBehavior`

  ## Fields


  """

  @schema Zoi.map(%{})
  @type t :: %{}

  @doc "Returns the Zoi schema for this type."
  def schema, do: @schema
end
