# Generated by mix bibbidi.gen — do not edit manually
defmodule Bibbidi.Events.Script.Message do
  @moduledoc """
  Event struct for `script.message`.

  Params type: `script.MessageParameters`
  """

  defstruct [:channel, :data, :source]
end
