# Generated by mix bibbidi.gen — do not edit manually
defmodule Bibbidi.Events.Script.RealmCreated do
  @moduledoc """
  Event struct for `script.realmCreated`.

  Params type: `script.RealmInfo`
  """

  @derive {Bibbidi.Telemetry.Metadata, keys: [:context]}
  defstruct [:realm, :origin, :type, :context, :user_context, :sandbox, :owners]
end
