# Generated by mix bibbidi.gen — do not edit manually
defmodule Bibbidi.Events.Script.RealmDestroyed do
  @moduledoc """
  Event struct for `script.realmDestroyed`.

  Params type: `script.RealmDestroyedParameters`

  ## Fields

  - `realm` - `t:Bibbidi.Types.Script.Realm.t/0` (required)
  """

  defstruct [:realm]

  @doc "Returns the BiDi method name this event struct represents."
  @spec method() :: String.t()
  def method, do: "script.realmDestroyed"
end
