# Generated by mix bibbidi.gen — do not edit manually
defmodule Bibbidi.Events.Script.RealmDestroyed do
  @moduledoc """
  Event struct for `script.realmDestroyed`.

  Params type: `script.RealmDestroyedParameters`

  ## Fields

  - `realm` - `t:Bibbidi.Types.Script.Realm.t/0` (required)
  """

  defstruct [:realm]
end
