# Generated by mix bibbidi.gen — do not edit manually
defmodule Bibbidi.Types.Emulation.ForcedColorsModeTheme do
  @moduledoc """
  `emulation.ForcedColorsModeTheme`

  Values: `light`, `dark`
  """

  @schema Zoi.enum(["light", "dark"])
  @type t :: String.t()
  @values ~w(light dark)

  @doc "Returns the Zoi schema for this type."
  def schema, do: @schema

  @doc "Returns the list of valid values."
  def values, do: @values
end
