# Generated by mix bibbidi.gen — do not edit manually
defmodule Bibbidi.Types.Emulation.NetworkConditions do
  @moduledoc """
  `emulation.NetworkConditions`

  ## Fields

  - `type` - `"offline"` (required)
  """

  @schema Zoi.map(%{type: Zoi.string()})
  @type t :: %{type: String.t()}

  @doc "Returns the Zoi schema for this type."
  def schema, do: @schema
end
