# Generated by mix bibbidi.gen — do not edit manually
defmodule Bibbidi.Types.Emulation.ScreenArea do
  @moduledoc """
  `emulation.ScreenArea`

  ## Fields

  - `width` - `t:Bibbidi.Types.JsUint.t/0` (required)
  - `height` - `t:Bibbidi.Types.JsUint.t/0` (required)
  """

  @schema Zoi.map(%{
            width: Zoi.lazy({Bibbidi.Types.JsUint, :schema, []}),
            height: Zoi.lazy({Bibbidi.Types.JsUint, :schema, []})
          })
  @type t :: %{width: Bibbidi.Types.JsUint.t(), height: Bibbidi.Types.JsUint.t()}

  @doc "Returns the Zoi schema for this type."
  def schema, do: @schema
end
