# Generated by mix bibbidi.gen — do not edit manually
defmodule Bibbidi.Types.Emulation.ScreenOrientationNatural do
  @moduledoc """
  `emulation.ScreenOrientationNatural`

  Values: `portrait`, `landscape`
  """

  @schema Zoi.enum(["portrait", "landscape"])
  @type t :: String.t()
  @values ~w(portrait landscape)

  @doc "Returns the Zoi schema for this type."
  def schema, do: @schema

  @doc "Returns the list of valid values."
  def values, do: @values
end
