# Generated by mix bibbidi.gen — do not edit manually
defmodule Bibbidi.Types.Emulation.ScreenOrientation do
  @moduledoc """
  `emulation.ScreenOrientation`

  ## Fields

  - `natural` - `t:Bibbidi.Types.Emulation.ScreenOrientationNatural.t/0` (required)
  - `type` - `t:Bibbidi.Types.Emulation.ScreenOrientationType.t/0` (required)
  """

  @schema Zoi.map(%{
            natural: Zoi.lazy({Bibbidi.Types.Emulation.ScreenOrientationNatural, :schema, []}),
            type: Zoi.lazy({Bibbidi.Types.Emulation.ScreenOrientationType, :schema, []})
          })
  @type t :: %{
          natural: Bibbidi.Types.Emulation.ScreenOrientationNatural.t(),
          type: Bibbidi.Types.Emulation.ScreenOrientationType.t()
        }

  @doc "Returns the Zoi schema for this type."
  def schema, do: @schema
end
