# Generated by mix bibbidi.gen — do not edit manually
defmodule Bibbidi.Types.Emulation.ScreenOrientationType do
  @moduledoc """
  `emulation.ScreenOrientationType`

  Values: `portrait-primary`, `portrait-secondary`, `landscape-primary`, `landscape-secondary`
  """

  @schema Zoi.enum([
            "portrait-primary",
            "portrait-secondary",
            "landscape-primary",
            "landscape-secondary"
          ])
  @type t :: String.t()
  @values ~w(portrait-primary portrait-secondary landscape-primary landscape-secondary)

  @doc "Returns the Zoi schema for this type."
  def schema, do: @schema

  @doc "Returns the list of valid values."
  def values, do: @values
end
