# Generated by mix bibbidi.gen — do not edit manually
defmodule Bibbidi.Types.Script.ArrayLocalValue do
  @moduledoc """
  `script.ArrayLocalValue`

  ## Fields

  - `type` - `"array"` (required)
  - `value` - `t:Bibbidi.Types.Script.ListLocalValue.t/0` (required)
  """

  @schema Zoi.map(%{
            type: Zoi.string(),
            value: Zoi.lazy({Bibbidi.Types.Script.ListLocalValue, :schema, []})
          })
  @type t :: %{type: String.t(), value: Bibbidi.Types.Script.ListLocalValue.t()}

  @doc "Returns the Zoi schema for this type."
  def schema, do: @schema
end
