# Generated by mix bibbidi.gen — do not edit manually
defmodule Bibbidi.Types.Script.BooleanValue do
  @moduledoc """
  `script.BooleanValue`

  ## Fields

  - `type` - `"boolean"` (required)
  - `value` - `boolean()` (required)
  """

  @schema Zoi.map(%{type: Zoi.string(), value: Zoi.boolean()})
  @type t :: %{type: String.t(), value: boolean()}

  @doc "Returns the Zoi schema for this type."
  def schema, do: @schema
end
