# Generated by mix bibbidi.gen — do not edit manually
defmodule Bibbidi.Types.Script.ChannelProperties do
  @moduledoc """
  `script.ChannelProperties`

  ## Fields

  - `channel` - `t:Bibbidi.Types.Script.Channel.t/0` (required)
  - `serialization_options` - `t:Bibbidi.Types.Script.SerializationOptions.t/0` (optional)
  - `ownership` - `t:Bibbidi.Types.Script.ResultOwnership.t/0` (optional)
  """

  @schema Zoi.map(%{
            channel: Zoi.lazy({Bibbidi.Types.Script.Channel, :schema, []}),
            serialization_options:
              Zoi.lazy({Bibbidi.Types.Script.SerializationOptions, :schema, []}) |> Zoi.optional(),
            ownership:
              Zoi.lazy({Bibbidi.Types.Script.ResultOwnership, :schema, []}) |> Zoi.optional()
          })
  @type t :: %{
          channel: Bibbidi.Types.Script.Channel.t(),
          serialization_options: Bibbidi.Types.Script.SerializationOptions.t() | nil,
          ownership: Bibbidi.Types.Script.ResultOwnership.t() | nil
        }

  @doc "Returns the Zoi schema for this type."
  def schema, do: @schema
end
