# Generated by mix bibbidi.gen — do not edit manually
defmodule Bibbidi.Types.Script.ChannelValue do
  @moduledoc """
  `script.ChannelValue`

  ## Fields

  - `type` - `"channel"` (required)
  - `value` - `t:Bibbidi.Types.Script.ChannelProperties.t/0` (required)
  """

  @schema Zoi.map(%{
            type: Zoi.string(),
            value: Zoi.lazy({Bibbidi.Types.Script.ChannelProperties, :schema, []})
          })
  @type t :: %{type: String.t(), value: Bibbidi.Types.Script.ChannelProperties.t()}

  @doc "Returns the Zoi schema for this type."
  def schema, do: @schema
end
