# Generated by mix bibbidi.gen — do not edit manually
defmodule Bibbidi.Types.Script.ContextTarget do
  @moduledoc """
  `script.ContextTarget`

  ## Fields

  - `context` - `t:Bibbidi.Types.BrowsingContext.t/0` (required)
  - `sandbox` - `String.t()` (optional)
  """

  @schema Zoi.map(%{
            context: Zoi.lazy({Bibbidi.Types.BrowsingContext, :schema, []}),
            sandbox: Zoi.string() |> Zoi.optional()
          })
  @type t :: %{context: Bibbidi.Types.BrowsingContext.t(), sandbox: String.t() | nil}

  @doc "Returns the Zoi schema for this type."
  def schema, do: @schema
end
