# Generated by mix bibbidi.gen — do not edit manually
defmodule Bibbidi.Types.Script.HtmlcollectionRemoteValue do
  @moduledoc """
  `script.HTMLCollectionRemoteValue`

  ## Fields

  - `type` - `"htmlcollection"` (required)
  - `handle` - `t:Bibbidi.Types.Script.Handle.t/0` (optional)
  - `internal_id` - `t:Bibbidi.Types.Script.InternalId.t/0` (optional)
  - `value` - `t:Bibbidi.Types.Script.ListRemoteValue.t/0` (optional)
  """

  @schema Zoi.map(%{
            type: Zoi.string(),
            handle: Zoi.lazy({Bibbidi.Types.Script.Handle, :schema, []}) |> Zoi.optional(),
            internal_id:
              Zoi.lazy({Bibbidi.Types.Script.InternalId, :schema, []}) |> Zoi.optional(),
            value: Zoi.lazy({Bibbidi.Types.Script.ListRemoteValue, :schema, []}) |> Zoi.optional()
          })
  @type t :: %{
          type: String.t(),
          handle: Bibbidi.Types.Script.Handle.t() | nil,
          internal_id: Bibbidi.Types.Script.InternalId.t() | nil,
          value: Bibbidi.Types.Script.ListRemoteValue.t() | nil
        }

  @doc "Returns the Zoi schema for this type."
  def schema, do: @schema
end
