# Generated by mix bibbidi.gen — do not edit manually
defmodule Bibbidi.Types.Script.ListRemoteValue do
  @moduledoc """
  `script.ListRemoteValue`
  """

  @schema Zoi.list(Zoi.lazy({Bibbidi.Types.Script.RemoteValue, :schema, []}))
  @type t :: [Bibbidi.Types.Script.RemoteValue.t()]

  @doc "Returns the Zoi schema for this type."
  def schema, do: @schema
end
