# Generated by mix bibbidi.gen — do not edit manually
defmodule Bibbidi.Types.Script.ListLocalValue do
  @moduledoc """
  `script.ListLocalValue`
  """

  @schema Zoi.list(Zoi.lazy({Bibbidi.Types.Script.LocalValue, :schema, []}))
  @type t :: [Bibbidi.Types.Script.LocalValue.t()]

  @doc "Returns the Zoi schema for this type."
  def schema, do: @schema
end
