# Generated by mix bibbidi.gen — do not edit manually
defmodule Bibbidi.Types.Script.LocalValue do
  @moduledoc """
  `script.LocalValue`
  """

  @schema Zoi.union([
            Zoi.lazy({Bibbidi.Types.Script.RemoteReference, :schema, []}),
            Zoi.lazy({Bibbidi.Types.Script.PrimitiveProtocolValue, :schema, []}),
            Zoi.lazy({Bibbidi.Types.Script.ChannelValue, :schema, []}),
            Zoi.lazy({Bibbidi.Types.Script.ArrayLocalValue, :schema, []}),
            Zoi.map(%{}),
            Zoi.lazy({Bibbidi.Types.Script.MapLocalValue, :schema, []}),
            Zoi.lazy({Bibbidi.Types.Script.ObjectLocalValue, :schema, []}),
            Zoi.map(%{}),
            Zoi.lazy({Bibbidi.Types.Script.SetLocalValue, :schema, []})
          ])
  @type t ::
          Bibbidi.Types.Script.RemoteReference.t()
          | Bibbidi.Types.Script.PrimitiveProtocolValue.t()
          | Bibbidi.Types.Script.ChannelValue.t()
          | Bibbidi.Types.Script.ArrayLocalValue.t()
          | map()
          | Bibbidi.Types.Script.MapLocalValue.t()
          | Bibbidi.Types.Script.ObjectLocalValue.t()
          | Bibbidi.Types.Script.SetLocalValue.t()

  @doc "Returns the Zoi schema for this type."
  def schema, do: @schema
end
