# Generated by mix bibbidi.gen — do not edit manually
defmodule Bibbidi.Types.Script.MappingRemoteValue do
  @moduledoc """
  `script.MappingRemoteValue`
  """

  @schema Zoi.list(
            Zoi.tuple(
              {Zoi.union([Bibbidi.Types.Script.RemoteValue.schema(), Zoi.string()]),
               Bibbidi.Types.Script.RemoteValue.schema()}
            )
          )
  @type t :: [
          {Bibbidi.Types.Script.RemoteValue.t() | String.t(),
           Bibbidi.Types.Script.RemoteValue.t()}
        ]

  @doc "Returns the Zoi schema for this type."
  def schema, do: @schema
end
