# Generated by mix bibbidi.gen — do not edit manually
defmodule Bibbidi.Types.Script.MappingLocalValue do
  @moduledoc """
  `script.MappingLocalValue`
  """

  @schema Zoi.list(
            Zoi.tuple(
              {Zoi.union([Bibbidi.Types.Script.LocalValue.schema(), Zoi.string()]),
               Bibbidi.Types.Script.LocalValue.schema()}
            )
          )
  @type t :: [
          {Bibbidi.Types.Script.LocalValue.t() | String.t(), Bibbidi.Types.Script.LocalValue.t()}
        ]

  @doc "Returns the Zoi schema for this type."
  def schema, do: @schema
end
