# Generated by mix bibbidi.gen — do not edit manually
defmodule Bibbidi.Types.Script.NodeProperties do
  @moduledoc """
  `script.NodeProperties`

  ## Fields

  - `node_type` - `t:Bibbidi.Types.JsUint.t/0` (required)
  - `child_node_count` - `t:Bibbidi.Types.JsUint.t/0` (required)
  - `attributes` - `map()` (optional)
  - `children` - list of `t:Bibbidi.Types.Script.NodeRemoteValue.t/0` (optional)
  - `local_name` - `String.t()` (optional)
  - `mode` - `"open"` or `"closed"` (optional)
  - `namespace_uri` - `String.t()` (optional)
  - `node_value` - `String.t()` (optional)
  - `shadow_root` - `t:Bibbidi.Types.Script.NodeRemoteValue.t/0` or `nil` (optional)
  """

  @schema Zoi.map(%{
            node_type: Zoi.lazy({Bibbidi.Types.JsUint, :schema, []}),
            child_node_count: Zoi.lazy({Bibbidi.Types.JsUint, :schema, []}),
            attributes: Zoi.map(%{}) |> Zoi.optional(),
            children:
              Zoi.list(Zoi.lazy({Bibbidi.Types.Script.NodeRemoteValue, :schema, []}))
              |> Zoi.optional(),
            local_name: Zoi.string() |> Zoi.optional(),
            mode: Zoi.union([Zoi.string(), Zoi.string()]) |> Zoi.optional(),
            namespace_uri: Zoi.string() |> Zoi.optional(),
            node_value: Zoi.string() |> Zoi.optional(),
            shadow_root:
              Zoi.union([
                Zoi.lazy({Bibbidi.Types.Script.NodeRemoteValue, :schema, []}),
                Zoi.null()
              ])
              |> Zoi.optional()
          })
  @type t :: %{
          node_type: Bibbidi.Types.JsUint.t(),
          child_node_count: Bibbidi.Types.JsUint.t(),
          attributes: map() | nil,
          children: [Bibbidi.Types.Script.NodeRemoteValue.t()] | nil,
          local_name: String.t() | nil,
          mode: String.t() | nil,
          namespace_uri: String.t() | nil,
          node_value: String.t() | nil,
          shadow_root: Bibbidi.Types.Script.NodeRemoteValue.t() | nil | nil
        }

  @doc "Returns the Zoi schema for this type."
  def schema, do: @schema
end
