# Generated by mix bibbidi.gen — do not edit manually
defmodule Bibbidi.Types.Script.NumberValue do
  @moduledoc """
  `script.NumberValue`

  ## Fields

  - `type` - `"number"` (required)
  - `value` - `number` or `t:Bibbidi.Types.Script.SpecialNumber.t/0` (required)
  """

  @schema Zoi.map(%{
            type: Zoi.string(),
            value:
              Zoi.union([Zoi.any(), Zoi.lazy({Bibbidi.Types.Script.SpecialNumber, :schema, []})])
          })
  @type t :: %{type: String.t(), value: term() | Bibbidi.Types.Script.SpecialNumber.t()}

  @doc "Returns the Zoi schema for this type."
  def schema, do: @schema
end
