# Generated by mix bibbidi.gen — do not edit manually
defmodule Bibbidi.Types.Script.ObjectLocalValue do
  @moduledoc """
  `script.ObjectLocalValue`

  ## Fields

  - `type` - `"object"` (required)
  - `value` - `t:Bibbidi.Types.Script.MappingLocalValue.t/0` (required)
  """

  @schema Zoi.map(%{
            type: Zoi.string(),
            value: Zoi.lazy({Bibbidi.Types.Script.MappingLocalValue, :schema, []})
          })
  @type t :: %{type: String.t(), value: Bibbidi.Types.Script.MappingLocalValue.t()}

  @doc "Returns the Zoi schema for this type."
  def schema, do: @schema
end
