# Generated by mix bibbidi.gen — do not edit manually
defmodule Bibbidi.Types.Script.PrimitiveProtocolValue do
  @moduledoc """
  `script.PrimitiveProtocolValue`

  One of:
  - `t:Bibbidi.Types.Script.UndefinedValue.t/0`
  - `t:Bibbidi.Types.Script.NullValue.t/0`
  - `t:Bibbidi.Types.Script.StringValue.t/0`
  - `t:Bibbidi.Types.Script.NumberValue.t/0`
  - `t:Bibbidi.Types.Script.BooleanValue.t/0`
  - `t:Bibbidi.Types.Script.BigIntValue.t/0`
  """

  @schema Zoi.union([
            Zoi.lazy({Bibbidi.Types.Script.UndefinedValue, :schema, []}),
            Zoi.lazy({Bibbidi.Types.Script.NullValue, :schema, []}),
            Zoi.lazy({Bibbidi.Types.Script.StringValue, :schema, []}),
            Zoi.lazy({Bibbidi.Types.Script.NumberValue, :schema, []}),
            Zoi.lazy({Bibbidi.Types.Script.BooleanValue, :schema, []}),
            Zoi.lazy({Bibbidi.Types.Script.BigIntValue, :schema, []})
          ])
  @type t ::
          Bibbidi.Types.Script.UndefinedValue.t()
          | Bibbidi.Types.Script.NullValue.t()
          | Bibbidi.Types.Script.StringValue.t()
          | Bibbidi.Types.Script.NumberValue.t()
          | Bibbidi.Types.Script.BooleanValue.t()
          | Bibbidi.Types.Script.BigIntValue.t()

  @doc "Returns the Zoi schema for this type."
  def schema, do: @schema
end
