# Generated by mix bibbidi.gen — do not edit manually
defmodule Bibbidi.Types.Script.RealmType do
  @moduledoc """
  `script.RealmType`

  Values: `window`, `dedicated-worker`, `shared-worker`, `service-worker`, `worker`, `paint-worklet`, `audio-worklet`, `worklet`
  """

  @schema Zoi.enum([
            "window",
            "dedicated-worker",
            "shared-worker",
            "service-worker",
            "worker",
            "paint-worklet",
            "audio-worklet",
            "worklet"
          ])
  @type t :: String.t()
  @values ~w(window dedicated-worker shared-worker service-worker worker paint-worklet audio-worklet worklet)

  @doc "Returns the Zoi schema for this type."
  def schema, do: @schema

  @doc "Returns the list of valid values."
  def values, do: @values
end
