# Generated by mix bibbidi.gen — do not edit manually
defmodule Bibbidi.Types.Script.RegExpLocalValue do
  @moduledoc """
  `script.RegExpLocalValue`
  """

  @schema Zoi.map(Zoi.string(), Zoi.any())
  @type t :: map()

  @doc "Returns the Zoi schema for this type."
  def schema, do: @schema
end
