# Generated by mix bibbidi.gen — do not edit manually
defmodule Bibbidi.Types.Script.RemoteReference do
  @moduledoc """
  `script.RemoteReference`

  One of:
  - `t:Bibbidi.Types.Script.SharedReference.t/0`
  - `t:Bibbidi.Types.Script.RemoteObjectReference.t/0`
  """

  @schema Zoi.union([
            Zoi.lazy({Bibbidi.Types.Script.SharedReference, :schema, []}),
            Zoi.lazy({Bibbidi.Types.Script.RemoteObjectReference, :schema, []})
          ])
  @type t ::
          Bibbidi.Types.Script.SharedReference.t()
          | Bibbidi.Types.Script.RemoteObjectReference.t()

  @doc "Returns the Zoi schema for this type."
  def schema, do: @schema
end
