# Generated by mix bibbidi.gen — do not edit manually
defmodule Bibbidi.Types.Script.RemoteObjectReference do
  @moduledoc """
  `script.RemoteObjectReference`

  ## Fields

  - `handle` - `t:Bibbidi.Types.Script.Handle.t/0` (required)
  - `shared_id` - `t:Bibbidi.Types.Script.SharedId.t/0` (optional)
  """

  @schema Zoi.map(%{
            handle: Zoi.lazy({Bibbidi.Types.Script.Handle, :schema, []}),
            shared_id: Zoi.lazy({Bibbidi.Types.Script.SharedId, :schema, []}) |> Zoi.optional()
          })
  @type t :: %{
          handle: Bibbidi.Types.Script.Handle.t(),
          shared_id: Bibbidi.Types.Script.SharedId.t() | nil
        }

  @doc "Returns the Zoi schema for this type."
  def schema, do: @schema
end
