# Generated by mix bibbidi.gen — do not edit manually
defmodule Bibbidi.Types.Script.SerializationOptions do
  @moduledoc """
  `script.SerializationOptions`

  ## Fields

  - `max_dom_depth` - `t:Bibbidi.Types.JsUint.t/0` or `nil` (optional)
  - `max_object_depth` - `t:Bibbidi.Types.JsUint.t/0` or `nil` (optional)
  - `include_shadow_tree` - `"none"` or `"open"` or `"all"` (optional)
  """

  @schema Zoi.map(%{
            max_dom_depth:
              Zoi.union([Zoi.lazy({Bibbidi.Types.JsUint, :schema, []}), Zoi.null()])
              |> Zoi.optional(),
            max_object_depth:
              Zoi.union([Zoi.lazy({Bibbidi.Types.JsUint, :schema, []}), Zoi.null()])
              |> Zoi.optional(),
            include_shadow_tree:
              Zoi.union([Zoi.string(), Zoi.string(), Zoi.string()]) |> Zoi.optional()
          })
  @type t :: %{
          max_dom_depth: Bibbidi.Types.JsUint.t() | nil | nil,
          max_object_depth: Bibbidi.Types.JsUint.t() | nil | nil,
          include_shadow_tree: String.t() | nil
        }

  @doc "Returns the Zoi schema for this type."
  def schema, do: @schema
end
