# Generated by mix bibbidi.gen — do not edit manually
defmodule Bibbidi.Types.Script.Source do
  @moduledoc """
  `script.Source`

  ## Fields

  - `realm` - `t:Bibbidi.Types.Script.Realm.t/0` (required)
  - `context` - `t:Bibbidi.Types.BrowsingContext.t/0` (optional)
  - `user_context` - `t:Bibbidi.Types.Browser.UserContext.t/0` (optional)
  """

  @schema Zoi.map(%{
            realm: Zoi.lazy({Bibbidi.Types.Script.Realm, :schema, []}),
            context: Zoi.lazy({Bibbidi.Types.BrowsingContext, :schema, []}) |> Zoi.optional(),
            user_context:
              Zoi.lazy({Bibbidi.Types.Browser.UserContext, :schema, []}) |> Zoi.optional()
          })
  @type t :: %{
          realm: Bibbidi.Types.Script.Realm.t(),
          context: Bibbidi.Types.BrowsingContext.t() | nil,
          user_context: Bibbidi.Types.Browser.UserContext.t() | nil
        }

  @doc "Returns the Zoi schema for this type."
  def schema, do: @schema
end
