# Generated by mix bibbidi.gen — do not edit manually
defmodule Bibbidi.Types.Script.SpecialNumber do
  @moduledoc """
  `script.SpecialNumber`

  Values: `NaN`, `-0`, `Infinity`, `-Infinity`
  """

  @schema Zoi.enum(["NaN", "-0", "Infinity", "-Infinity"])
  @type t :: String.t()
  @values ~w(NaN -0 Infinity -Infinity)

  @doc "Returns the Zoi schema for this type."
  def schema, do: @schema

  @doc "Returns the list of valid values."
  def values, do: @values
end
