# Generated by mix bibbidi.gen — do not edit manually
defmodule Bibbidi.Types.Script.StackTrace do
  @moduledoc """
  `script.StackTrace`

  ## Fields

  - `call_frames` - list of `t:Bibbidi.Types.Script.StackFrame.t/0` (required)
  """

  @schema Zoi.map(%{
            call_frames: Zoi.list(Zoi.lazy({Bibbidi.Types.Script.StackFrame, :schema, []}))
          })
  @type t :: %{call_frames: [Bibbidi.Types.Script.StackFrame.t()]}

  @doc "Returns the Zoi schema for this type."
  def schema, do: @schema
end
