# Generated by mix bibbidi.gen — do not edit manually
defmodule Bibbidi.Types.Script.Target do
  @moduledoc """
  `script.Target`

  One of:
  - `t:Bibbidi.Types.Script.ContextTarget.t/0`
  - `t:Bibbidi.Types.Script.RealmTarget.t/0`
  """

  @schema Zoi.union([
            Zoi.lazy({Bibbidi.Types.Script.ContextTarget, :schema, []}),
            Zoi.lazy({Bibbidi.Types.Script.RealmTarget, :schema, []})
          ])
  @type t :: Bibbidi.Types.Script.ContextTarget.t() | Bibbidi.Types.Script.RealmTarget.t()

  @doc "Returns the Zoi schema for this type."
  def schema, do: @schema
end
