# Generated by mix bibbidi.gen — do not edit manually
defmodule Bibbidi.Types.Script.UndefinedValue do
  @moduledoc """
  `script.UndefinedValue`

  ## Fields

  - `type` - `"undefined"` (required)
  """

  @schema Zoi.map(%{type: Zoi.string()})
  @type t :: %{type: String.t()}

  @doc "Returns the Zoi schema for this type."
  def schema, do: @schema
end
