# Generated by mix bibbidi.gen — do not edit manually
defmodule Bibbidi.Types.Script.WindowProxyProperties do
  @moduledoc """
  `script.WindowProxyProperties`

  ## Fields

  - `context` - `t:Bibbidi.Types.BrowsingContext.t/0` (required)
  """

  @schema Zoi.map(%{context: Zoi.lazy({Bibbidi.Types.BrowsingContext, :schema, []})})
  @type t :: %{context: Bibbidi.Types.BrowsingContext.t()}

  @doc "Returns the Zoi schema for this type."
  def schema, do: @schema
end
