# Generated by mix bibbidi.gen — do not edit manually
defmodule Bibbidi.Types.Script.WindowProxyRemoteValue do
  @moduledoc """
  `script.WindowProxyRemoteValue`

  ## Fields

  - `type` - `"window"` (required)
  - `value` - `t:Bibbidi.Types.Script.WindowProxyProperties.t/0` (required)
  - `handle` - `t:Bibbidi.Types.Script.Handle.t/0` (optional)
  - `internal_id` - `t:Bibbidi.Types.Script.InternalId.t/0` (optional)
  """

  @schema Zoi.map(%{
            type: Zoi.string(),
            value: Zoi.lazy({Bibbidi.Types.Script.WindowProxyProperties, :schema, []}),
            handle: Zoi.lazy({Bibbidi.Types.Script.Handle, :schema, []}) |> Zoi.optional(),
            internal_id:
              Zoi.lazy({Bibbidi.Types.Script.InternalId, :schema, []}) |> Zoi.optional()
          })
  @type t :: %{
          type: String.t(),
          value: Bibbidi.Types.Script.WindowProxyProperties.t(),
          handle: Bibbidi.Types.Script.Handle.t() | nil,
          internal_id: Bibbidi.Types.Script.InternalId.t() | nil
        }

  @doc "Returns the Zoi schema for this type."
  def schema, do: @schema
end
