defmodule Bibbidi.CDDL.Generator do
  @moduledoc false

  alias Bibbidi.CDDL.Parser
  alias Bibbidi.CDDL.Utils

  @modules ~w(browsingContext script session browser network log storage input emulation webExtension)

  @doc """
  Builds an `%Igniter{}` with all generated events and command modules.

  Returns the igniter struct — the caller decides whether to apply or dry-run.
  """
  @spec run(Igniter.t()) :: Igniter.t()
  def run(igniter) do
    {:ok, remote_rules} = Parser.parse_file("priv/cddl/remote.cddl")
    {:ok, local_rules} = Parser.parse_file("priv/cddl/local.cddl")

    all_rules = remote_rules ++ local_rules
    grouped = group_by_module(all_rules)

    Enum.reduce(@modules, igniter, fn mod, igniter ->
      rules = Map.get(grouped, mod, [])

      igniter
      |> maybe_generate_events_module(mod, rules, local_rules, all_rules)
      |> maybe_generate_command_modules(mod, remote_rules, all_rules)
      |> maybe_generate_facade_module(mod, remote_rules, all_rules)
    end)
  end

  defp group_by_module(rules) do
    rules
    |> Enum.filter(fn {name, _} -> String.contains?(name, ".") end)
    |> Enum.group_by(fn {name, _} -> name |> String.split(".") |> hd() end)
  end

  @correlation_keys ~w(context navigation request)a

  defp maybe_generate_events_module(igniter, mod, _rules, local_rules, all_rules) do
    events = extract_events(mod, local_rules)
    if events == [], do: igniter, else: generate_events_module(igniter, mod, events, all_rules)
  end

  defp generate_events_module(igniter, mod, events, all_rules) do
    snake = to_snake(mod)
    camel = to_module_name(mod)

    event_list =
      events
      |> Enum.map(fn {method, _params_ref} -> ~s("#{method}") end)
      |> Enum.join(",\n      ")

    event_functions =
      events
      |> Enum.map(fn {method, params_ref} ->
        fun_name = method |> String.split(".") |> List.last() |> to_snake()

        """
          @doc \"\"\"
          Event: `#{method}`

          Params type: `#{params_ref || "none"}`
          \"\"\"
          def #{fun_name}, do: "#{method}"
        """
      end)
      |> Enum.join("\n")

    # Build parse/2 clauses
    parse_clauses = generate_parse_clauses(events, all_rules)

    # Build struct aliases for parse/2
    struct_aliases = generate_struct_aliases(events, all_rules)

    content = """
    # Generated by mix bibbidi.gen — do not edit manually
    defmodule Bibbidi.Events.#{camel} do
      @moduledoc \"\"\"
      Events for the `#{mod}` module of the WebDriver BiDi protocol.
      \"\"\"

    #{struct_aliases}
      @doc "Returns all event method names for this module."
      @spec events() :: [String.t()]
      def events do
        [
          #{event_list}
        ]
      end

    #{event_functions}
      @doc "Parses a raw event params map into a typed struct."
      @spec parse(String.t(), map()) :: struct() | map()
    #{parse_clauses}
      def parse(_method, params), do: params
    end
    """

    path = "lib/bibbidi/events/#{snake}.ex"

    igniter = Igniter.create_new_file(igniter, path, content, on_exists: :overwrite)

    # Generate event struct modules
    generate_event_struct_modules(igniter, mod, events, all_rules)
  end

  defp generate_parse_clauses(events, all_rules) do
    events
    |> Enum.map(fn {method, params_ref} ->
      struct_name = event_struct_name(method)
      fields = resolve_event_fields(params_ref, all_rules)

      if fields != [] do
        field_assignments =
          fields
          |> Enum.uniq_by(fn {json_key, _, _, _} -> json_key end)
          |> Enum.map(fn {json_key, elixir_key, _, _} ->
            "#{elixir_key}: params[\"#{json_key}\"]"
          end)
          |> Enum.join(", ")

        """
          def parse("#{method}", params) do
            %#{struct_name}{#{field_assignments}}
          end
        """
      else
        """
          def parse("#{method}", params), do: params
        """
      end
    end)
    |> Enum.join("\n")
  end

  defp generate_struct_aliases(events, all_rules) do
    events
    |> Enum.filter(fn {_, params_ref} -> resolve_event_fields(params_ref, all_rules) != [] end)
    |> Enum.map(fn {method, _} -> event_struct_name(method) end)
    |> Enum.map(fn name -> "  alias __MODULE__.#{name}" end)
    |> Enum.join("\n")
  end

  defp generate_event_struct_modules(igniter, mod, events, all_rules) do
    snake_mod = to_snake(mod)

    events
    |> Enum.reduce(igniter, fn {method, params_ref}, igniter ->
      fields = resolve_event_fields(params_ref, all_rules)

      if fields != [] do
        generate_event_struct_module(igniter, snake_mod, mod, method, params_ref, fields)
      else
        igniter
      end
    end)
  end

  defp generate_event_struct_module(igniter, snake_mod, mod, method, params_ref, fields) do
    camel_mod = to_module_name(mod)
    struct_name = event_struct_name(method)
    snake_struct = to_snake(struct_name)

    unique_fields =
      fields
      |> Enum.uniq_by(fn {json_key, _, _, _} -> json_key end)

    field_atoms = Enum.map(unique_fields, fn {_, elixir_key, _, _} -> ":#{elixir_key}" end)
    fields_str = Enum.join(field_atoms, ", ")

    # Determine correlation keys for this struct
    field_atom_list = Enum.map(unique_fields, fn {_, elixir_key, _, _} -> String.to_atom(elixir_key) end)
    correlation = Enum.filter(@correlation_keys, &(&1 in field_atom_list))

    derive_line =
      if correlation == [] do
        ""
      else
        keys_str = Enum.map_join(correlation, ", ", &":#{&1}")
        "  @derive {Bibbidi.Telemetry.Metadata, keys: [#{keys_str}]}\n"
      end

    content = """
    # Generated by mix bibbidi.gen — do not edit manually
    defmodule Bibbidi.Events.#{camel_mod}.#{struct_name} do
      @moduledoc \"\"\"
      Event struct for `#{method}`.

      Params type: `#{params_ref}`
      \"\"\"

    #{derive_line}  defstruct [#{fields_str}]
    end
    """

    path = "lib/bibbidi/events/#{snake_mod}/#{snake_struct}.ex"
    Igniter.create_new_file(igniter, path, content, on_exists: :overwrite)
  end

  defp resolve_event_fields(nil, _all_rules), do: []

  defp resolve_event_fields(params_ref, all_rules) do
    resolve_command_fields(params_ref, all_rules)
  end

  # "browsingContext.contextCreated" -> "ContextCreated"
  defp event_struct_name(method) do
    method |> String.split(".") |> List.last() |> to_module_name()
  end

  defp extract_events(mod, local_rules) do
    local_rules
    |> Enum.filter(fn {name, def} ->
      String.starts_with?(name, mod <> ".") and is_event_def?(def)
    end)
    |> Enum.map(fn {_name, {:group, members}} ->
      method =
        Enum.find_value(members, fn
          {:required, "method", {:string, m}} -> m
          _ -> nil
        end)

      params_ref =
        Enum.find_value(members, fn
          {:required, "params", {:ref, r}} -> r
          _ -> nil
        end)

      {method, params_ref}
    end)
    |> Enum.reject(fn {method, _} -> is_nil(method) end)
  end

  # ── Command struct generation ─────────────────────────────────────

  defp maybe_generate_command_modules(igniter, mod, remote_rules, all_rules) do
    commands = extract_commands(mod, remote_rules)
    if commands == [], do: igniter, else: generate_command_modules(igniter, mod, commands, all_rules)
  end

  defp extract_commands(mod, remote_rules) do
    remote_rules
    |> Enum.filter(fn {name, def} ->
      String.starts_with?(name, mod <> ".") and Utils.command_def?(def)
    end)
    |> Enum.map(fn {name, {:group, members}} ->
      command_name = name |> String.split(".") |> List.last()

      method =
        Enum.find_value(members, fn
          {:required, "method", {:string, m}} -> m
          _ -> nil
        end)

      params_ref =
        Enum.find_value(members, fn
          {:required, "params", {:ref, r}} -> r
          _ -> nil
        end)

      {command_name, method, params_ref}
    end)
    |> Enum.reject(fn {_, method, _} -> is_nil(method) end)
  end

  defp generate_command_modules(igniter, mod, commands, all_rules) do
    Enum.reduce(commands, igniter, fn {command_name, method, params_ref}, igniter ->
      generate_command_module(igniter, mod, command_name, method, params_ref, all_rules)
    end)
  end

  defp generate_command_module(igniter, mod, command_name, method, params_ref, all_rules) do
    snake_mod = to_snake(mod)
    camel_mod = to_module_name(mod)
    command_snake = to_snake(command_name)

    fields = resolve_command_fields(params_ref, all_rules)

    required = Enum.filter(fields, fn {_, _, req, _} -> req == :required end)
    optional = Enum.filter(fields, fn {_, _, req, _} -> req == :optional end)
    all_fields = required ++ optional

    # Build @schema (Zoi.struct)
    schema_fields =
      all_fields
      |> Enum.map(fn {_json, elixir, req, cddl_type} ->
        base = type_to_schema(cddl_type)

        if req == :optional do
          "#{elixir}: #{base} |> Zoi.optional()"
        else
          "#{elixir}: #{base}"
        end
      end)
      |> Enum.join(", ")

    # Build @opts_schema (Zoi.keyword for optional fields)
    opts_schema_fields =
      optional
      |> Enum.map(fn {_json, elixir, _, cddl_type} ->
        "#{elixir}: #{type_to_schema(cddl_type)} |> Zoi.optional()"
      end)
      |> Enum.join(", ")

    # Build @result_schema
    result_schema = resolve_result_schema(mod, command_name, all_rules)

    params_body = generate_params_body(required, optional)

    # Add meta field to schema (optional, not sent on wire)
    meta_schema_field = "meta: Zoi.any() |> Zoi.optional()"

    full_schema_fields =
      if schema_fields == "" do
        meta_schema_field
      else
        "#{schema_fields}, #{meta_schema_field}"
      end

    content = """
    # Generated by mix bibbidi.gen — do not edit manually
    defmodule Bibbidi.Commands.#{camel_mod}.#{command_name} do
      @moduledoc \"\"\"
      Command struct for `#{method}`.
      \"\"\"

      @derive Bibbidi.Telemetry.Metadata
      @schema Zoi.struct(__MODULE__, %{#{full_schema_fields}})
      @opts_schema Zoi.keyword([#{opts_schema_fields}])
      @result_schema #{result_schema}

      @type t :: unquote(Zoi.type_spec(@schema))
      @type opts :: unquote(Zoi.type_spec(@opts_schema))
      @type result :: unquote(Zoi.type_spec(@result_schema))

      @enforce_keys Zoi.Struct.enforce_keys(@schema)
      defstruct Zoi.Struct.struct_fields(@schema)

      @doc "Returns the Zoi schema for this command struct."
      def schema, do: @schema

      @doc "Returns the Zoi schema for the keyword options."
      def opts_schema, do: @opts_schema

      @doc "Returns the Zoi schema for the result type."
      def result_schema, do: @result_schema

      defimpl Bibbidi.Encodable do
        def method(_), do: "#{method}"

    #{params_body}
      end
    end
    """

    path = "lib/bibbidi/commands/#{snake_mod}/#{command_snake}.ex"
    Igniter.create_new_file(igniter, path, content, on_exists: :overwrite)
  end

  @doc """
  Resolves a CDDL params reference into a list of
  `{json_key, elixir_key, :required | :optional, cddl_type}` tuples.

  Used by the code generator and by `mix bibbidi.cddl.inspect --fields`.
  """
  def resolve_command_fields(nil, _all_rules), do: []
  def resolve_command_fields("EmptyParams", _all_rules), do: []

  def resolve_command_fields(ref, all_rules) do
    case List.keyfind(all_rules, ref, 0) do
      {^ref, {:map, content}} ->
        extract_field_defs_from_map(content, all_rules)

      {^ref, {:group, members}} ->
        extract_field_defs(members, all_rules)

      {^ref, {:choice, alternatives}} ->
        # For choice types, merge fields from all alternatives (all optional)
        resolve_choice_fields(alternatives, all_rules)

      _ ->
        []
    end
  end

  defp extract_field_defs_from_map(content, all_rules) do
    Enum.flat_map(content, fn
      {:fields, fields} -> extract_field_defs(fields, all_rules)
      {:group_choice, groups} -> extract_field_defs_from_group_choice(groups, all_rules)
      _ -> []
    end)
  end

  defp extract_field_defs_from_group_choice(groups, all_rules) do
    # For group choices inside maps (e.g. coordinates // error),
    # include all fields as optional since only one branch is used at a time
    groups
    |> Enum.flat_map(fn
      {:fields, fields} ->
        Enum.flat_map(fields, fn
          {:required, name, type} -> [{name, to_snake(name), :optional, type}]
          {:optional, name, type} -> [{name, to_snake(name), :optional, type}]
          {:embed, ref} ->
            resolve_command_fields(ref, all_rules)
            |> Enum.map(fn {json, elixir, _, type} -> {json, elixir, :optional, type} end)
          _ -> []
        end)

      {:group, members} ->
        Enum.flat_map(members, fn
          {:required, name, type} -> [{name, to_snake(name), :optional, type}]
          {:optional, name, type} -> [{name, to_snake(name), :optional, type}]
          {:embed, ref} ->
            resolve_command_fields(ref, all_rules)
            |> Enum.map(fn {json, elixir, _, type} -> {json, elixir, :optional, type} end)
          _ -> []
        end)

      _ ->
        []
    end)
    |> Enum.uniq_by(fn {json, _, _, _} -> json end)
  end

  defp resolve_choice_fields(alternatives, all_rules) do
    # Resolve each alternative ref and merge all fields as optional
    Enum.flat_map(alternatives, fn
      {:ref, ref} ->
        resolve_command_fields(ref, all_rules)
        |> Enum.map(fn {json, elixir, _, type} -> {json, elixir, :optional, type} end)

      _ ->
        []
    end)
    |> Enum.uniq_by(fn {json, _, _, _} -> json end)
  end

  defp extract_field_defs(fields, all_rules) do
    Enum.flat_map(fields, fn
      {:required, name, type} ->
        [{name, to_snake(name), :required, type}]

      {:optional, name, type} ->
        [{name, to_snake(name), :optional, type}]

      {:group_choice, groups} ->
        extract_field_defs_from_group_choice(groups, all_rules)

      {:embed, ref} ->
        resolve_command_fields(ref, all_rules)

      _ ->
        []
    end)
  end

  defp generate_params_body([], []) do
    "    def params(_cmd), do: %{}"
  end

  defp generate_params_body(required, []) do
    fields =
      Enum.map_join(required, ", ", fn {json_key, elixir_key, _, _} ->
        "#{json_key}: cmd.#{elixir_key}"
      end)

    "    def params(cmd), do: %{#{fields}}"
  end

  defp generate_params_body(required, optional) do
    required_map =
      if required == [] do
        "%{}"
      else
        fields =
          Enum.map_join(required, ", ", fn {json_key, elixir_key, _, _} ->
            "#{json_key}: cmd.#{elixir_key}"
          end)

        "%{#{fields}}"
      end

    optional_entries =
      Enum.map_join(optional, ",\n        ", fn {json_key, elixir_key, _, _} ->
        "{:#{json_key}, cmd.#{elixir_key}}"
      end)

    """
        def params(cmd) do
          optional = [
            #{optional_entries}
          ]

          Enum.reduce(optional, #{required_map}, fn
            {_key, nil}, acc -> acc
            {key, value}, acc -> Map.put(acc, key, value)
          end)
        end
    """
  end

  # ── Result type resolution ──────────────────────────────────────

  @doc """
  Resolves the result Zoi schema string for a command.

  Looks up `<mod>.<CommandName>Result` in all_rules.
  """
  def resolve_result_schema(mod, command_name, all_rules) do
    result_ref = "#{mod}.#{command_name}Result"
    resolve_result_ref(result_ref, all_rules, 0)
  end

  defp resolve_result_ref(_ref, _all_rules, depth) when depth > 5 do
    "Zoi.map(Zoi.string(), Zoi.any())"
  end

  defp resolve_result_ref(ref, all_rules, depth) do
    case List.keyfind(all_rules, ref, 0) do
      nil ->
        # No result type found
        "Zoi.map(Zoi.string(), Zoi.any())"

      {^ref, {:ref, "EmptyResult"}} ->
        "Zoi.map(Zoi.string(), Zoi.any())"

      {^ref, {:ref, inner_ref}} ->
        # Follow reference chain (e.g., ReloadResult → NavigateResult)
        resolve_result_ref(inner_ref, all_rules, depth + 1)

      {^ref, {:map, [{:fields, []}]}} ->
        "Zoi.map(Zoi.string(), Zoi.any())"

      {^ref, {:map, [{:fields, fields}]}} ->
        field_schemas =
          fields
          |> Enum.map(fn
            {:required, key, type} -> "#{to_snake(key)}: #{type_to_schema(type)}"
            {:optional, key, type} -> "#{to_snake(key)}: #{type_to_schema(type)} |> Zoi.optional()"
            {:extensible, _, _} -> nil
            {:embed, _} -> nil
            {:group_choice, _} -> nil
          end)
          |> Enum.reject(&is_nil/1)
          |> Enum.join(", ")

        "Zoi.map(%{#{field_schemas}})"

      {^ref, {:choice, _}} ->
        "Zoi.any()"

      {^ref, {:group, members}} ->
        # Check if it's an EmptyResult-like group
        real_fields =
          Enum.filter(members, fn
            {:required, _, _} -> true
            {:optional, _, _} -> true
            _ -> false
          end)

        if real_fields == [] do
          "Zoi.map(Zoi.string(), Zoi.any())"
        else
          field_schemas =
            real_fields
            |> Enum.map(fn
              {:required, key, type} -> "#{to_snake(key)}: #{type_to_schema(type)}"
              {:optional, key, type} -> "#{to_snake(key)}: #{type_to_schema(type)} |> Zoi.optional()"
            end)
            |> Enum.join(", ")

          "Zoi.map(%{#{field_schemas}})"
        end

      _ ->
        "Zoi.map(Zoi.string(), Zoi.any())"
    end
  end

  # ── Predicate helpers ───────────────────────────────────────────────

  defp is_event_def?({:group, members}) do
    has_method =
      Enum.any?(members, fn
        {:required, "method", {:string, m}} -> not String.ends_with?(m, "Command")
        _ -> false
      end)

    has_method and Utils.command_def?({:group, members})
  end

  defp is_event_def?(_), do: false

  # ── Zoi schema generation ─────────────────────────────────────────

  @doc false
  def type_to_schema({:primitive, :text}), do: "Zoi.string()"
  def type_to_schema({:primitive, :text, _}), do: "Zoi.string()"
  def type_to_schema({:primitive, :uint}), do: "Zoi.integer() |> Zoi.min(0)"
  def type_to_schema({:primitive, :uint, _}), do: "Zoi.integer() |> Zoi.min(0)"
  def type_to_schema({:primitive, :int}), do: "Zoi.integer()"
  def type_to_schema({:primitive, :int, _}), do: "Zoi.integer()"
  def type_to_schema({:primitive, :float}), do: "Zoi.float()"
  def type_to_schema({:primitive, :float, _}), do: "Zoi.float()"
  def type_to_schema({:primitive, :bool}), do: "Zoi.boolean()"
  def type_to_schema({:primitive, :bool, _}), do: "Zoi.boolean()"
  def type_to_schema({:primitive, :any}), do: "Zoi.any()"
  def type_to_schema({:primitive, :null}), do: "Zoi.null()"
  def type_to_schema({:string, _}), do: "Zoi.string()"
  def type_to_schema({:number, n}) when is_integer(n), do: "Zoi.integer()"
  def type_to_schema({:number, n}) when is_float(n), do: "Zoi.float()"
  def type_to_schema({:range, low, high}), do: "Zoi.integer() |> Zoi.min(#{low}) |> Zoi.max(#{high})"
  def type_to_schema({:range_exclusive, _low, _high}), do: "Zoi.integer()"
  def type_to_schema({:ref, _name}), do: "Zoi.any()"
  def type_to_schema({:array, inner, _q}), do: "Zoi.list(#{type_to_schema(inner)})"

  def type_to_schema({:choice, items}) do
    schemas = Enum.map(items, &type_to_schema/1)
    "Zoi.union([#{Enum.join(schemas, ", ")}])"
  end

  def type_to_schema({:choice, items, _constraint}) do
    # 3-element choice with constraint (e.g. {:choice, items, {:default, _}})
    type_to_schema({:choice, items})
  end

  def type_to_schema({:map, [{:fields, fields}]}) do
    field_schemas =
      fields
      |> Enum.map(fn
        {:required, key, type} -> "#{to_snake(key)}: #{type_to_schema(type)}"
        {:optional, key, type} -> "#{to_snake(key)}: #{type_to_schema(type)} |> Zoi.optional()"
        {:extensible, _, _} -> nil
        {:embed, _} -> nil
        {:group_choice, _} -> nil
      end)
      |> Enum.reject(&is_nil/1)
      |> Enum.join(", ")

    "Zoi.map(%{#{field_schemas}})"
  end

  def type_to_schema({:map, _}), do: "Zoi.map(Zoi.string(), Zoi.any())"
  def type_to_schema({:group, _}), do: "Zoi.map(Zoi.string(), Zoi.any())"
  def type_to_schema({:tuple, items}), do: "Zoi.tuple({#{Enum.map_join(items, ", ", &type_to_schema/1)}})"
  def type_to_schema({:group_choice, _}), do: "Zoi.any()"
  def type_to_schema(_), do: "Zoi.any()"

  # ── Typespec generation (for facade specs from CDDL types) ──────

  @doc false
  def type_to_spec({:primitive, :text}), do: "String.t()"
  def type_to_spec({:primitive, :text, _constraint}), do: "String.t()"
  def type_to_spec({:primitive, :uint}), do: "non_neg_integer()"
  def type_to_spec({:primitive, :uint, _constraint}), do: "non_neg_integer()"
  def type_to_spec({:primitive, :int}), do: "integer()"
  def type_to_spec({:primitive, :int, _constraint}), do: "integer()"
  def type_to_spec({:primitive, :float}), do: "float()"
  def type_to_spec({:primitive, :float, _constraint}), do: "float()"
  def type_to_spec({:primitive, :bool}), do: "boolean()"
  def type_to_spec({:primitive, :bool, _constraint}), do: "boolean()"
  def type_to_spec({:primitive, :any}), do: "term()"
  def type_to_spec({:primitive, :null}), do: "nil"
  def type_to_spec({:string, _}), do: "String.t()"
  def type_to_spec({:ref, _name}), do: "term()"
  def type_to_spec({:number, n}) when is_integer(n), do: "integer()"
  def type_to_spec({:number, n}) when is_float(n), do: "float()"
  def type_to_spec({:range, _low, _high}), do: "integer()"
  def type_to_spec({:range_exclusive, _low, _high}), do: "integer()"

  def type_to_spec({:choice, items}) do
    items
    |> Enum.map(&type_to_spec/1)
    |> Enum.uniq()
    |> Enum.join(" | ")
  end

  def type_to_spec({:choice, items, _constraint}) do
    type_to_spec({:choice, items})
  end

  def type_to_spec({:array, inner, _quantifier}), do: "[#{type_to_spec(inner)}]"
  def type_to_spec({:tuple, items}), do: "{#{Enum.map_join(items, ", ", &type_to_spec/1)}}"
  def type_to_spec({:map, _}), do: "map()"
  def type_to_spec({:group, _}), do: "map()"
  def type_to_spec({:group_choice, _}), do: "map()"
  def type_to_spec(_), do: "term()"

  # ── Facade module generation ──────────────────────────────────────

  defp maybe_generate_facade_module(igniter, mod, remote_rules, all_rules) do
    commands = extract_commands(mod, remote_rules)
    if commands == [], do: igniter, else: generate_facade_module(igniter, mod, commands, all_rules)
  end

  defp generate_facade_module(igniter, mod, commands, all_rules) do
    snake = to_snake(mod)
    camel = to_module_name(mod)

    # Collect all command module aliases needed
    command_aliases =
      commands
      |> Enum.map(fn {command_name, _, _} -> command_name end)
      |> Enum.map(fn name -> "  alias __MODULE__.#{name}" end)
      |> Enum.join("\n")

    functions =
      commands
      |> Enum.map(fn {command_name, method, params_ref} ->
        generate_facade_function(camel, command_name, method, params_ref, all_rules)
      end)
      |> Enum.join("\n")

    session_note =
      if mod == "session" do
        "\n\n  See also `Bibbidi.Session` for a higher-level convenience API."
      else
        ""
      end

    content = """
    # Generated by mix bibbidi.gen — do not edit manually
    defmodule Bibbidi.Commands.#{camel} do
      @moduledoc \"\"\"
      Command builders for the `#{mod}` module of the WebDriver BiDi protocol.#{session_note}
      \"\"\"

      alias Bibbidi.Connection
    #{command_aliases}

    #{functions}end
    """

    path = "lib/bibbidi/commands/#{snake}.ex"
    Igniter.create_new_file(igniter, path, content, on_exists: :overwrite)
  end

  # Elixir reserved words that can't be function names
  @reserved_words ~w(end do fn if else case cond for receive try raise rescue after catch with)

  defp generate_facade_function(_camel_mod, command_name, method, params_ref, all_rules) do
    raw_name = to_snake(command_name)

    fun_name =
      if raw_name in @reserved_words do
        # Derive a safe name from the BiDi module prefix + command name
        mod_prefix = method |> String.split(".") |> hd()
        to_snake(mod_prefix) <> "_" <> raw_name
      else
        raw_name
      end

    fields = resolve_command_fields(params_ref, all_rules)

    required = Enum.filter(fields, fn {_, _, req, _} -> req == :required end)
    optional = Enum.filter(fields, fn {_, _, req, _} -> req == :optional end)

    # Build the function signature — every function takes opts for :connection_mod
    required_args = Enum.map_join(required, ", ", fn {_, elixir, _, _} -> elixir end)

    args_str =
      case required_args do
        "" -> "conn, opts \\\\ []"
        r -> "conn, #{r}, opts \\\\ []"
      end

    # Build the struct creation body
    struct_body =
      case {required, optional} do
        {[], []} ->
          "%#{command_name}{}"

        {req, []} ->
          fields_str =
            req
            |> Enum.map(fn {_, elixir, _, _} -> "{:#{elixir}, #{elixir}}" end)
            |> Enum.join(", ")

          "struct!(#{command_name}, [#{fields_str}])"

        {req, _} ->
          required_pairs =
            req
            |> Enum.map(fn {_, elixir, _, _} -> "{:#{elixir}, #{elixir}}" end)

          all_pairs = Enum.join(required_pairs, ", ")

          if all_pairs == "" do
            "struct!(#{command_name}, opts)"
          else
            "struct!(#{command_name}, [#{all_pairs} | opts])"
          end
      end

    # Build the @spec with real types
    spec_required_args =
      required
      |> Enum.map(fn {_, _, _, cddl_type} -> type_to_spec(cddl_type) end)

    spec_args =
      case spec_required_args do
        [] ->
          "GenServer.server(), #{command_name}.opts()"

        r ->
          "GenServer.server(), #{Enum.join(r, ", ")}, #{command_name}.opts()"
      end

    result_type = "#{command_name}.result()"

    # Build @doc with opts description
    doc =
      if optional != [] do
        """
          @doc \"\"\"
          Executes the `#{method}` command.

          ## Options

          \#{Zoi.describe(#{command_name}.opts_schema())}
          \"\"\"
        """
      else
        "  @doc \"Executes the `#{method}` command.\"\n"
      end

    # Build parse line for opts
    parse_line =
      if optional != [] do
        "    opts = Zoi.parse!(#{command_name}.opts_schema(), opts)\n"
      else
        ""
      end

    pop_line =
      if optional != [] do
        "    {connection_mod, opts} = Keyword.pop(opts, :connection_mod, Connection)"
      else
        "    {connection_mod, _opts} = Keyword.pop(opts, :connection_mod, Connection)"
      end

    """
    #{doc}  @spec #{fun_name}(#{spec_args}) :: {:ok, #{result_type}} | {:error, term()}
      def #{fun_name}(#{args_str}) do
    #{pop_line}
    #{parse_line}    connection_mod.execute(conn, #{struct_body}, [])
      end
    """
  end

  defdelegate to_snake(str), to: Utils
  defdelegate to_module_name(str), to: Utils
end
