# Generated by mix bibbidi.gen — do not edit manually
defmodule Bibbidi.Commands.Browser.SetClientWindowState do
  @moduledoc """
  Command struct for `browser.setClientWindowState`.
  """

  @schema Zoi.struct(__MODULE__, %{client_window: Zoi.any()})
  @opts_schema Zoi.keyword([])
  @result_schema Zoi.map(%{
                   active: Zoi.boolean(),
                   client_window: Zoi.any(),
                   height: Zoi.any(),
                   state: Zoi.union([Zoi.string(), Zoi.string(), Zoi.string(), Zoi.string()]),
                   width: Zoi.any(),
                   x: Zoi.any(),
                   y: Zoi.any()
                 })

  @type t :: unquote(Zoi.type_spec(@schema))
  @type opts :: unquote(Zoi.type_spec(@opts_schema))
  @type result :: unquote(Zoi.type_spec(@result_schema))

  @enforce_keys Zoi.Struct.enforce_keys(@schema)
  defstruct Zoi.Struct.struct_fields(@schema)

  @doc "Returns the Zoi schema for this command struct."
  def schema, do: @schema

  @doc "Returns the Zoi schema for the keyword options."
  def opts_schema, do: @opts_schema

  @doc "Returns the Zoi schema for the result type."
  def result_schema, do: @result_schema

  defimpl Bibbidi.Encodable do
    def method(_), do: "browser.setClientWindowState"

    def params(cmd), do: %{clientWindow: cmd.client_window}
  end
end
