# Generated by mix bibbidi.gen — do not edit manually
defmodule Bibbidi.Events.BrowsingContext.ContextDestroyed do
  @moduledoc """
  Event struct for `browsingContext.contextDestroyed`.

  Params type: `browsingContext.Info`
  """

  @derive {Bibbidi.Telemetry.Metadata, keys: [:context]}
  defstruct [:children, :client_window, :context, :original_opener, :url, :user_context, :parent]
end
