# Generated by mix bibbidi.gen — do not edit manually
defmodule Bibbidi.Events.BrowsingContext.DownloadEnd do
  @moduledoc """
  Event struct for `browsingContext.downloadEnd`.

  Params type: `browsingContext.DownloadEndParams`
  """

  @derive {Bibbidi.Telemetry.Metadata, keys: [:context, :navigation]}
  defstruct [:status, :context, :navigation, :timestamp, :url, :user_context, :filepath]
end
