# Generated by mix bibbidi.gen — do not edit manually
defmodule Bibbidi.Events.BrowsingContext.DownloadWillBegin do
  @moduledoc """
  Event struct for `browsingContext.downloadWillBegin`.

  Params type: `browsingContext.DownloadWillBeginParams`
  """

  @derive {Bibbidi.Telemetry.Metadata, keys: [:context, :navigation]}
  defstruct [:suggested_filename, :context, :navigation, :timestamp, :url, :user_context]
end
