# Generated by mix bibbidi.gen — do not edit manually
defmodule Bibbidi.Events.BrowsingContext.HistoryUpdated do
  @moduledoc """
  Event struct for `browsingContext.historyUpdated`.

  Params type: `browsingContext.HistoryUpdatedParameters`

  ## Fields

  - `context` - `t:Bibbidi.Types.BrowsingContext.t/0` (required)
  - `timestamp` - `t:Bibbidi.Types.JsUint.t/0` (required)
  - `url` - `String.t()` (required)
  - `user_context` - `t:Bibbidi.Types.Browser.UserContext.t/0` (optional)
  """

  @derive {Bibbidi.Telemetry.Metadata, keys: [:context]}
  defstruct [:context, :timestamp, :url, :user_context]
end
