# Generated by mix bibbidi.gen — do not edit manually
defmodule Bibbidi.Events.BrowsingContext.HistoryUpdated do
  @moduledoc """
  Event struct for `browsingContext.historyUpdated`.

  Params type: `browsingContext.HistoryUpdatedParameters`
  """

  @derive {Bibbidi.Telemetry.Metadata, keys: [:context]}
  defstruct [:context, :timestamp, :url, :user_context]
end
