# Generated by mix bibbidi.gen — do not edit manually
defmodule Bibbidi.Events.BrowsingContext.NavigationStarted do
  @moduledoc """
  Event struct for `browsingContext.navigationStarted`.

  Params type: `browsingContext.NavigationInfo`
  """

  @derive {Bibbidi.Telemetry.Metadata, keys: [:context, :navigation]}
  defstruct [:context, :navigation, :timestamp, :url, :user_context]
end
