# Generated by mix bibbidi.gen — do not edit manually
defmodule Bibbidi.Events.BrowsingContext.UserPromptOpened do
  @moduledoc """
  Event struct for `browsingContext.userPromptOpened`.

  Params type: `browsingContext.UserPromptOpenedParameters`
  """

  @derive {Bibbidi.Telemetry.Metadata, keys: [:context]}
  defstruct [:context, :handler, :message, :type, :user_context, :default_value]
end
