# Generated by mix bibbidi.gen — do not edit manually
defmodule Bibbidi.Events.BrowsingContext.UserPromptClosed do
  @moduledoc """
  Event struct for `browsingContext.userPromptClosed`.

  Params type: `browsingContext.UserPromptClosedParameters`
  """

  @derive {Bibbidi.Telemetry.Metadata, keys: [:context]}
  defstruct [:context, :accepted, :type, :user_context, :user_text]
end
