# Generated by mix bibbidi.gen — do not edit manually
defmodule Bibbidi.Types.JsUint do
  @moduledoc """
  `js-uint`
  """

  @schema Zoi.integer() |> Zoi.min(0) |> Zoi.max(9_007_199_254_740_991)
  @type t :: integer()

  @doc "Returns the Zoi schema for this type."
  def schema, do: @schema
end
