# Generated by mix bibbidi.gen — do not edit manually
defmodule Bibbidi.Commands.Network.AddDataCollector do
  @moduledoc """
  Command struct for `network.addDataCollector`.
  """

  @derive Bibbidi.Telemetry.Metadata
  @schema Zoi.struct(__MODULE__, %{
            data_types: Zoi.list(Zoi.any()),
            max_encoded_data_size: Zoi.any(),
            collector_type: Zoi.any() |> Zoi.optional(),
            contexts: Zoi.list(Zoi.any()) |> Zoi.optional(),
            user_contexts: Zoi.list(Zoi.any()) |> Zoi.optional(),
            meta: Zoi.any() |> Zoi.optional()
          })
  @opts_schema Zoi.keyword(
                 collector_type: Zoi.any() |> Zoi.optional(),
                 contexts: Zoi.list(Zoi.any()) |> Zoi.optional(),
                 user_contexts: Zoi.list(Zoi.any()) |> Zoi.optional()
               )
  @result_schema Zoi.map(%{collector: Zoi.any()})

  @type t :: unquote(Zoi.type_spec(@schema))
  @type opts :: unquote(Zoi.type_spec(@opts_schema))
  @type result :: unquote(Zoi.type_spec(@result_schema))

  @enforce_keys Zoi.Struct.enforce_keys(@schema)
  defstruct Zoi.Struct.struct_fields(@schema)

  @doc "Returns the Zoi schema for this command struct."
  def schema, do: @schema

  @doc "Returns the Zoi schema for the keyword options."
  def opts_schema, do: @opts_schema

  @doc "Returns the Zoi schema for the result type."
  def result_schema, do: @result_schema

  defimpl Bibbidi.Encodable do
    def method(_), do: "network.addDataCollector"

    def params(cmd) do
      optional = [
        {:collectorType, cmd.collector_type},
        {:contexts, cmd.contexts},
        {:userContexts, cmd.user_contexts}
      ]

      Enum.reduce(
        optional,
        %{dataTypes: cmd.data_types, maxEncodedDataSize: cmd.max_encoded_data_size},
        fn
          {_key, nil}, acc -> acc
          {key, value}, acc -> Map.put(acc, key, value)
        end
      )
    end
  end
end
