# Generated by mix bibbidi.gen — do not edit manually
defmodule Bibbidi.Commands.Network.AddDataCollector do
  @moduledoc """
  Command struct for `network.addDataCollector`.

  [WebDriver BiDi Spec](https://w3c.github.io/webdriver-bidi/#command-network-addDataCollector)
  ## Fields

  - `data_types` - list of `t:Bibbidi.Types.Network.DataType.t/0` (required)
  - `max_encoded_data_size` - `t:Bibbidi.Types.JsUint.t/0` (required)
  - `collector_type` - `term()` (optional)
  - `contexts` - list of `t:Bibbidi.Types.BrowsingContext.t/0` (optional)
  - `user_contexts` - list of `t:Bibbidi.Types.Browser.UserContext.t/0` (optional)

  """

  @derive Bibbidi.Telemetry.Metadata
  @schema Zoi.struct(__MODULE__, %{
            data_types: Zoi.list(Bibbidi.Types.Network.DataType.schema()),
            max_encoded_data_size: Bibbidi.Types.JsUint.schema(),
            collector_type: Zoi.any() |> Zoi.optional(),
            contexts: Zoi.list(Bibbidi.Types.BrowsingContext.schema()) |> Zoi.optional(),
            user_contexts: Zoi.list(Bibbidi.Types.Browser.UserContext.schema()) |> Zoi.optional(),
            meta: Zoi.any() |> Zoi.optional()
          })
  @opts_schema Zoi.keyword(
                 collector_type: Zoi.any() |> Zoi.optional(),
                 contexts: Zoi.list(Zoi.any()) |> Zoi.optional(),
                 user_contexts: Zoi.list(Zoi.any()) |> Zoi.optional()
               )
  @result_schema Zoi.map(%{collector: Bibbidi.Types.Network.Collector.schema()})

  @type t :: unquote(Zoi.type_spec(@schema))
  @type opts :: unquote(Zoi.type_spec(@opts_schema))
  @type result :: unquote(Zoi.type_spec(@result_schema))

  @enforce_keys Zoi.Struct.enforce_keys(@schema)
  defstruct Zoi.Struct.struct_fields(@schema)

  @doc "Returns the Zoi schema for this command struct."
  def schema, do: @schema

  @doc "Returns the Zoi schema for the keyword options."
  def opts_schema, do: @opts_schema

  @doc "Returns the Zoi schema for the result type."
  def result_schema, do: @result_schema

  defimpl Bibbidi.Encodable do
    def method(_), do: "network.addDataCollector"

    def params(cmd) do
      optional = [
        {:collectorType, cmd.collector_type},
        {:contexts, cmd.contexts},
        {:userContexts, cmd.user_contexts}
      ]

      Enum.reduce(
        optional,
        %{dataTypes: cmd.data_types, maxEncodedDataSize: cmd.max_encoded_data_size},
        fn
          {_key, nil}, acc -> acc
          {key, value}, acc -> Map.put(acc, key, value)
        end
      )
    end
  end
end
