# Generated by mix bibbidi.gen — do not edit manually
defmodule Bibbidi.Commands.Network.AddIntercept do
  @moduledoc """
  Command struct for `network.addIntercept`.

  [WebDriver BiDi Spec](https://w3c.github.io/webdriver-bidi/#command-network-addIntercept)
  ## Fields

  - `phases` - list of `t:Bibbidi.Types.Network.InterceptPhase.t/0` (required)
  - `contexts` - list of `t:Bibbidi.Types.BrowsingContext.t/0` (optional)
  - `url_patterns` - list of `t:Bibbidi.Types.Network.UrlPattern.t/0` (optional)

  """

  @derive Bibbidi.Telemetry.Metadata
  @schema Zoi.struct(__MODULE__, %{
            phases: Zoi.list(Bibbidi.Types.Network.InterceptPhase.schema()),
            contexts: Zoi.list(Bibbidi.Types.BrowsingContext.schema()) |> Zoi.optional(),
            url_patterns: Zoi.list(Bibbidi.Types.Network.UrlPattern.schema()) |> Zoi.optional(),
            meta: Zoi.any() |> Zoi.optional()
          })
  @opts_schema Zoi.keyword(
                 contexts: Zoi.list(Zoi.any()) |> Zoi.optional(),
                 url_patterns: Zoi.list(Zoi.any()) |> Zoi.optional()
               )
  @result_schema Zoi.map(%{intercept: Bibbidi.Types.Network.Intercept.schema()})

  @type t :: unquote(Zoi.type_spec(@schema))
  @type opts :: unquote(Zoi.type_spec(@opts_schema))
  @type result :: unquote(Zoi.type_spec(@result_schema))

  @enforce_keys Zoi.Struct.enforce_keys(@schema)
  defstruct Zoi.Struct.struct_fields(@schema)

  @doc "Returns the Zoi schema for this command struct."
  def schema, do: @schema

  @doc "Returns the Zoi schema for the keyword options."
  def opts_schema, do: @opts_schema

  @doc "Returns the Zoi schema for the result type."
  def result_schema, do: @result_schema

  defimpl Bibbidi.Encodable do
    def method(_), do: "network.addIntercept"

    def params(cmd) do
      optional = [
        {:contexts, cmd.contexts},
        {:urlPatterns, cmd.url_patterns}
      ]

      Enum.reduce(optional, %{phases: cmd.phases}, fn
        {_key, nil}, acc -> acc
        {key, value}, acc -> Map.put(acc, key, value)
      end)
    end
  end
end
