# Generated by mix bibbidi.gen — do not edit manually
defmodule Bibbidi.Commands.Network.ContinueRequest do
  @moduledoc """
  Command struct for `network.continueRequest`.

  [WebDriver BiDi Spec](https://w3c.github.io/webdriver-bidi/#command-network-continueRequest)
  ## Fields

  - `request` - `t:Bibbidi.Types.Network.Request.t/0` (required)
  - `body` - `t:Bibbidi.Types.Network.BytesValue.t/0` (optional)
  - `cookies` - list of `t:Bibbidi.Types.Network.CookieHeader.t/0` (optional)
  - `headers` - list of `t:Bibbidi.Types.Network.Header.t/0` (optional)
  - `method` - `String.t()` (optional)
  - `url` - `String.t()` (optional)

  """

  @derive Bibbidi.Telemetry.Metadata
  @schema Zoi.struct(__MODULE__, %{
            request: Bibbidi.Types.Network.Request.schema(),
            body: Bibbidi.Types.Network.BytesValue.schema() |> Zoi.optional(),
            cookies: Zoi.list(Bibbidi.Types.Network.CookieHeader.schema()) |> Zoi.optional(),
            headers: Zoi.list(Bibbidi.Types.Network.Header.schema()) |> Zoi.optional(),
            method: Zoi.string() |> Zoi.optional(),
            url: Zoi.string() |> Zoi.optional(),
            meta: Zoi.any() |> Zoi.optional()
          })
  @opts_schema Zoi.keyword(
                 body: Zoi.any() |> Zoi.optional(),
                 cookies: Zoi.list(Zoi.any()) |> Zoi.optional(),
                 headers: Zoi.list(Zoi.any()) |> Zoi.optional(),
                 method: Zoi.string() |> Zoi.optional(),
                 url: Zoi.string() |> Zoi.optional()
               )
  @result_schema Zoi.map(Zoi.string(), Zoi.any())

  @type t :: unquote(Zoi.type_spec(@schema))
  @type opts :: unquote(Zoi.type_spec(@opts_schema))
  @type result :: unquote(Zoi.type_spec(@result_schema))

  @enforce_keys Zoi.Struct.enforce_keys(@schema)
  defstruct Zoi.Struct.struct_fields(@schema)

  @doc "Returns the Zoi schema for this command struct."
  def schema, do: @schema

  @doc "Returns the Zoi schema for the keyword options."
  def opts_schema, do: @opts_schema

  @doc "Returns the Zoi schema for the result type."
  def result_schema, do: @result_schema

  defimpl Bibbidi.Encodable do
    def method(_), do: "network.continueRequest"

    def params(cmd) do
      optional = [
        {:body, cmd.body},
        {:cookies, cmd.cookies},
        {:headers, cmd.headers},
        {:method, cmd.method},
        {:url, cmd.url}
      ]

      Enum.reduce(optional, %{request: cmd.request}, fn
        {_key, nil}, acc -> acc
        {key, value}, acc -> Map.put(acc, key, value)
      end)
    end
  end
end
