# Generated by mix bibbidi.gen — do not edit manually
defmodule Bibbidi.Commands.Network.ContinueWithAuth do
  @moduledoc """
  Command struct for `network.continueWithAuth`.

  [WebDriver BiDi Spec](https://w3c.github.io/webdriver-bidi/#command-network-continueWithAuth)
  ## Fields

  - `request` - `t:Bibbidi.Types.Network.Request.t/0` (required)
  - `action` - `"provideCredentials"` (optional)
  - `credentials` - `t:Bibbidi.Types.Network.AuthCredentials.t/0` (optional)

  """

  @derive Bibbidi.Telemetry.Metadata
  @schema Zoi.struct(__MODULE__, %{
            request: Bibbidi.Types.Network.Request.schema(),
            action: Zoi.string() |> Zoi.optional(),
            credentials: Bibbidi.Types.Network.AuthCredentials.schema() |> Zoi.optional(),
            meta: Zoi.any() |> Zoi.optional()
          })
  @opts_schema Zoi.keyword(
                 action: Zoi.string() |> Zoi.optional(),
                 credentials: Zoi.any() |> Zoi.optional()
               )
  @result_schema Zoi.map(Zoi.string(), Zoi.any())

  @type t :: unquote(Zoi.type_spec(@schema))
  @type opts :: unquote(Zoi.type_spec(@opts_schema))
  @type result :: unquote(Zoi.type_spec(@result_schema))

  @enforce_keys Zoi.Struct.enforce_keys(@schema)
  defstruct Zoi.Struct.struct_fields(@schema)

  @doc "Returns the Zoi schema for this command struct."
  def schema, do: @schema

  @doc "Returns the Zoi schema for the keyword options."
  def opts_schema, do: @opts_schema

  @doc "Returns the Zoi schema for the result type."
  def result_schema, do: @result_schema

  defimpl Bibbidi.Encodable do
    def method(_), do: "network.continueWithAuth"

    def params(cmd) do
      optional = [
        {:action, cmd.action},
        {:credentials, cmd.credentials}
      ]

      Enum.reduce(optional, %{request: cmd.request}, fn
        {_key, nil}, acc -> acc
        {key, value}, acc -> Map.put(acc, key, value)
      end)
    end
  end
end
