# Generated by mix bibbidi.gen — do not edit manually
defmodule Bibbidi.Commands.Network.GetData do
  @moduledoc """
  Command struct for `network.getData`.

  [WebDriver BiDi Spec](https://w3c.github.io/webdriver-bidi/#command-network-getData)
  ## Fields

  - `data_type` - `t:Bibbidi.Types.Network.DataType.t/0` (required)
  - `request` - `t:Bibbidi.Types.Network.Request.t/0` (required)
  - `collector` - `t:Bibbidi.Types.Network.Collector.t/0` (optional)
  - `disown` - `boolean()` (optional)

  """

  @derive Bibbidi.Telemetry.Metadata
  @schema Zoi.struct(__MODULE__, %{
            data_type: Bibbidi.Types.Network.DataType.schema(),
            request: Bibbidi.Types.Network.Request.schema(),
            collector: Bibbidi.Types.Network.Collector.schema() |> Zoi.optional(),
            disown: Zoi.boolean() |> Zoi.optional(),
            meta: Zoi.any() |> Zoi.optional()
          })
  @opts_schema Zoi.keyword(
                 collector: Zoi.any() |> Zoi.optional(),
                 disown: Zoi.boolean() |> Zoi.optional()
               )
  @result_schema Zoi.map(%{bytes: Bibbidi.Types.Network.BytesValue.schema()})

  @type t :: unquote(Zoi.type_spec(@schema))
  @type opts :: unquote(Zoi.type_spec(@opts_schema))
  @type result :: unquote(Zoi.type_spec(@result_schema))

  @enforce_keys Zoi.Struct.enforce_keys(@schema)
  defstruct Zoi.Struct.struct_fields(@schema)

  @doc "Returns the Zoi schema for this command struct."
  def schema, do: @schema

  @doc "Returns the Zoi schema for the keyword options."
  def opts_schema, do: @opts_schema

  @doc "Returns the Zoi schema for the result type."
  def result_schema, do: @result_schema

  defimpl Bibbidi.Encodable do
    def method(_), do: "network.getData"

    def params(cmd) do
      optional = [
        {:collector, cmd.collector},
        {:disown, cmd.disown}
      ]

      Enum.reduce(optional, %{dataType: cmd.data_type, request: cmd.request}, fn
        {_key, nil}, acc -> acc
        {key, value}, acc -> Map.put(acc, key, value)
      end)
    end
  end
end
