# Generated by mix bibbidi.gen — do not edit manually
defmodule Bibbidi.Types.WebExtension.ExtensionArchivePath do
  @moduledoc """
  `webExtension.ExtensionArchivePath`

  ## Fields

  - `type` - `"archivePath"` (required)
  - `path` - `String.t()` (required)
  """

  @schema Zoi.map(%{type: Zoi.string(), path: Zoi.string()})
  @type t :: %{type: String.t(), path: String.t()}

  @doc "Returns the Zoi schema for this type."
  def schema, do: @schema
end
