# Generated by mix bibbidi.gen — do not edit manually
defmodule Bibbidi.Commands.Session.Unsubscribe do
  @moduledoc """
  Command struct for `session.unsubscribe`.
  """

  defstruct [:events, :subscriptions]

  defimpl Bibbidi.Encodable do
    def method(_), do: "session.unsubscribe"

    def params(cmd) do
      optional = [
        {:events, cmd.events},
        {:subscriptions, cmd.subscriptions}
      ]

      Enum.reduce(optional, %{}, fn
        {_key, nil}, acc -> acc
        {key, value}, acc -> Map.put(acc, key, value)
      end)
    end
  end
end
