defmodule Bibbidi.CDDL.Generator do
  @moduledoc false

  alias Bibbidi.CDDL.Parser

  @modules ~w(browsingContext script session browser network log storage input emulation webExtension)

  def run do
    {:ok, remote_rules} = Parser.parse_file("priv/cddl/remote.cddl")
    {:ok, local_rules} = Parser.parse_file("priv/cddl/local.cddl")

    all_rules = remote_rules ++ local_rules
    grouped = group_by_module(all_rules)

    for mod <- @modules do
      rules = Map.get(grouped, mod, [])
      generate_types_module(mod, rules)
      generate_events_module(mod, rules, local_rules)
    end
  end

  defp group_by_module(rules) do
    rules
    |> Enum.filter(fn {name, _} -> String.contains?(name, ".") end)
    |> Enum.group_by(fn {name, _} -> name |> String.split(".") |> hd() end)
  end

  defp generate_types_module(mod, rules) do
    snake = to_snake(mod)
    camel = to_module_name(mod)
    types = extract_types(rules)

    return = if types == [], do: :skip, else: :ok
    if return == :skip, do: throw(:skip)

    type_defs =
      types
      |> Enum.map(fn {name, def} -> generate_type(name, def) end)
      |> Enum.reject(&is_nil/1)
      |> Enum.uniq_by(fn line -> line |> String.split("::") |> hd() |> String.trim() end)
      |> Enum.join("\n\n")

    content = """
    # Generated by mix bibbidi.gen — do not edit manually
    defmodule Bibbidi.Types.#{camel} do
      @moduledoc \"\"\"
      Type definitions for the `#{mod}` module of the WebDriver BiDi protocol.
      \"\"\"

    #{type_defs}
    end
    """

    path = "lib/bibbidi/types/#{snake}.ex"
    File.mkdir_p!(Path.dirname(path))
    File.write!(path, content)
    Mix.shell().info("Generated #{path}")
  catch
    :skip -> :ok
  end

  defp generate_events_module(mod, _rules, local_rules) do
    events = extract_events(mod, local_rules)
    if events == [], do: throw(:skip)

    snake = to_snake(mod)
    camel = to_module_name(mod)

    event_list =
      events
      |> Enum.map(fn {method, _params_ref} -> ~s("#{method}") end)
      |> Enum.join(",\n      ")

    event_functions =
      events
      |> Enum.map(fn {method, params_ref} ->
        fun_name = method |> String.split(".") |> List.last() |> to_snake()

        """
          @doc \"\"\"
          Event: `#{method}`

          Params type: `#{params_ref || "none"}`
          \"\"\"
          def #{fun_name}, do: "#{method}"
        """
      end)
      |> Enum.join("\n")

    content = """
    # Generated by mix bibbidi.gen — do not edit manually
    defmodule Bibbidi.Events.#{camel} do
      @moduledoc \"\"\"
      Events for the `#{mod}` module of the WebDriver BiDi protocol.
      \"\"\"

      @doc "Returns all event method names for this module."
      @spec events() :: [String.t()]
      def events do
        [
          #{event_list}
        ]
      end

    #{event_functions}end
    """

    path = "lib/bibbidi/events/#{snake}.ex"
    File.mkdir_p!(Path.dirname(path))
    File.write!(path, content)
    Mix.shell().info("Generated #{path}")
  catch
    :skip -> :ok
  end

  defp extract_types(rules) do
    Enum.reject(rules, fn {name, def} ->
      # Skip command definitions (groups with method + params) and top-level dispatchers
      is_command_def?(def) or is_event_def?(def) or
        String.ends_with?(name, "Command") or String.ends_with?(name, "Event")
    end)
  end

  defp extract_events(mod, local_rules) do
    local_rules
    |> Enum.filter(fn {name, def} ->
      String.starts_with?(name, mod <> ".") and is_event_def?(def)
    end)
    |> Enum.map(fn {_name, {:group, members}} ->
      method =
        Enum.find_value(members, fn
          {:required, "method", {:string, m}} -> m
          _ -> nil
        end)

      params_ref =
        Enum.find_value(members, fn
          {:required, "params", {:ref, r}} -> r
          _ -> nil
        end)

      {method, params_ref}
    end)
    |> Enum.reject(fn {method, _} -> is_nil(method) end)
  end

  defp is_command_def?({:group, members}) do
    Enum.any?(members, fn
      {:required, "method", {:string, _}} -> true
      _ -> false
    end) and
      Enum.any?(members, fn
        {:required, "params", _} -> true
        _ -> false
      end)
  end

  defp is_command_def?(_), do: false

  defp is_event_def?({:group, members}) do
    has_method =
      Enum.any?(members, fn
        {:required, "method", {:string, m}} -> not String.ends_with?(m, "Command")
        _ -> false
      end)

    has_method and is_command_def?({:group, members})
  end

  defp is_event_def?(_), do: false

  defp generate_type(name, definition) do
    short = name |> String.split(".") |> List.last()
    type_name = to_snake(short) |> String.to_atom()
    type_str = type_to_spec(definition)

    "  @type #{type_name} :: #{type_str}"
  end

  defp type_to_spec({:primitive, :text}), do: "String.t()"
  defp type_to_spec({:primitive, :text, _constraint}), do: "String.t()"
  defp type_to_spec({:primitive, :uint}), do: "non_neg_integer()"
  defp type_to_spec({:primitive, :uint, _constraint}), do: "non_neg_integer()"
  defp type_to_spec({:primitive, :int}), do: "integer()"
  defp type_to_spec({:primitive, :int, _constraint}), do: "integer()"
  defp type_to_spec({:primitive, :float}), do: "float()"
  defp type_to_spec({:primitive, :float, _constraint}), do: "float()"
  defp type_to_spec({:primitive, :bool}), do: "boolean()"
  defp type_to_spec({:primitive, :bool, _constraint}), do: "boolean()"
  defp type_to_spec({:primitive, :any}), do: "term()"
  defp type_to_spec({:primitive, :null}), do: "nil"
  defp type_to_spec({:string, _}), do: "String.t()"
  defp type_to_spec({:ref, name}), do: ref_type(name)
  defp type_to_spec({:number, n}) when is_integer(n), do: "integer()"
  defp type_to_spec({:number, n}) when is_float(n), do: "float()"
  defp type_to_spec({:range, _low, _high}), do: "integer()"
  defp type_to_spec({:range_exclusive, _low, _high}), do: "integer()"

  defp type_to_spec({:choice, items}) do
    items
    |> Enum.map(&type_to_spec/1)
    |> Enum.uniq()
    |> Enum.join(" | ")
  end

  defp type_to_spec({:array, inner, _quantifier}), do: "[#{type_to_spec(inner)}]"
  defp type_to_spec({:tuple, items}), do: "{#{Enum.map_join(items, ", ", &type_to_spec/1)}}"

  defp type_to_spec({:map, [{:fields, fields}]}) do
    field_specs =
      fields
      |> Enum.map(fn
        {:required, _key, type} -> "String.t() => #{type_to_spec(type)}"
        {:optional, _key, type} -> "optional(String.t()) => #{type_to_spec(type)}"
        {:extensible, _k, _v} -> "optional(String.t()) => term()"
        {:embed, _name} -> nil
        {:group_choice, _} -> nil
      end)
      |> Enum.reject(&is_nil/1)
      |> Enum.uniq()
      |> Enum.join(", ")

    "%{#{field_specs}}"
  end

  defp type_to_spec({:map, [{:group_choice, _groups}]}), do: "map()"
  defp type_to_spec({:map, []}), do: "map()"

  defp type_to_spec({:group, members}) do
    field_specs =
      members
      |> Enum.map(fn
        {:required, _key, type} -> "String.t() => #{type_to_spec(type)}"
        {:optional, _key, type} -> "optional(String.t()) => #{type_to_spec(type)}"
        {:embed, _name} -> nil
        {:optional_embed, _} -> nil
        _ -> nil
      end)
      |> Enum.reject(&is_nil/1)
      |> Enum.uniq()
      |> Enum.join(", ")

    "%{#{field_specs}}"
  end

  defp type_to_spec({:group_choice, _}), do: "map()"
  defp type_to_spec(_), do: "term()"

  # Well-known global types and literals
  @global_types %{
    "true" => "true",
    "false" => "false",
    "null" => "nil",
    "js-uint" => "non_neg_integer()",
    "js-int" => "integer()",
    "Extensible" => "map()"
  }

  defp ref_type(name) do
    case Map.get(@global_types, name) do
      nil ->
        if String.contains?(name, ".") do
          [mod, type] = String.split(name, ".", parts: 2)
          "Bibbidi.Types.#{to_module_name(mod)}.#{to_snake(type)}()"
        else
          # Unknown global type — use term()
          "term()"
        end

      resolved ->
        resolved
    end
  end

  defp to_snake(str) do
    str
    |> String.replace(~r/([a-z])([A-Z])/, "\\1_\\2")
    |> String.replace(~r/([A-Z]+)([A-Z][a-z])/, "\\1_\\2")
    |> String.replace("-", "_")
    |> String.downcase()
  end

  defp to_module_name(mod) do
    mod
    |> String.split(~r/[_-]/)
    |> Enum.map(&String.capitalize/1)
    |> Enum.join()
    |> then(fn
      "Browsingcontext" -> "BrowsingContext"
      "Webextension" -> "WebExtension"
      other -> other
    end)
  end
end
