defmodule Bibbidi.CDDL.Generator do
  @moduledoc false

  alias Bibbidi.CDDL.Parser
  alias Bibbidi.CDDL.Utils

  @modules ~w(browsingContext script session browser network log storage input emulation webExtension)

  @doc """
  Builds an `%Igniter{}` with all generated types, events, and command modules.

  Returns the igniter struct — the caller decides whether to apply or dry-run.
  """
  @spec run(Igniter.t()) :: Igniter.t()
  def run(igniter) do
    {:ok, remote_rules} = Parser.parse_file("priv/cddl/remote.cddl")
    {:ok, local_rules} = Parser.parse_file("priv/cddl/local.cddl")

    all_rules = remote_rules ++ local_rules
    grouped = group_by_module(all_rules)

    Enum.reduce(@modules, igniter, fn mod, igniter ->
      rules = Map.get(grouped, mod, [])

      igniter
      |> maybe_generate_types_module(mod, rules)
      |> maybe_generate_events_module(mod, rules, local_rules)
      |> maybe_generate_command_modules(mod, remote_rules, all_rules)
      |> maybe_generate_facade_module(mod, remote_rules, all_rules)
    end)
  end

  defp group_by_module(rules) do
    rules
    |> Enum.filter(fn {name, _} -> String.contains?(name, ".") end)
    |> Enum.group_by(fn {name, _} -> name |> String.split(".") |> hd() end)
  end

  defp maybe_generate_types_module(igniter, mod, rules) do
    types = extract_types(rules)
    if types == [], do: igniter, else: generate_types_module(igniter, mod, types)
  end

  defp generate_types_module(igniter, mod, types) do
    snake = to_snake(mod)
    camel = to_module_name(mod)

    type_entries =
      types
      |> Enum.map(fn {name, def} -> generate_type(name, def) end)
      |> Enum.reject(&is_nil/1)
      |> Enum.uniq_by(fn {type_name, _, _} -> type_name end)

    schema_defs =
      type_entries
      |> Enum.map(fn {type_name, _type_str, schema_str} ->
        "  @#{type_name}_schema #{schema_str}\n  @type #{type_name} :: unquote(Zoi.type_spec(@#{type_name}_schema))"
      end)
      |> Enum.join("\n\n")

    schema_funs =
      type_entries
      |> Enum.map(fn {type_name, _type_str, _schema_str} ->
        """
          @doc "Returns the Zoi schema for `#{type_name}`."
          def #{type_name}, do: @#{type_name}_schema
        """
      end)
      |> Enum.join("\n")

    content = """
    # Generated by mix bibbidi.gen — do not edit manually
    defmodule Bibbidi.Types.#{camel} do
      @moduledoc \"\"\"
      Type definitions and Zoi schemas for the `#{mod}` module of the WebDriver BiDi protocol.

      Each type has:
      - A `@type` spec derived from the Zoi schema (for Dialyzer)
      - A function returning the Zoi schema (for runtime validation)
      \"\"\"

    #{schema_defs}

    #{schema_funs}end
    """

    path = "lib/bibbidi/types/#{snake}.ex"

    Igniter.create_new_file(igniter, path, content, on_exists: :overwrite)
  end

  defp maybe_generate_events_module(igniter, mod, _rules, local_rules) do
    events = extract_events(mod, local_rules)
    if events == [], do: igniter, else: generate_events_module(igniter, mod, events)
  end

  defp generate_events_module(igniter, mod, events) do
    snake = to_snake(mod)
    camel = to_module_name(mod)

    event_list =
      events
      |> Enum.map(fn {method, _params_ref} -> ~s("#{method}") end)
      |> Enum.join(",\n      ")

    event_functions =
      events
      |> Enum.map(fn {method, params_ref} ->
        fun_name = method |> String.split(".") |> List.last() |> to_snake()

        """
          @doc \"\"\"
          Event: `#{method}`

          Params type: `#{params_ref || "none"}`
          \"\"\"
          def #{fun_name}, do: "#{method}"
        """
      end)
      |> Enum.join("\n")

    content = """
    # Generated by mix bibbidi.gen — do not edit manually
    defmodule Bibbidi.Events.#{camel} do
      @moduledoc \"\"\"
      Events for the `#{mod}` module of the WebDriver BiDi protocol.
      \"\"\"

      @doc "Returns all event method names for this module."
      @spec events() :: [String.t()]
      def events do
        [
          #{event_list}
        ]
      end

    #{event_functions}end
    """

    path = "lib/bibbidi/events/#{snake}.ex"

    Igniter.create_new_file(igniter, path, content, on_exists: :overwrite)
  end

  defp extract_types(rules) do
    Enum.reject(rules, fn {name, def} ->
      # Skip command definitions (groups with method + params) and top-level dispatchers
      Utils.command_def?(def) or is_event_def?(def) or
        String.ends_with?(name, "Command") or String.ends_with?(name, "Event")
    end)
  end

  defp extract_events(mod, local_rules) do
    local_rules
    |> Enum.filter(fn {name, def} ->
      String.starts_with?(name, mod <> ".") and is_event_def?(def)
    end)
    |> Enum.map(fn {_name, {:group, members}} ->
      method =
        Enum.find_value(members, fn
          {:required, "method", {:string, m}} -> m
          _ -> nil
        end)

      params_ref =
        Enum.find_value(members, fn
          {:required, "params", {:ref, r}} -> r
          _ -> nil
        end)

      {method, params_ref}
    end)
    |> Enum.reject(fn {method, _} -> is_nil(method) end)
  end

  # ── Command struct generation ─────────────────────────────────────

  defp maybe_generate_command_modules(igniter, mod, remote_rules, all_rules) do
    commands = extract_commands(mod, remote_rules)
    if commands == [], do: igniter, else: generate_command_modules(igniter, mod, commands, all_rules)
  end

  defp extract_commands(mod, remote_rules) do
    remote_rules
    |> Enum.filter(fn {name, def} ->
      String.starts_with?(name, mod <> ".") and Utils.command_def?(def)
    end)
    |> Enum.map(fn {name, {:group, members}} ->
      command_name = name |> String.split(".") |> List.last()

      method =
        Enum.find_value(members, fn
          {:required, "method", {:string, m}} -> m
          _ -> nil
        end)

      params_ref =
        Enum.find_value(members, fn
          {:required, "params", {:ref, r}} -> r
          _ -> nil
        end)

      {command_name, method, params_ref}
    end)
    |> Enum.reject(fn {_, method, _} -> is_nil(method) end)
  end

  defp generate_command_modules(igniter, mod, commands, all_rules) do
    Enum.reduce(commands, igniter, fn {command_name, method, params_ref}, igniter ->
      generate_command_module(igniter, mod, command_name, method, params_ref, all_rules)
    end)
  end

  defp generate_command_module(igniter, mod, command_name, method, params_ref, all_rules) do
    snake_mod = to_snake(mod)
    camel_mod = to_module_name(mod)
    command_snake = to_snake(command_name)

    fields = resolve_command_fields(params_ref, all_rules)

    required = Enum.filter(fields, fn {_, _, req} -> req == :required end)
    optional = Enum.filter(fields, fn {_, _, req} -> req == :optional end)
    all_fields = required ++ optional

    enforce_keys_line =
      case required do
        [] ->
          ""

        _ ->
          keys = Enum.map_join(required, ", ", fn {_, elixir, _} -> ":#{elixir}" end)
          "@enforce_keys [#{keys}]\n  "
      end

    struct_fields = Enum.map_join(all_fields, ", ", fn {_, elixir, _} -> ":#{elixir}" end)
    params_body = generate_params_body(required, optional)

    content = """
    # Generated by mix bibbidi.gen — do not edit manually
    defmodule Bibbidi.Commands.#{camel_mod}.#{command_name} do
      @moduledoc \"\"\"
      Command struct for `#{method}`.
      \"\"\"

      #{enforce_keys_line}defstruct [#{struct_fields}]

      defimpl Bibbidi.Encodable do
        def method(_), do: "#{method}"

    #{params_body}
      end
    end
    """

    path = "lib/bibbidi/commands/#{snake_mod}/#{command_snake}.ex"
    Igniter.create_new_file(igniter, path, content, on_exists: :overwrite)
  end

  @doc """
  Resolves a CDDL params reference into a list of `{json_key, elixir_key, :required | :optional}` tuples.

  Used by the code generator and by `mix bibbidi.cddl.inspect --fields`.
  """
  def resolve_command_fields(nil, _all_rules), do: []
  def resolve_command_fields("EmptyParams", _all_rules), do: []

  def resolve_command_fields(ref, all_rules) do
    case List.keyfind(all_rules, ref, 0) do
      {^ref, {:map, content}} ->
        extract_field_defs_from_map(content)

      {^ref, {:group, members}} ->
        extract_field_defs(members)

      {^ref, {:choice, alternatives}} ->
        # For choice types, merge fields from all alternatives (all optional)
        resolve_choice_fields(alternatives, all_rules)

      _ ->
        []
    end
  end

  defp extract_field_defs_from_map(content) do
    Enum.flat_map(content, fn
      {:fields, fields} -> extract_field_defs(fields)
      {:group_choice, groups} -> extract_field_defs_from_group_choice(groups)
      _ -> []
    end)
  end

  defp extract_field_defs_from_group_choice(groups) do
    # For group choices inside maps (e.g. coordinates // error),
    # include all fields as optional since only one branch is used at a time
    Enum.flat_map(groups, fn
      {:fields, fields} ->
        Enum.flat_map(fields, fn
          {:required, name, _type} -> [{name, to_snake(name), :optional}]
          {:optional, name, _type} -> [{name, to_snake(name), :optional}]
          _ -> []
        end)

      {:group, members} ->
        Enum.flat_map(members, fn
          {:required, name, _type} -> [{name, to_snake(name), :optional}]
          {:optional, name, _type} -> [{name, to_snake(name), :optional}]
          _ -> []
        end)

      _ ->
        []
    end)
  end

  defp resolve_choice_fields(alternatives, all_rules) do
    # Resolve each alternative ref and merge all fields as optional
    Enum.flat_map(alternatives, fn
      {:ref, ref} ->
        resolve_command_fields(ref, all_rules)
        |> Enum.map(fn {json, elixir, _} -> {json, elixir, :optional} end)

      _ ->
        []
    end)
    |> Enum.uniq_by(fn {json, _, _} -> json end)
  end

  defp extract_field_defs(fields) do
    Enum.flat_map(fields, fn
      {:required, name, _type} ->
        [{name, to_snake(name), :required}]

      {:optional, name, _type} ->
        [{name, to_snake(name), :optional}]

      {:group_choice, groups} ->
        extract_field_defs_from_group_choice(groups)

      _ ->
        []
    end)
  end

  defp generate_params_body([], []) do
    "    def params(_cmd), do: %{}"
  end

  defp generate_params_body(required, []) do
    fields =
      Enum.map_join(required, ", ", fn {json_key, elixir_key, _} ->
        "#{json_key}: cmd.#{elixir_key}"
      end)

    "    def params(cmd), do: %{#{fields}}"
  end

  defp generate_params_body(required, optional) do
    required_map =
      if required == [] do
        "%{}"
      else
        fields =
          Enum.map_join(required, ", ", fn {json_key, elixir_key, _} ->
            "#{json_key}: cmd.#{elixir_key}"
          end)

        "%{#{fields}}"
      end

    optional_entries =
      Enum.map_join(optional, ",\n        ", fn {json_key, elixir_key, _} ->
        "{:#{json_key}, cmd.#{elixir_key}}"
      end)

    """
        def params(cmd) do
          optional = [
            #{optional_entries}
          ]

          Enum.reduce(optional, #{required_map}, fn
            {_key, nil}, acc -> acc
            {key, value}, acc -> Map.put(acc, key, value)
          end)
        end
    """
  end

  # ── Predicate helpers ───────────────────────────────────────────────

  defp is_event_def?({:group, members}) do
    has_method =
      Enum.any?(members, fn
        {:required, "method", {:string, m}} -> not String.ends_with?(m, "Command")
        _ -> false
      end)

    has_method and Utils.command_def?({:group, members})
  end

  defp is_event_def?(_), do: false

  defp generate_type(name, definition) do
    short = name |> String.split(".") |> List.last()
    type_name = to_snake(short)
    type_str = type_to_spec(definition)
    schema_str = type_to_schema(definition)

    {type_name, type_str, schema_str}
  end

  # ── Zoi schema generation ─────────────────────────────────────────

  defp type_to_schema({:primitive, :text}), do: "Zoi.string()"
  defp type_to_schema({:primitive, :text, _}), do: "Zoi.string()"
  defp type_to_schema({:primitive, :uint}), do: "Zoi.integer() |> Zoi.min(0)"
  defp type_to_schema({:primitive, :uint, _}), do: "Zoi.integer() |> Zoi.min(0)"
  defp type_to_schema({:primitive, :int}), do: "Zoi.integer()"
  defp type_to_schema({:primitive, :int, _}), do: "Zoi.integer()"
  defp type_to_schema({:primitive, :float}), do: "Zoi.float()"
  defp type_to_schema({:primitive, :float, _}), do: "Zoi.float()"
  defp type_to_schema({:primitive, :bool}), do: "Zoi.boolean()"
  defp type_to_schema({:primitive, :bool, _}), do: "Zoi.boolean()"
  defp type_to_schema({:primitive, :any}), do: "Zoi.any()"
  defp type_to_schema({:primitive, :null}), do: "Zoi.null()"
  defp type_to_schema({:string, _}), do: "Zoi.string()"
  defp type_to_schema({:number, n}) when is_integer(n), do: "Zoi.integer()"
  defp type_to_schema({:number, n}) when is_float(n), do: "Zoi.float()"
  defp type_to_schema({:range, low, high}), do: "Zoi.integer() |> Zoi.min(#{low}) |> Zoi.max(#{high})"
  defp type_to_schema({:range_exclusive, _low, _high}), do: "Zoi.integer()"
  defp type_to_schema({:ref, _name}), do: "Zoi.any()"
  defp type_to_schema({:array, inner, _q}), do: "Zoi.list(#{type_to_schema(inner)})"

  defp type_to_schema({:choice, items}) do
    schemas = Enum.map(items, &type_to_schema/1)
    "Zoi.union([#{Enum.join(schemas, ", ")}])"
  end

  defp type_to_schema({:map, [{:fields, fields}]}) do
    field_schemas =
      fields
      |> Enum.map(fn
        {:required, key, type} -> "#{to_snake(key)}: #{type_to_schema(type)}"
        {:optional, key, type} -> "#{to_snake(key)}: #{type_to_schema(type)} |> Zoi.optional()"
        {:extensible, _, _} -> nil
        {:embed, _} -> nil
        {:group_choice, _} -> nil
      end)
      |> Enum.reject(&is_nil/1)
      |> Enum.join(", ")

    "Zoi.map(%{#{field_schemas}})"
  end

  defp type_to_schema({:map, _}), do: "Zoi.map(Zoi.string(), Zoi.any())"
  defp type_to_schema({:group, _}), do: "Zoi.map(Zoi.string(), Zoi.any())"
  defp type_to_schema({:tuple, items}), do: "Zoi.tuple({#{Enum.map_join(items, ", ", &type_to_schema/1)}})"
  defp type_to_schema({:group_choice, _}), do: "Zoi.any()"
  defp type_to_schema(_), do: "Zoi.any()"

  # ── Typespec generation ──────────────────────────────────────────

  defp type_to_spec({:primitive, :text}), do: "String.t()"
  defp type_to_spec({:primitive, :text, _constraint}), do: "String.t()"
  defp type_to_spec({:primitive, :uint}), do: "non_neg_integer()"
  defp type_to_spec({:primitive, :uint, _constraint}), do: "non_neg_integer()"
  defp type_to_spec({:primitive, :int}), do: "integer()"
  defp type_to_spec({:primitive, :int, _constraint}), do: "integer()"
  defp type_to_spec({:primitive, :float}), do: "float()"
  defp type_to_spec({:primitive, :float, _constraint}), do: "float()"
  defp type_to_spec({:primitive, :bool}), do: "boolean()"
  defp type_to_spec({:primitive, :bool, _constraint}), do: "boolean()"
  defp type_to_spec({:primitive, :any}), do: "term()"
  defp type_to_spec({:primitive, :null}), do: "nil"
  defp type_to_spec({:string, _}), do: "String.t()"
  defp type_to_spec({:ref, name}), do: ref_type(name)
  defp type_to_spec({:number, n}) when is_integer(n), do: "integer()"
  defp type_to_spec({:number, n}) when is_float(n), do: "float()"
  defp type_to_spec({:range, _low, _high}), do: "integer()"
  defp type_to_spec({:range_exclusive, _low, _high}), do: "integer()"

  defp type_to_spec({:choice, items}) do
    items
    |> Enum.map(&type_to_spec/1)
    |> Enum.uniq()
    |> Enum.join(" | ")
  end

  defp type_to_spec({:array, inner, _quantifier}), do: "[#{type_to_spec(inner)}]"
  defp type_to_spec({:tuple, items}), do: "{#{Enum.map_join(items, ", ", &type_to_spec/1)}}"

  defp type_to_spec({:map, [{:fields, fields}]}) do
    field_specs =
      fields
      |> Enum.map(fn
        {:required, _key, type} -> "String.t() => #{type_to_spec(type)}"
        {:optional, _key, type} -> "optional(String.t()) => #{type_to_spec(type)}"
        {:extensible, _k, _v} -> "optional(String.t()) => term()"
        {:embed, _name} -> nil
        {:group_choice, _} -> nil
      end)
      |> Enum.reject(&is_nil/1)
      |> Enum.uniq()
      |> Enum.join(", ")

    "%{#{field_specs}}"
  end

  defp type_to_spec({:map, [{:group_choice, _groups}]}), do: "map()"
  defp type_to_spec({:map, []}), do: "map()"

  defp type_to_spec({:group, members}) do
    field_specs =
      members
      |> Enum.map(fn
        {:required, _key, type} -> "String.t() => #{type_to_spec(type)}"
        {:optional, _key, type} -> "optional(String.t()) => #{type_to_spec(type)}"
        {:embed, _name} -> nil
        {:optional_embed, _} -> nil
        _ -> nil
      end)
      |> Enum.reject(&is_nil/1)
      |> Enum.uniq()
      |> Enum.join(", ")

    "%{#{field_specs}}"
  end

  defp type_to_spec({:group_choice, _}), do: "map()"
  defp type_to_spec(_), do: "term()"

  # Well-known global types and literals
  @global_types %{
    "true" => "true",
    "false" => "false",
    "null" => "nil",
    "js-uint" => "non_neg_integer()",
    "js-int" => "integer()",
    "Extensible" => "map()"
  }

  defp ref_type(name) do
    case Map.get(@global_types, name) do
      nil ->
        if String.contains?(name, ".") do
          [mod, type] = String.split(name, ".", parts: 2)
          "Bibbidi.Types.#{to_module_name(mod)}.#{to_snake(type)}()"
        else
          # Unknown global type — use term()
          "term()"
        end

      resolved ->
        resolved
    end
  end

  # ── Facade module generation ──────────────────────────────────────

  defp maybe_generate_facade_module(igniter, mod, remote_rules, all_rules) do
    commands = extract_commands(mod, remote_rules)
    if commands == [], do: igniter, else: generate_facade_module(igniter, mod, commands, all_rules)
  end

  defp generate_facade_module(igniter, mod, commands, all_rules) do
    snake = to_snake(mod)
    camel = to_module_name(mod)

    functions =
      commands
      |> Enum.map(fn {command_name, method, params_ref} ->
        generate_facade_function(camel, command_name, method, params_ref, all_rules)
      end)
      |> Enum.join("\n")

    session_note =
      if mod == "session" do
        "\n\n  See also `Bibbidi.Session` for a higher-level convenience API."
      else
        ""
      end

    content = """
    # Generated by mix bibbidi.gen — do not edit manually
    defmodule Bibbidi.Commands.#{camel} do
      @moduledoc \"\"\"
      Command builders for the `#{mod}` module of the WebDriver BiDi protocol.#{session_note}
      \"\"\"

      alias Bibbidi.Connection

    #{functions}end
    """

    path = "lib/bibbidi/commands/#{snake}.ex"
    Igniter.create_new_file(igniter, path, content, on_exists: :overwrite)
  end

  # Elixir reserved words that can't be function names
  @reserved_words ~w(end do fn if else case cond for receive try raise rescue after catch with)

  defp generate_facade_function(_camel_mod, command_name, method, params_ref, all_rules) do
    raw_name = to_snake(command_name)

    fun_name =
      if raw_name in @reserved_words do
        # Derive a safe name from the BiDi module prefix + command name
        mod_prefix = method |> String.split(".") |> hd()
        to_snake(mod_prefix) <> "_" <> raw_name
      else
        raw_name
      end

    fields = resolve_command_fields(params_ref, all_rules)

    required = Enum.filter(fields, fn {_, _, req} -> req == :required end)
    optional = Enum.filter(fields, fn {_, _, req} -> req == :optional end)

    # Build the function signature
    required_args = Enum.map_join(required, ", ", fn {_, elixir, _} -> elixir end)

    args_str =
      case {required_args, optional} do
        {"", []} -> "conn"
        {"", _} -> "conn, opts \\\\ []"
        {r, []} -> "conn, #{r}"
        {r, _} -> "conn, #{r}, opts \\\\ []"
      end

    # Build the struct fields
    struct_assignments =
      (required ++ optional)
      |> Enum.map(fn
        {_, elixir, :required} -> "      #{elixir}: #{elixir}"
        {_, elixir, :optional} -> "      #{elixir}: opts[:#{elixir}]"
      end)
      |> Enum.join(",\n")

    struct_body =
      if struct_assignments == "" do
        "%__MODULE__.#{command_name}{}"
      else
        "%__MODULE__.#{command_name}{\n#{struct_assignments}\n    }"
      end

    # Build the @spec
    spec_args =
      case {required, optional} do
        {[], []} -> "GenServer.server()"
        {[], _} -> "GenServer.server(), keyword()"
        {r, []} -> "GenServer.server(), #{Enum.map_join(r, ", ", fn _ -> "term()" end)}"
        {r, _} -> "GenServer.server(), #{Enum.map_join(r, ", ", fn _ -> "term()" end)}, keyword()"
      end

    """
      @doc "Executes the `#{method}` command."
      @spec #{fun_name}(#{spec_args}) :: {:ok, map()} | {:error, term()}
      def #{fun_name}(#{args_str}) do
        Connection.execute(conn, #{struct_body})
      end
    """
  end

  defdelegate to_snake(str), to: Utils
  defdelegate to_module_name(str), to: Utils
end
