# Generated by mix bibbidi.gen — do not edit manually
defmodule Bibbidi.Types.Storage.BrowsingContextPartitionDescriptor do
  @moduledoc """
  `storage.BrowsingContextPartitionDescriptor`

  ## Fields

  - `type` - `"context"` (required)
  - `context` - `t:Bibbidi.Types.BrowsingContext.t/0` (required)
  """

  @schema Zoi.map(%{
            type: Zoi.string(),
            context: Zoi.lazy({Bibbidi.Types.BrowsingContext, :schema, []})
          })
  @type t :: %{type: String.t(), context: Bibbidi.Types.BrowsingContext.t()}

  @doc "Returns the Zoi schema for this type."
  def schema, do: @schema
end
