# Generated by mix bibbidi.gen — do not edit manually
defmodule Bibbidi.Types.Storage.PartitionDescriptor do
  @moduledoc """
  `storage.PartitionDescriptor`

  One of:
  - `t:Bibbidi.Types.Storage.BrowsingContextPartitionDescriptor.t/0`
  - `t:Bibbidi.Types.Storage.StorageKeyPartitionDescriptor.t/0`
  """

  @schema Zoi.union([
            Zoi.lazy({Bibbidi.Types.Storage.BrowsingContextPartitionDescriptor, :schema, []}),
            Zoi.lazy({Bibbidi.Types.Storage.StorageKeyPartitionDescriptor, :schema, []})
          ])
  @type t ::
          Bibbidi.Types.Storage.BrowsingContextPartitionDescriptor.t()
          | Bibbidi.Types.Storage.StorageKeyPartitionDescriptor.t()

  @doc "Returns the Zoi schema for this type."
  def schema, do: @schema
end
