# Generated by mix bibbidi.gen — do not edit manually
defmodule Bibbidi.Types.Storage.StorageKeyPartitionDescriptor do
  @moduledoc """
  `storage.StorageKeyPartitionDescriptor`

  ## Fields

  - `type` - `"storageKey"` (required)
  - `user_context` - `String.t()` (optional)
  - `source_origin` - `String.t()` (optional)
  """

  @schema Zoi.map(%{
            type: Zoi.string(),
            user_context: Zoi.string() |> Zoi.optional(),
            source_origin: Zoi.string() |> Zoi.optional()
          })
  @type t :: %{type: String.t(), user_context: String.t() | nil, source_origin: String.t() | nil}

  @doc "Returns the Zoi schema for this type."
  def schema, do: @schema
end
