# Generated by mix bibbidi.gen — do not edit manually
defmodule Bibbidi.Types.Network.AuthCredentials do
  @moduledoc """
  `network.AuthCredentials`

  ## Fields

  - `type` - `"password"` (required)
  - `username` - `String.t()` (required)
  - `password` - `String.t()` (required)
  """

  @schema Zoi.map(%{type: Zoi.string(), username: Zoi.string(), password: Zoi.string()})
  @type t :: %{type: String.t(), username: String.t(), password: String.t()}

  @doc "Returns the Zoi schema for this type."
  def schema, do: @schema
end
