# Generated by mix bibbidi.gen — do not edit manually
defmodule Bibbidi.Types.Network.BytesValue do
  @moduledoc """
  `network.BytesValue`

  One of:
  - `t:Bibbidi.Types.Network.StringValue.t/0`
  - `t:Bibbidi.Types.Network.Base64value.t/0`
  """

  @schema Zoi.union([
            Zoi.lazy({Bibbidi.Types.Network.StringValue, :schema, []}),
            Zoi.lazy({Bibbidi.Types.Network.Base64value, :schema, []})
          ])
  @type t :: Bibbidi.Types.Network.StringValue.t() | Bibbidi.Types.Network.Base64value.t()

  @doc "Returns the Zoi schema for this type."
  def schema, do: @schema
end
