# Generated by mix bibbidi.gen — do not edit manually
defmodule Bibbidi.Types.Network.Cookie do
  @moduledoc """
  `network.Cookie`

  ## Fields

  - `name` - `String.t()` (required)
  - `value` - `t:Bibbidi.Types.Network.BytesValue.t/0` (required)
  - `domain` - `String.t()` (required)
  - `path` - `String.t()` (required)
  - `size` - `t:Bibbidi.Types.JsUint.t/0` (required)
  - `http_only` - `boolean()` (required)
  - `secure` - `boolean()` (required)
  - `same_site` - `t:Bibbidi.Types.Network.SameSite.t/0` (required)
  - `expiry` - `t:Bibbidi.Types.JsUint.t/0` (optional)
  """

  @schema Zoi.map(%{
            name: Zoi.string(),
            value: Zoi.lazy({Bibbidi.Types.Network.BytesValue, :schema, []}),
            domain: Zoi.string(),
            path: Zoi.string(),
            size: Zoi.lazy({Bibbidi.Types.JsUint, :schema, []}),
            http_only: Zoi.boolean(),
            secure: Zoi.boolean(),
            same_site: Zoi.lazy({Bibbidi.Types.Network.SameSite, :schema, []}),
            expiry: Zoi.lazy({Bibbidi.Types.JsUint, :schema, []}) |> Zoi.optional()
          })
  @type t :: %{
          name: String.t(),
          value: Bibbidi.Types.Network.BytesValue.t(),
          domain: String.t(),
          path: String.t(),
          size: Bibbidi.Types.JsUint.t(),
          http_only: boolean(),
          secure: boolean(),
          same_site: Bibbidi.Types.Network.SameSite.t(),
          expiry: Bibbidi.Types.JsUint.t() | nil
        }

  @doc "Returns the Zoi schema for this type."
  def schema, do: @schema
end
