# Generated by mix bibbidi.gen — do not edit manually
defmodule Bibbidi.Types.Network.DataType do
  @moduledoc """
  `network.DataType`

  Values: `request`, `response`
  """

  @schema Zoi.enum(["request", "response"])
  @type t :: String.t()
  @values ~w(request response)

  @doc "Returns the Zoi schema for this type."
  def schema, do: @schema

  @doc "Returns the list of valid values."
  def values, do: @values
end
