# Generated by mix bibbidi.gen — do not edit manually
defmodule Bibbidi.Types.Network.FetchTimingInfo do
  @moduledoc """
  `network.FetchTimingInfo`

  ## Fields

  - `time_origin` - `float()` (required)
  - `request_time` - `float()` (required)
  - `redirect_start` - `float()` (required)
  - `redirect_end` - `float()` (required)
  - `fetch_start` - `float()` (required)
  - `dns_start` - `float()` (required)
  - `dns_end` - `float()` (required)
  - `connect_start` - `float()` (required)
  - `connect_end` - `float()` (required)
  - `tls_start` - `float()` (required)
  - `request_start` - `float()` (required)
  - `response_start` - `float()` (required)
  - `response_end` - `float()` (required)
  """

  @schema Zoi.map(%{
            time_origin: Zoi.float(),
            request_time: Zoi.float(),
            redirect_start: Zoi.float(),
            redirect_end: Zoi.float(),
            fetch_start: Zoi.float(),
            dns_start: Zoi.float(),
            dns_end: Zoi.float(),
            connect_start: Zoi.float(),
            connect_end: Zoi.float(),
            tls_start: Zoi.float(),
            request_start: Zoi.float(),
            response_start: Zoi.float(),
            response_end: Zoi.float()
          })
  @type t :: %{
          time_origin: float(),
          request_time: float(),
          redirect_start: float(),
          redirect_end: float(),
          fetch_start: float(),
          dns_start: float(),
          dns_end: float(),
          connect_start: float(),
          connect_end: float(),
          tls_start: float(),
          request_start: float(),
          response_start: float(),
          response_end: float()
        }

  @doc "Returns the Zoi schema for this type."
  def schema, do: @schema
end
