# Generated by mix bibbidi.gen — do not edit manually
defmodule Bibbidi.Types.Network.Header do
  @moduledoc """
  `network.Header`

  ## Fields

  - `name` - `String.t()` (required)
  - `value` - `t:Bibbidi.Types.Network.BytesValue.t/0` (required)
  """

  @schema Zoi.map(%{
            name: Zoi.string(),
            value: Zoi.lazy({Bibbidi.Types.Network.BytesValue, :schema, []})
          })
  @type t :: %{name: String.t(), value: Bibbidi.Types.Network.BytesValue.t()}

  @doc "Returns the Zoi schema for this type."
  def schema, do: @schema
end
