# Generated by mix bibbidi.gen — do not edit manually
defmodule Bibbidi.Types.Network.Initiator do
  @moduledoc """
  `network.Initiator`

  ## Fields

  - `column_number` - `t:Bibbidi.Types.JsUint.t/0` (optional)
  - `line_number` - `t:Bibbidi.Types.JsUint.t/0` (optional)
  - `request` - `t:Bibbidi.Types.Network.Request.t/0` (optional)
  - `stack_trace` - `t:Bibbidi.Types.Script.StackTrace.t/0` (optional)
  - `type` - `"parser"` or `"script"` or `"preflight"` or `"other"` (optional)
  """

  @schema Zoi.map(%{
            column_number: Zoi.lazy({Bibbidi.Types.JsUint, :schema, []}) |> Zoi.optional(),
            line_number: Zoi.lazy({Bibbidi.Types.JsUint, :schema, []}) |> Zoi.optional(),
            request: Zoi.lazy({Bibbidi.Types.Network.Request, :schema, []}) |> Zoi.optional(),
            stack_trace:
              Zoi.lazy({Bibbidi.Types.Script.StackTrace, :schema, []}) |> Zoi.optional(),
            type:
              Zoi.union([Zoi.string(), Zoi.string(), Zoi.string(), Zoi.string()])
              |> Zoi.optional()
          })
  @type t :: %{
          column_number: Bibbidi.Types.JsUint.t() | nil,
          line_number: Bibbidi.Types.JsUint.t() | nil,
          request: Bibbidi.Types.Network.Request.t() | nil,
          stack_trace: Bibbidi.Types.Script.StackTrace.t() | nil,
          type: String.t() | nil
        }

  @doc "Returns the Zoi schema for this type."
  def schema, do: @schema
end
