# Generated by mix bibbidi.gen — do not edit manually
defmodule Bibbidi.Types.Network.RequestData do
  @moduledoc """
  `network.RequestData`

  ## Fields

  - `request` - `t:Bibbidi.Types.Network.Request.t/0` (required)
  - `url` - `String.t()` (required)
  - `method` - `String.t()` (required)
  - `headers` - list of `t:Bibbidi.Types.Network.Header.t/0` (required)
  - `cookies` - list of `t:Bibbidi.Types.Network.Cookie.t/0` (required)
  - `headers_size` - `t:Bibbidi.Types.JsUint.t/0` (required)
  - `body_size` - `t:Bibbidi.Types.JsUint.t/0` or `nil` (required)
  - `destination` - `String.t()` (required)
  - `initiator_type` - `String.t()` or `nil` (required)
  - `timings` - `t:Bibbidi.Types.Network.FetchTimingInfo.t/0` (required)
  """

  @schema Zoi.map(%{
            request: Zoi.lazy({Bibbidi.Types.Network.Request, :schema, []}),
            url: Zoi.string(),
            method: Zoi.string(),
            headers: Zoi.list(Zoi.lazy({Bibbidi.Types.Network.Header, :schema, []})),
            cookies: Zoi.list(Zoi.lazy({Bibbidi.Types.Network.Cookie, :schema, []})),
            headers_size: Zoi.lazy({Bibbidi.Types.JsUint, :schema, []}),
            body_size: Zoi.union([Zoi.lazy({Bibbidi.Types.JsUint, :schema, []}), Zoi.null()]),
            destination: Zoi.string(),
            initiator_type: Zoi.union([Zoi.string(), Zoi.null()]),
            timings: Zoi.lazy({Bibbidi.Types.Network.FetchTimingInfo, :schema, []})
          })
  @type t :: %{
          request: Bibbidi.Types.Network.Request.t(),
          url: String.t(),
          method: String.t(),
          headers: [Bibbidi.Types.Network.Header.t()],
          cookies: [Bibbidi.Types.Network.Cookie.t()],
          headers_size: Bibbidi.Types.JsUint.t(),
          body_size: Bibbidi.Types.JsUint.t() | nil,
          destination: String.t(),
          initiator_type: String.t() | nil,
          timings: Bibbidi.Types.Network.FetchTimingInfo.t()
        }

  @doc "Returns the Zoi schema for this type."
  def schema, do: @schema
end
