# Generated by mix bibbidi.gen — do not edit manually
defmodule Bibbidi.Types.Network.ResponseContent do
  @moduledoc """
  `network.ResponseContent`

  ## Fields

  - `size` - `t:Bibbidi.Types.JsUint.t/0` (required)
  """

  @schema Zoi.map(%{size: Zoi.lazy({Bibbidi.Types.JsUint, :schema, []})})
  @type t :: %{size: Bibbidi.Types.JsUint.t()}

  @doc "Returns the Zoi schema for this type."
  def schema, do: @schema
end
