# Generated by mix bibbidi.gen — do not edit manually
defmodule Bibbidi.Types.Network.ResponseData do
  @moduledoc """
  `network.ResponseData`

  ## Fields

  - `url` - `String.t()` (required)
  - `protocol` - `String.t()` (required)
  - `status` - `t:Bibbidi.Types.JsUint.t/0` (required)
  - `status_text` - `String.t()` (required)
  - `from_cache` - `boolean()` (required)
  - `headers` - list of `t:Bibbidi.Types.Network.Header.t/0` (required)
  - `mime_type` - `String.t()` (required)
  - `bytes_received` - `t:Bibbidi.Types.JsUint.t/0` (required)
  - `headers_size` - `t:Bibbidi.Types.JsUint.t/0` or `nil` (required)
  - `body_size` - `t:Bibbidi.Types.JsUint.t/0` or `nil` (required)
  - `content` - `t:Bibbidi.Types.Network.ResponseContent.t/0` (required)
  - `auth_challenges` - list of `t:Bibbidi.Types.Network.AuthChallenge.t/0` (optional)
  """

  @schema Zoi.map(%{
            url: Zoi.string(),
            protocol: Zoi.string(),
            status: Zoi.lazy({Bibbidi.Types.JsUint, :schema, []}),
            status_text: Zoi.string(),
            from_cache: Zoi.boolean(),
            headers: Zoi.list(Zoi.lazy({Bibbidi.Types.Network.Header, :schema, []})),
            mime_type: Zoi.string(),
            bytes_received: Zoi.lazy({Bibbidi.Types.JsUint, :schema, []}),
            headers_size: Zoi.union([Zoi.lazy({Bibbidi.Types.JsUint, :schema, []}), Zoi.null()]),
            body_size: Zoi.union([Zoi.lazy({Bibbidi.Types.JsUint, :schema, []}), Zoi.null()]),
            content: Zoi.lazy({Bibbidi.Types.Network.ResponseContent, :schema, []}),
            auth_challenges:
              Zoi.list(Zoi.lazy({Bibbidi.Types.Network.AuthChallenge, :schema, []}))
              |> Zoi.optional()
          })
  @type t :: %{
          url: String.t(),
          protocol: String.t(),
          status: Bibbidi.Types.JsUint.t(),
          status_text: String.t(),
          from_cache: boolean(),
          headers: [Bibbidi.Types.Network.Header.t()],
          mime_type: String.t(),
          bytes_received: Bibbidi.Types.JsUint.t(),
          headers_size: Bibbidi.Types.JsUint.t() | nil,
          body_size: Bibbidi.Types.JsUint.t() | nil,
          content: Bibbidi.Types.Network.ResponseContent.t(),
          auth_challenges: [Bibbidi.Types.Network.AuthChallenge.t()] | nil
        }

  @doc "Returns the Zoi schema for this type."
  def schema, do: @schema
end
