# Generated by mix bibbidi.gen — do not edit manually
defmodule Bibbidi.Types.Network.SameSite do
  @moduledoc """
  `network.SameSite`

  Values: `strict`, `lax`, `none`, `default`
  """

  @schema Zoi.enum(["strict", "lax", "none", "default"])
  @type t :: String.t()
  @values ~w(strict lax none default)

  @doc "Returns the Zoi schema for this type."
  def schema, do: @schema

  @doc "Returns the list of valid values."
  def values, do: @values
end
