# Generated by mix bibbidi.gen — do not edit manually
defmodule Bibbidi.Types.Network.SetCookieHeader do
  @moduledoc """
  `network.SetCookieHeader`

  ## Fields

  - `name` - `String.t()` (required)
  - `value` - `t:Bibbidi.Types.Network.BytesValue.t/0` (required)
  - `domain` - `String.t()` (optional)
  - `http_only` - `boolean()` (optional)
  - `expiry` - `String.t()` (optional)
  - `max_age` - `t:Bibbidi.Types.JsInt.t/0` (optional)
  - `path` - `String.t()` (optional)
  - `same_site` - `t:Bibbidi.Types.Network.SameSite.t/0` (optional)
  - `secure` - `boolean()` (optional)
  """

  @schema Zoi.map(%{
            name: Zoi.string(),
            value: Zoi.lazy({Bibbidi.Types.Network.BytesValue, :schema, []}),
            domain: Zoi.string() |> Zoi.optional(),
            http_only: Zoi.boolean() |> Zoi.optional(),
            expiry: Zoi.string() |> Zoi.optional(),
            max_age: Zoi.lazy({Bibbidi.Types.JsInt, :schema, []}) |> Zoi.optional(),
            path: Zoi.string() |> Zoi.optional(),
            same_site: Zoi.lazy({Bibbidi.Types.Network.SameSite, :schema, []}) |> Zoi.optional(),
            secure: Zoi.boolean() |> Zoi.optional()
          })
  @type t :: %{
          name: String.t(),
          value: Bibbidi.Types.Network.BytesValue.t(),
          domain: String.t() | nil,
          http_only: boolean() | nil,
          expiry: String.t() | nil,
          max_age: Bibbidi.Types.JsInt.t() | nil,
          path: String.t() | nil,
          same_site: Bibbidi.Types.Network.SameSite.t() | nil,
          secure: boolean() | nil
        }

  @doc "Returns the Zoi schema for this type."
  def schema, do: @schema
end
