# Generated by mix bibbidi.gen — do not edit manually
defmodule Bibbidi.Types.Network.UrlPattern do
  @moduledoc """
  `network.UrlPattern`

  One of:
  - `t:Bibbidi.Types.Network.UrlPatternPattern.t/0`
  - `t:Bibbidi.Types.Network.UrlPatternString.t/0`
  """

  @schema Zoi.union([
            Zoi.lazy({Bibbidi.Types.Network.UrlPatternPattern, :schema, []}),
            Zoi.lazy({Bibbidi.Types.Network.UrlPatternString, :schema, []})
          ])
  @type t ::
          Bibbidi.Types.Network.UrlPatternPattern.t() | Bibbidi.Types.Network.UrlPatternString.t()

  @doc "Returns the Zoi schema for this type."
  def schema, do: @schema
end
