# Generated by mix bibbidi.gen — do not edit manually
defmodule Bibbidi.Types.Network.UrlPatternPattern do
  @moduledoc """
  `network.UrlPatternPattern`

  ## Fields

  - `type` - `"pattern"` (required)
  - `protocol` - `String.t()` (optional)
  - `hostname` - `String.t()` (optional)
  - `port` - `String.t()` (optional)
  - `pathname` - `String.t()` (optional)
  - `search` - `String.t()` (optional)
  """

  @schema Zoi.map(%{
            type: Zoi.string(),
            protocol: Zoi.string() |> Zoi.optional(),
            hostname: Zoi.string() |> Zoi.optional(),
            port: Zoi.string() |> Zoi.optional(),
            pathname: Zoi.string() |> Zoi.optional(),
            search: Zoi.string() |> Zoi.optional()
          })
  @type t :: %{
          type: String.t(),
          protocol: String.t() | nil,
          hostname: String.t() | nil,
          port: String.t() | nil,
          pathname: String.t() | nil,
          search: String.t() | nil
        }

  @doc "Returns the Zoi schema for this type."
  def schema, do: @schema
end
