# Generated by mix bibbidi.gen — do not edit manually
defmodule Bibbidi.Commands.Emulation.SetTouchOverride do
  @moduledoc """
  Command struct for `emulation.setTouchOverride`.

  [WebDriver BiDi Spec](https://w3c.github.io/webdriver-bidi/#command-emulation-setTouchOverride)
  ## Fields

  - `max_touch_points` - `term()` or `nil` (required)
  - `contexts` - list of `t:Bibbidi.Types.BrowsingContext.t/0` (optional)
  - `user_contexts` - list of `t:Bibbidi.Types.Browser.UserContext.t/0` (optional)

  """

  @derive Bibbidi.Telemetry.Metadata
  @schema Zoi.struct(__MODULE__, %{
            max_touch_points: Zoi.union([Zoi.any(), Zoi.null()]),
            contexts: Zoi.list(Bibbidi.Types.BrowsingContext.schema()) |> Zoi.optional(),
            user_contexts: Zoi.list(Bibbidi.Types.Browser.UserContext.schema()) |> Zoi.optional(),
            meta: Zoi.any() |> Zoi.optional()
          })
  @opts_schema Zoi.keyword(
                 contexts: Zoi.list(Zoi.any()) |> Zoi.optional(),
                 user_contexts: Zoi.list(Zoi.any()) |> Zoi.optional()
               )
  @result_schema Zoi.map(Zoi.string(), Zoi.any())

  @type t :: unquote(Zoi.type_spec(@schema))
  @type opts :: unquote(Zoi.type_spec(@opts_schema))
  @type result :: unquote(Zoi.type_spec(@result_schema))

  @enforce_keys Zoi.Struct.enforce_keys(@schema)
  defstruct Zoi.Struct.struct_fields(@schema)

  @doc "Returns the Zoi schema for this command struct."
  def schema, do: @schema

  @doc "Returns the Zoi schema for the keyword options."
  def opts_schema, do: @opts_schema

  @doc "Returns the Zoi schema for the result type."
  def result_schema, do: @result_schema

  defimpl Bibbidi.Encodable do
    def method(_), do: "emulation.setTouchOverride"

    def params(cmd) do
      optional = [
        {:contexts, cmd.contexts},
        {:userContexts, cmd.user_contexts}
      ]

      Enum.reduce(optional, %{maxTouchPoints: cmd.max_touch_points}, fn
        {_key, nil}, acc -> acc
        {key, value}, acc -> Map.put(acc, key, value)
      end)
    end
  end
end
