# Generated by mix bibbidi.gen — do not edit manually
defmodule Bibbidi.Commands.Browser.CreateUserContext do
  @moduledoc """
  Command struct for `browser.createUserContext`.

  [WebDriver BiDi Spec](https://w3c.github.io/webdriver-bidi/#command-browser-createUserContext)
  ## Fields

  - `accept_insecure_certs` - `boolean()` (optional)
  - `proxy` - `t:Bibbidi.Types.Session.ProxyConfiguration.t/0` (optional)
  - `unhandled_prompt_behavior` - `t:Bibbidi.Types.Session.UserPromptHandler.t/0` (optional)

  """

  @derive Bibbidi.Telemetry.Metadata
  @schema Zoi.struct(__MODULE__, %{
            accept_insecure_certs: Zoi.boolean() |> Zoi.optional(),
            proxy: Bibbidi.Types.Session.ProxyConfiguration.schema() |> Zoi.optional(),
            unhandled_prompt_behavior:
              Bibbidi.Types.Session.UserPromptHandler.schema() |> Zoi.optional(),
            meta: Zoi.any() |> Zoi.optional()
          })
  @opts_schema Zoi.keyword(
                 accept_insecure_certs: Zoi.boolean() |> Zoi.optional(),
                 proxy: Zoi.any() |> Zoi.optional(),
                 unhandled_prompt_behavior: Zoi.any() |> Zoi.optional()
               )
  @result_schema Zoi.map(%{user_context: Bibbidi.Types.Browser.UserContext.schema()})

  @type t :: unquote(Zoi.type_spec(@schema))
  @type opts :: unquote(Zoi.type_spec(@opts_schema))
  @type result :: unquote(Zoi.type_spec(@result_schema))

  @enforce_keys Zoi.Struct.enforce_keys(@schema)
  defstruct Zoi.Struct.struct_fields(@schema)

  @doc "Returns the Zoi schema for this command struct."
  def schema, do: @schema

  @doc "Returns the Zoi schema for the keyword options."
  def opts_schema, do: @opts_schema

  @doc "Returns the Zoi schema for the result type."
  def result_schema, do: @result_schema

  defimpl Bibbidi.Encodable do
    def method(_), do: "browser.createUserContext"

    def params(cmd) do
      optional = [
        {:acceptInsecureCerts, cmd.accept_insecure_certs},
        {:proxy, cmd.proxy},
        {:unhandledPromptBehavior, cmd.unhandled_prompt_behavior}
      ]

      Enum.reduce(optional, %{}, fn
        {_key, nil}, acc -> acc
        {key, value}, acc -> Map.put(acc, key, value)
      end)
    end
  end
end
