# Generated by mix bibbidi.gen — do not edit manually
defmodule Bibbidi.Commands.Browser.SetDownloadBehavior do
  @moduledoc """
  Command struct for `browser.setDownloadBehavior`.
  """

  @derive Bibbidi.Telemetry.Metadata
  @schema Zoi.struct(__MODULE__, %{
            download_behavior: Zoi.union([Zoi.any(), Zoi.null()]),
            user_contexts: Zoi.list(Zoi.any()) |> Zoi.optional(),
            meta: Zoi.any() |> Zoi.optional()
          })
  @opts_schema Zoi.keyword(user_contexts: Zoi.list(Zoi.any()) |> Zoi.optional())
  @result_schema Zoi.map(Zoi.string(), Zoi.any())

  @type t :: unquote(Zoi.type_spec(@schema))
  @type opts :: unquote(Zoi.type_spec(@opts_schema))
  @type result :: unquote(Zoi.type_spec(@result_schema))

  @enforce_keys Zoi.Struct.enforce_keys(@schema)
  defstruct Zoi.Struct.struct_fields(@schema)

  @doc "Returns the Zoi schema for this command struct."
  def schema, do: @schema

  @doc "Returns the Zoi schema for the keyword options."
  def opts_schema, do: @opts_schema

  @doc "Returns the Zoi schema for the result type."
  def result_schema, do: @result_schema

  defimpl Bibbidi.Encodable do
    def method(_), do: "browser.setDownloadBehavior"

    def params(cmd) do
      optional = [
        {:userContexts, cmd.user_contexts}
      ]

      Enum.reduce(optional, %{downloadBehavior: cmd.download_behavior}, fn
        {_key, nil}, acc -> acc
        {key, value}, acc -> Map.put(acc, key, value)
      end)
    end
  end
end
