# Generated by mix bibbidi.gen — do not edit manually
defmodule Bibbidi.Commands.Browser.SetClientWindowState do
  @moduledoc """
  Command struct for `browser.setClientWindowState`.

  [WebDriver BiDi Spec](https://w3c.github.io/webdriver-bidi/#command-browser-setClientWindowState)
  ## Fields

  - `client_window` - `t:Bibbidi.Types.Browser.ClientWindow.t/0` (required)
  - `state` - `"fullscreen"` or `"maximized"` or `"minimized"` (optional)
  - `width` - `t:Bibbidi.Types.JsUint.t/0` (optional)
  - `height` - `t:Bibbidi.Types.JsUint.t/0` (optional)
  - `x` - `t:Bibbidi.Types.JsInt.t/0` (optional)
  - `y` - `t:Bibbidi.Types.JsInt.t/0` (optional)

  """

  @derive Bibbidi.Telemetry.Metadata
  @schema Zoi.struct(__MODULE__, %{
            client_window: Bibbidi.Types.Browser.ClientWindow.schema(),
            state: Zoi.union([Zoi.string(), Zoi.string(), Zoi.string()]) |> Zoi.optional(),
            width: Bibbidi.Types.JsUint.schema() |> Zoi.optional(),
            height: Bibbidi.Types.JsUint.schema() |> Zoi.optional(),
            x: Bibbidi.Types.JsInt.schema() |> Zoi.optional(),
            y: Bibbidi.Types.JsInt.schema() |> Zoi.optional(),
            meta: Zoi.any() |> Zoi.optional()
          })
  @opts_schema Zoi.keyword(
                 state: Zoi.union([Zoi.string(), Zoi.string(), Zoi.string()]) |> Zoi.optional(),
                 width: Zoi.any() |> Zoi.optional(),
                 height: Zoi.any() |> Zoi.optional(),
                 x: Zoi.any() |> Zoi.optional(),
                 y: Zoi.any() |> Zoi.optional()
               )
  @result_schema Zoi.map(%{
                   active: Zoi.boolean(),
                   client_window: Bibbidi.Types.Browser.ClientWindow.schema(),
                   height: Bibbidi.Types.JsUint.schema(),
                   state: Zoi.union([Zoi.string(), Zoi.string(), Zoi.string(), Zoi.string()]),
                   width: Bibbidi.Types.JsUint.schema(),
                   x: Bibbidi.Types.JsInt.schema(),
                   y: Bibbidi.Types.JsInt.schema()
                 })

  @type t :: unquote(Zoi.type_spec(@schema))
  @type opts :: unquote(Zoi.type_spec(@opts_schema))
  @type result :: unquote(Zoi.type_spec(@result_schema))

  @enforce_keys Zoi.Struct.enforce_keys(@schema)
  defstruct Zoi.Struct.struct_fields(@schema)

  @doc "Returns the Zoi schema for this command struct."
  def schema, do: @schema

  @doc "Returns the Zoi schema for the keyword options."
  def opts_schema, do: @opts_schema

  @doc "Returns the Zoi schema for the result type."
  def result_schema, do: @result_schema

  defimpl Bibbidi.Encodable do
    def method(_), do: "browser.setClientWindowState"

    def params(cmd) do
      optional = [
        {:state, cmd.state},
        {:width, cmd.width},
        {:height, cmd.height},
        {:x, cmd.x},
        {:y, cmd.y}
      ]

      Enum.reduce(optional, %{clientWindow: cmd.client_window}, fn
        {_key, nil}, acc -> acc
        {key, value}, acc -> Map.put(acc, key, value)
      end)
    end
  end
end
