# Generated by mix bibbidi.gen — do not edit manually
defmodule Bibbidi.Events.Network.AuthRequired do
  @moduledoc """
  Event struct for `network.authRequired`.

  Params type: `network.AuthRequiredParameters`
  """

  @derive {Bibbidi.Telemetry.Metadata, keys: [:context, :navigation, :request]}
  defstruct [
    :context,
    :is_blocked,
    :navigation,
    :redirect_count,
    :request,
    :timestamp,
    :user_context,
    :intercepts,
    :response
  ]
end
