# Generated by mix bibbidi.gen — do not edit manually
defmodule Bibbidi.Commands.BrowsingContext.CaptureScreenshot do
  @moduledoc """
  Command struct for `browsingContext.captureScreenshot`.

  [WebDriver BiDi Spec](https://w3c.github.io/webdriver-bidi/#command-browsingContext-captureScreenshot)
  ## Fields

  - `context` - `t:Bibbidi.Types.BrowsingContext.t/0` (required)
  - `origin` - `"viewport"` or `"document"` (optional)
  - `format` - `t:Bibbidi.Types.BrowsingContext.ImageFormat.t/0` (optional)
  - `clip` - `t:Bibbidi.Types.BrowsingContext.ClipRectangle.t/0` (optional)

  """

  @derive Bibbidi.Telemetry.Metadata
  @schema Zoi.struct(__MODULE__, %{
            context: Bibbidi.Types.BrowsingContext.schema(),
            origin: Zoi.union([Zoi.string(), Zoi.string()]) |> Zoi.optional(),
            format: Bibbidi.Types.BrowsingContext.ImageFormat.schema() |> Zoi.optional(),
            clip: Bibbidi.Types.BrowsingContext.ClipRectangle.schema() |> Zoi.optional(),
            meta: Zoi.any() |> Zoi.optional()
          })
  @opts_schema Zoi.keyword(
                 origin: Zoi.union([Zoi.string(), Zoi.string()]) |> Zoi.optional(),
                 format: Zoi.any() |> Zoi.optional(),
                 clip: Zoi.any() |> Zoi.optional()
               )
  @result_schema Zoi.map(%{data: Zoi.string()})

  @type t :: unquote(Zoi.type_spec(@schema))
  @type opts :: unquote(Zoi.type_spec(@opts_schema))
  @type result :: unquote(Zoi.type_spec(@result_schema))

  @enforce_keys Zoi.Struct.enforce_keys(@schema)
  defstruct Zoi.Struct.struct_fields(@schema)

  @doc "Returns the Zoi schema for this command struct."
  def schema, do: @schema

  @doc "Returns the Zoi schema for the keyword options."
  def opts_schema, do: @opts_schema

  @doc "Returns the Zoi schema for the result type."
  def result_schema, do: @result_schema

  defimpl Bibbidi.Encodable do
    def method(_), do: "browsingContext.captureScreenshot"

    def params(cmd) do
      optional = [
        {:origin, cmd.origin},
        {:format, cmd.format},
        {:clip, cmd.clip}
      ]

      Enum.reduce(optional, %{context: cmd.context}, fn
        {_key, nil}, acc -> acc
        {key, value}, acc -> Map.put(acc, key, value)
      end)
    end
  end
end
