# Generated by mix bibbidi.gen — do not edit manually
defmodule Bibbidi.Commands.BrowsingContext.Create do
  @moduledoc """
  Command struct for `browsingContext.create`.

  [WebDriver BiDi Spec](https://w3c.github.io/webdriver-bidi/#command-browsingContext-create)
  ## Fields

  - `type` - `t:Bibbidi.Types.BrowsingContext.CreateType.t/0` (required)
  - `reference_context` - `t:Bibbidi.Types.BrowsingContext.t/0` (optional)
  - `background` - `boolean()` (optional)
  - `user_context` - `t:Bibbidi.Types.Browser.UserContext.t/0` (optional)

  """

  @derive Bibbidi.Telemetry.Metadata
  @schema Zoi.struct(__MODULE__, %{
            type: Bibbidi.Types.BrowsingContext.CreateType.schema(),
            reference_context: Bibbidi.Types.BrowsingContext.schema() |> Zoi.optional(),
            background: Zoi.boolean() |> Zoi.optional(),
            user_context: Bibbidi.Types.Browser.UserContext.schema() |> Zoi.optional(),
            meta: Zoi.any() |> Zoi.optional()
          })
  @opts_schema Zoi.keyword(
                 reference_context: Zoi.any() |> Zoi.optional(),
                 background: Zoi.boolean() |> Zoi.optional(),
                 user_context: Zoi.any() |> Zoi.optional()
               )
  @result_schema Zoi.map(%{
                   context: Bibbidi.Types.BrowsingContext.schema(),
                   user_context: Bibbidi.Types.Browser.UserContext.schema() |> Zoi.optional()
                 })

  @type t :: unquote(Zoi.type_spec(@schema))
  @type opts :: unquote(Zoi.type_spec(@opts_schema))
  @type result :: unquote(Zoi.type_spec(@result_schema))

  @enforce_keys Zoi.Struct.enforce_keys(@schema)
  defstruct Zoi.Struct.struct_fields(@schema)

  @doc "Returns the Zoi schema for this command struct."
  def schema, do: @schema

  @doc "Returns the Zoi schema for the keyword options."
  def opts_schema, do: @opts_schema

  @doc "Returns the Zoi schema for the result type."
  def result_schema, do: @result_schema

  defimpl Bibbidi.Encodable do
    def method(_), do: "browsingContext.create"

    def params(cmd) do
      optional = [
        {:referenceContext, cmd.reference_context},
        {:background, cmd.background},
        {:userContext, cmd.user_context}
      ]

      Enum.reduce(optional, %{type: cmd.type}, fn
        {_key, nil}, acc -> acc
        {key, value}, acc -> Map.put(acc, key, value)
      end)
    end
  end
end
