# Generated by mix bibbidi.gen — do not edit manually
defmodule Bibbidi.Commands.BrowsingContext.LocateNodes do
  @moduledoc """
  Command struct for `browsingContext.locateNodes`.

  [WebDriver BiDi Spec](https://w3c.github.io/webdriver-bidi/#command-browsingContext-locateNodes)
  ## Fields

  - `context` - `t:Bibbidi.Types.BrowsingContext.t/0` (required)
  - `locator` - `t:Bibbidi.Types.BrowsingContext.Locator.t/0` (required)
  - `max_node_count` - `term()` (optional)
  - `serialization_options` - `t:Bibbidi.Types.Script.SerializationOptions.t/0` (optional)
  - `start_nodes` - list of `t:Bibbidi.Types.Script.SharedReference.t/0` (optional)

  """

  @derive Bibbidi.Telemetry.Metadata
  @schema Zoi.struct(__MODULE__, %{
            context: Bibbidi.Types.BrowsingContext.schema(),
            locator: Bibbidi.Types.BrowsingContext.Locator.schema(),
            max_node_count: Zoi.any() |> Zoi.optional(),
            serialization_options:
              Bibbidi.Types.Script.SerializationOptions.schema() |> Zoi.optional(),
            start_nodes:
              Zoi.list(Bibbidi.Types.Script.SharedReference.schema()) |> Zoi.optional(),
            meta: Zoi.any() |> Zoi.optional()
          })
  @opts_schema Zoi.keyword(
                 max_node_count: Zoi.any() |> Zoi.optional(),
                 serialization_options: Zoi.any() |> Zoi.optional(),
                 start_nodes: Zoi.list(Zoi.any()) |> Zoi.optional()
               )
  @result_schema Zoi.map(%{nodes: Zoi.list(Bibbidi.Types.Script.NodeRemoteValue.schema())})

  @type t :: unquote(Zoi.type_spec(@schema))
  @type opts :: unquote(Zoi.type_spec(@opts_schema))
  @type result :: unquote(Zoi.type_spec(@result_schema))

  @enforce_keys Zoi.Struct.enforce_keys(@schema)
  defstruct Zoi.Struct.struct_fields(@schema)

  @doc "Returns the Zoi schema for this command struct."
  def schema, do: @schema

  @doc "Returns the Zoi schema for the keyword options."
  def opts_schema, do: @opts_schema

  @doc "Returns the Zoi schema for the result type."
  def result_schema, do: @result_schema

  defimpl Bibbidi.Encodable do
    def method(_), do: "browsingContext.locateNodes"

    def params(cmd) do
      optional = [
        {:maxNodeCount, cmd.max_node_count},
        {:serializationOptions, cmd.serialization_options},
        {:startNodes, cmd.start_nodes}
      ]

      Enum.reduce(optional, %{context: cmd.context, locator: cmd.locator}, fn
        {_key, nil}, acc -> acc
        {key, value}, acc -> Map.put(acc, key, value)
      end)
    end
  end
end
