# Generated by mix bibbidi.gen — do not edit manually
defmodule Bibbidi.Commands.BrowsingContext.Navigate do
  @moduledoc """
  Command struct for `browsingContext.navigate`.

  [WebDriver BiDi Spec](https://w3c.github.io/webdriver-bidi/#command-browsingContext-navigate)
  ## Fields

  - `context` - `t:Bibbidi.Types.BrowsingContext.t/0` (required)
  - `url` - `String.t()` (required)
  - `wait` - `t:Bibbidi.Types.BrowsingContext.ReadinessState.t/0` (optional)

  """

  @derive Bibbidi.Telemetry.Metadata
  @schema Zoi.struct(__MODULE__, %{
            context: Bibbidi.Types.BrowsingContext.schema(),
            url: Zoi.string(),
            wait: Bibbidi.Types.BrowsingContext.ReadinessState.schema() |> Zoi.optional(),
            meta: Zoi.any() |> Zoi.optional()
          })
  @opts_schema Zoi.keyword(wait: Zoi.any() |> Zoi.optional())
  @result_schema Zoi.map(%{
                   navigation:
                     Zoi.union([Bibbidi.Types.BrowsingContext.Navigation.schema(), Zoi.null()]),
                   url: Zoi.string()
                 })

  @type t :: unquote(Zoi.type_spec(@schema))
  @type opts :: unquote(Zoi.type_spec(@opts_schema))
  @type result :: unquote(Zoi.type_spec(@result_schema))

  @enforce_keys Zoi.Struct.enforce_keys(@schema)
  defstruct Zoi.Struct.struct_fields(@schema)

  @doc "Returns the Zoi schema for this command struct."
  def schema, do: @schema

  @doc "Returns the Zoi schema for the keyword options."
  def opts_schema, do: @opts_schema

  @doc "Returns the Zoi schema for the result type."
  def result_schema, do: @result_schema

  defimpl Bibbidi.Encodable do
    def method(_), do: "browsingContext.navigate"

    def params(cmd) do
      optional = [
        {:wait, cmd.wait}
      ]

      Enum.reduce(optional, %{context: cmd.context, url: cmd.url}, fn
        {_key, nil}, acc -> acc
        {key, value}, acc -> Map.put(acc, key, value)
      end)
    end
  end
end
