# Generated by mix bibbidi.gen — do not edit manually
defmodule Bibbidi.Commands.BrowsingContext.Print do
  @moduledoc """
  Command struct for `browsingContext.print`.
  """

  @derive Bibbidi.Telemetry.Metadata
  @schema Zoi.struct(__MODULE__, %{
            context: Zoi.any(),
            background: Zoi.boolean() |> Zoi.optional(),
            margin: Zoi.any() |> Zoi.optional(),
            orientation: Zoi.union([Zoi.string(), Zoi.string()]) |> Zoi.optional(),
            page: Zoi.any() |> Zoi.optional(),
            page_ranges: Zoi.list(Zoi.union([Zoi.any(), Zoi.string()])) |> Zoi.optional(),
            scale: Zoi.any() |> Zoi.optional(),
            shrink_to_fit: Zoi.boolean() |> Zoi.optional(),
            meta: Zoi.any() |> Zoi.optional()
          })
  @opts_schema Zoi.keyword(
                 background: Zoi.boolean() |> Zoi.optional(),
                 margin: Zoi.any() |> Zoi.optional(),
                 orientation: Zoi.union([Zoi.string(), Zoi.string()]) |> Zoi.optional(),
                 page: Zoi.any() |> Zoi.optional(),
                 page_ranges: Zoi.list(Zoi.union([Zoi.any(), Zoi.string()])) |> Zoi.optional(),
                 scale: Zoi.any() |> Zoi.optional(),
                 shrink_to_fit: Zoi.boolean() |> Zoi.optional()
               )
  @result_schema Zoi.map(%{data: Zoi.string()})

  @type t :: unquote(Zoi.type_spec(@schema))
  @type opts :: unquote(Zoi.type_spec(@opts_schema))
  @type result :: unquote(Zoi.type_spec(@result_schema))

  @enforce_keys Zoi.Struct.enforce_keys(@schema)
  defstruct Zoi.Struct.struct_fields(@schema)

  @doc "Returns the Zoi schema for this command struct."
  def schema, do: @schema

  @doc "Returns the Zoi schema for the keyword options."
  def opts_schema, do: @opts_schema

  @doc "Returns the Zoi schema for the result type."
  def result_schema, do: @result_schema

  defimpl Bibbidi.Encodable do
    def method(_), do: "browsingContext.print"

    def params(cmd) do
      optional = [
        {:background, cmd.background},
        {:margin, cmd.margin},
        {:orientation, cmd.orientation},
        {:page, cmd.page},
        {:pageRanges, cmd.page_ranges},
        {:scale, cmd.scale},
        {:shrinkToFit, cmd.shrink_to_fit}
      ]

      Enum.reduce(optional, %{context: cmd.context}, fn
        {_key, nil}, acc -> acc
        {key, value}, acc -> Map.put(acc, key, value)
      end)
    end
  end
end
