# Generated by mix bibbidi.gen — do not edit manually
defmodule Bibbidi.Commands.BrowsingContext.Reload do
  @moduledoc """
  Command struct for `browsingContext.reload`.
  """

  @derive Bibbidi.Telemetry.Metadata
  @schema Zoi.struct(__MODULE__, %{
            context: Zoi.any(),
            ignore_cache: Zoi.boolean() |> Zoi.optional(),
            wait: Zoi.any() |> Zoi.optional(),
            meta: Zoi.any() |> Zoi.optional()
          })
  @opts_schema Zoi.keyword(
                 ignore_cache: Zoi.boolean() |> Zoi.optional(),
                 wait: Zoi.any() |> Zoi.optional()
               )
  @result_schema Zoi.map(%{navigation: Zoi.union([Zoi.any(), Zoi.null()]), url: Zoi.string()})

  @type t :: unquote(Zoi.type_spec(@schema))
  @type opts :: unquote(Zoi.type_spec(@opts_schema))
  @type result :: unquote(Zoi.type_spec(@result_schema))

  @enforce_keys Zoi.Struct.enforce_keys(@schema)
  defstruct Zoi.Struct.struct_fields(@schema)

  @doc "Returns the Zoi schema for this command struct."
  def schema, do: @schema

  @doc "Returns the Zoi schema for the keyword options."
  def opts_schema, do: @opts_schema

  @doc "Returns the Zoi schema for the result type."
  def result_schema, do: @result_schema

  defimpl Bibbidi.Encodable do
    def method(_), do: "browsingContext.reload"

    def params(cmd) do
      optional = [
        {:ignoreCache, cmd.ignore_cache},
        {:wait, cmd.wait}
      ]

      Enum.reduce(optional, %{context: cmd.context}, fn
        {_key, nil}, acc -> acc
        {key, value}, acc -> Map.put(acc, key, value)
      end)
    end
  end
end
