# Generated by mix bibbidi.gen — do not edit manually
defmodule Bibbidi.Commands.Script.AddPreloadScript do
  @moduledoc """
  Command struct for `script.addPreloadScript`.

  [WebDriver BiDi Spec](https://w3c.github.io/webdriver-bidi/#command-script-addPreloadScript)
  ## Fields

  - `function_declaration` - `String.t()` (required)
  - `arguments` - list of `t:Bibbidi.Types.Script.ChannelValue.t/0` (optional)
  - `contexts` - list of `t:Bibbidi.Types.BrowsingContext.t/0` (optional)
  - `user_contexts` - list of `t:Bibbidi.Types.Browser.UserContext.t/0` (optional)
  - `sandbox` - `String.t()` (optional)

  """

  @derive Bibbidi.Telemetry.Metadata
  @schema Zoi.struct(__MODULE__, %{
            function_declaration: Zoi.string(),
            arguments: Zoi.list(Bibbidi.Types.Script.ChannelValue.schema()) |> Zoi.optional(),
            contexts: Zoi.list(Bibbidi.Types.BrowsingContext.schema()) |> Zoi.optional(),
            user_contexts: Zoi.list(Bibbidi.Types.Browser.UserContext.schema()) |> Zoi.optional(),
            sandbox: Zoi.string() |> Zoi.optional(),
            meta: Zoi.any() |> Zoi.optional()
          })
  @opts_schema Zoi.keyword(
                 arguments: Zoi.list(Zoi.any()) |> Zoi.optional(),
                 contexts: Zoi.list(Zoi.any()) |> Zoi.optional(),
                 user_contexts: Zoi.list(Zoi.any()) |> Zoi.optional(),
                 sandbox: Zoi.string() |> Zoi.optional()
               )
  @result_schema Zoi.map(%{script: Bibbidi.Types.Script.PreloadScript.schema()})

  @type t :: unquote(Zoi.type_spec(@schema))
  @type opts :: unquote(Zoi.type_spec(@opts_schema))
  @type result :: unquote(Zoi.type_spec(@result_schema))

  @enforce_keys Zoi.Struct.enforce_keys(@schema)
  defstruct Zoi.Struct.struct_fields(@schema)

  @doc "Returns the Zoi schema for this command struct."
  def schema, do: @schema

  @doc "Returns the Zoi schema for the keyword options."
  def opts_schema, do: @opts_schema

  @doc "Returns the Zoi schema for the result type."
  def result_schema, do: @result_schema

  defimpl Bibbidi.Encodable do
    def method(_), do: "script.addPreloadScript"

    def params(cmd) do
      optional = [
        {:arguments, cmd.arguments},
        {:contexts, cmd.contexts},
        {:userContexts, cmd.user_contexts},
        {:sandbox, cmd.sandbox}
      ]

      Enum.reduce(optional, %{functionDeclaration: cmd.function_declaration}, fn
        {_key, nil}, acc -> acc
        {key, value}, acc -> Map.put(acc, key, value)
      end)
    end
  end
end
