# Generated by mix bibbidi.gen — do not edit manually
defmodule Bibbidi.Commands.Script.CallFunction do
  @moduledoc """
  Command struct for `script.callFunction`.
  """

  @schema Zoi.struct(__MODULE__, %{
            function_declaration: Zoi.string(),
            await_promise: Zoi.boolean(),
            target: Zoi.any(),
            arguments: Zoi.list(Zoi.any()) |> Zoi.optional(),
            result_ownership: Zoi.any() |> Zoi.optional(),
            serialization_options: Zoi.any() |> Zoi.optional(),
            this: Zoi.any() |> Zoi.optional(),
            user_activation: Zoi.boolean() |> Zoi.optional()
          })
  @opts_schema Zoi.keyword(
                 arguments: Zoi.list(Zoi.any()) |> Zoi.optional(),
                 result_ownership: Zoi.any() |> Zoi.optional(),
                 serialization_options: Zoi.any() |> Zoi.optional(),
                 this: Zoi.any() |> Zoi.optional(),
                 user_activation: Zoi.boolean() |> Zoi.optional()
               )
  @result_schema Zoi.any()

  @type t :: unquote(Zoi.type_spec(@schema))
  @type opts :: unquote(Zoi.type_spec(@opts_schema))
  @type result :: unquote(Zoi.type_spec(@result_schema))

  @enforce_keys Zoi.Struct.enforce_keys(@schema)
  defstruct Zoi.Struct.struct_fields(@schema)

  @doc "Returns the Zoi schema for this command struct."
  def schema, do: @schema

  @doc "Returns the Zoi schema for the keyword options."
  def opts_schema, do: @opts_schema

  @doc "Returns the Zoi schema for the result type."
  def result_schema, do: @result_schema

  defimpl Bibbidi.Encodable do
    def method(_), do: "script.callFunction"

    def params(cmd) do
      optional = [
        {:arguments, cmd.arguments},
        {:resultOwnership, cmd.result_ownership},
        {:serializationOptions, cmd.serialization_options},
        {:this, cmd.this},
        {:userActivation, cmd.user_activation}
      ]

      Enum.reduce(
        optional,
        %{
          functionDeclaration: cmd.function_declaration,
          awaitPromise: cmd.await_promise,
          target: cmd.target
        },
        fn
          {_key, nil}, acc -> acc
          {key, value}, acc -> Map.put(acc, key, value)
        end
      )
    end
  end
end
