# Generated by mix bibbidi.gen — do not edit manually
defmodule Bibbidi.Commands.Script.Disown do
  @moduledoc """
  Command struct for `script.disown`.
  """

  @schema Zoi.struct(__MODULE__, %{handles: Zoi.list(Zoi.any()), target: Zoi.any()})
  @opts_schema Zoi.keyword([])
  @result_schema Zoi.map(Zoi.string(), Zoi.any())

  @type t :: unquote(Zoi.type_spec(@schema))
  @type opts :: unquote(Zoi.type_spec(@opts_schema))
  @type result :: unquote(Zoi.type_spec(@result_schema))

  @enforce_keys Zoi.Struct.enforce_keys(@schema)
  defstruct Zoi.Struct.struct_fields(@schema)

  @doc "Returns the Zoi schema for this command struct."
  def schema, do: @schema

  @doc "Returns the Zoi schema for the keyword options."
  def opts_schema, do: @opts_schema

  @doc "Returns the Zoi schema for the result type."
  def result_schema, do: @result_schema

  defimpl Bibbidi.Encodable do
    def method(_), do: "script.disown"

    def params(cmd), do: %{handles: cmd.handles, target: cmd.target}
  end
end
