# Generated by mix bibbidi.gen — do not edit manually
defmodule Bibbidi.Commands.Script.Disown do
  @moduledoc """
  Command struct for `script.disown`.

  [WebDriver BiDi Spec](https://w3c.github.io/webdriver-bidi/#command-script-disown)
  ## Fields

  - `handles` - list of `t:Bibbidi.Types.Script.Handle.t/0` (required)
  - `target` - `t:Bibbidi.Types.Script.Target.t/0` (required)

  """

  @derive Bibbidi.Telemetry.Metadata
  @schema Zoi.struct(__MODULE__, %{
            handles: Zoi.list(Bibbidi.Types.Script.Handle.schema()),
            target: Bibbidi.Types.Script.Target.schema(),
            meta: Zoi.any() |> Zoi.optional()
          })
  @opts_schema Zoi.keyword([])
  @result_schema Zoi.map(Zoi.string(), Zoi.any())

  @type t :: unquote(Zoi.type_spec(@schema))
  @type opts :: unquote(Zoi.type_spec(@opts_schema))
  @type result :: unquote(Zoi.type_spec(@result_schema))

  @enforce_keys Zoi.Struct.enforce_keys(@schema)
  defstruct Zoi.Struct.struct_fields(@schema)

  @doc "Returns the Zoi schema for this command struct."
  def schema, do: @schema

  @doc "Returns the Zoi schema for the keyword options."
  def opts_schema, do: @opts_schema

  @doc "Returns the Zoi schema for the result type."
  def result_schema, do: @result_schema

  defimpl Bibbidi.Encodable do
    def method(_), do: "script.disown"

    def params(cmd), do: %{handles: cmd.handles, target: cmd.target}
  end
end
