# Generated by mix bibbidi.gen — do not edit manually
defmodule Bibbidi.Commands.Script.GetRealms do
  @moduledoc """
  Command struct for `script.getRealms`.

  [WebDriver BiDi Spec](https://w3c.github.io/webdriver-bidi/#command-script-getRealms)
  ## Fields

  - `context` - `t:Bibbidi.Types.BrowsingContext.t/0` (optional)
  - `type` - `t:Bibbidi.Types.Script.RealmType.t/0` (optional)

  """

  @derive Bibbidi.Telemetry.Metadata
  @schema Zoi.struct(__MODULE__, %{
            context: Bibbidi.Types.BrowsingContext.schema() |> Zoi.optional(),
            type: Bibbidi.Types.Script.RealmType.schema() |> Zoi.optional(),
            meta: Zoi.any() |> Zoi.optional()
          })
  @opts_schema Zoi.keyword(
                 context: Zoi.any() |> Zoi.optional(),
                 type: Zoi.any() |> Zoi.optional()
               )
  @result_schema Zoi.map(%{realms: Zoi.list(Zoi.any())})

  @type t :: unquote(Zoi.type_spec(@schema))
  @type opts :: unquote(Zoi.type_spec(@opts_schema))
  @type result :: unquote(Zoi.type_spec(@result_schema))

  @enforce_keys Zoi.Struct.enforce_keys(@schema)
  defstruct Zoi.Struct.struct_fields(@schema)

  @doc "Returns the Zoi schema for this command struct."
  def schema, do: @schema

  @doc "Returns the Zoi schema for the keyword options."
  def opts_schema, do: @opts_schema

  @doc "Returns the Zoi schema for the result type."
  def result_schema, do: @result_schema

  defimpl Bibbidi.Encodable do
    def method(_), do: "script.getRealms"

    def params(cmd) do
      optional = [
        {:context, cmd.context},
        {:type, cmd.type}
      ]

      Enum.reduce(optional, %{}, fn
        {_key, nil}, acc -> acc
        {key, value}, acc -> Map.put(acc, key, value)
      end)
    end
  end
end
