# Generated by mix bibbidi.gen — do not edit manually
defmodule Bibbidi.Events.Input.FileDialogOpened do
  @moduledoc """
  Event struct for `input.fileDialogOpened`.

  Params type: `input.FileDialogInfo`
  """

  @derive {Bibbidi.Telemetry.Metadata, keys: [:context]}
  defstruct [:context, :user_context, :element, :multiple]
end
